#!/home/odoo/devel/venv/bin/python2
# -*- coding: utf-8 -*-
# Copyright (C) 2015-2021 SHS-AV s.r.l. (<http://www.zeroincombenze.org>)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
"""
    Zeroincombenze® unit test library for python programs Regression Test Suite
    You can use this file as main all_tests.py too
"""
import os
import sys
try:
    import z0testlib
    Z0BUG = z0testlib.Z0test()
except ImportError:
    from zerobug import Z0BUG


__version__ = "1.0.2.2"


def version():
    return __version__


if __name__ == "__main__":
    exit(
        Z0BUG.main(
            Z0BUG.parseoptest(
                sys.argv[1:], version=version()
            )
        )
    )
