.\" Manpage for please.
.\" Contact antoniomaria.vigliotti@gmail.com to correct errors or typos.
.TH venv_mgr 8
.SH NAME
venv_mgr \- virtual environment management
.SH SYNOPSIS
venv_mgr [options] action [directory]
.SH DESCRIPTION
\fBvenv_mgr\fR is an interactive tool which adds new features to standard virtual environment command.
.P
Action is one of:
.br
* help
.br
* cp
.br
* create
.br
* exec
.br
* info
.br
* install
.br
* merge
.br
* mv
.br
* update
.br
* test
.br
* reset
.P
\fBcp\fR
.RS
Copy SOURCE environment directory to DEST, like cp bash command but set relative path inside virtual environment
to correct the new directory name.
.RE
.P
\fBcreate\fR
.RS
Create a new virtual environment directory like virtualenv bach command but with some nice features.
.br
This action can install various python packages to create ready to use environment directory.
.br
See -I -D -O -r switches to furthermore informations.
.RE
.SH OPTIONS
.TP
.BR \-D
With create or reset action, install or upgrade development packages.
.TP
.BR \-I
Run isolated mode, without accessing system packages.
.TP
.TP
.SH EXAMPLES
venv_mgr create -DI -O 3.5 my_venv
.SH BUGS
No known bugs.
.SH AUTHOR
Antonio Maria Vigliotti (antoniomaria.vigliotti@gmail.com)
