#!/bin/bash
if [[ -z $1  || $1 == "-h" ]]; then
  echo "$0 action odoo_vid"
  echo ""
  echo "odoo_vid example: 10.0 12.0 oca16"
  echo ""
  echo "action is:"
  echo "  start"
  echo "  stop"
  echo "  restart"
  echo "  status"
  echo "  enable"
  echo "  disable"
  exit 1
fi
svc=""
[[ -f /etc/init.d/$2 ]] && svc="$2"
if [[ -z $svc ]]; then
  m=$(echo $2 | grep -Eo "[0-9]+" | head -n1)
  [[ -f /etc/init.d/odoo$m ]] && svc="odoo$m"
  [[ -z $svc && -f /etc/init.d/odoo${m}-server ]] && svc="odoo${m}-server"
  [[ -z $svc && $2 =~ ^oca && -f /etc/init.d/odoo${m}-oca ]] && svc="odoo${m}-oca"
fi
[[ -z $svc ]] && echo "Service $2 not found!" && exit 126
if [[ $1 =~ (start|stop|restart|status|enable|disable) ]]; then
  echo "systemctl $1 $svc"
  sudo systemctl $1 $svc
else
  echo "Invalid action $1"
  echo "$0 start|stop|restart|status|enable|disable $2"
  exit 1
fi
exit 0
