# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Zeroincombenze(R)
org_slug: zeroincombenze
rebel_module_groups: []
repo_description: Addons concerning Odoo Italian Localization.
repo_name: pypi
repo_slug: pypi
repo_website: git@github.com:zeroincombenze
travis_apt_packages: []
travis_apt_sources: []
