#! /bin/bash
# -*- coding: utf-8 -*-
# Sample of Regression tests
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=.
  RUNDIR=..
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=.
elif [ -d ../_travis ]; then
  TRAVISDIR=..
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
  Z0LIBDIR=$TDIR
elif [ -e ./z0librc ]; then
. ./z0librc
  Z0LIBDIR=.
elif [ -e ../z0librc ]; then
. ../z0librc
  Z0LIBDIR=..
elif [ -e ~/z0librc ]; then
. ~/z0librc
  Z0LIBDIR=~
else
. /etc/z0librc
  Z0LIBDIR=/etc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
  Z0TLIBDIR=$TDIR
elif [ -e ./z0testrc ]; then
. ./z0testrc
  Z0TLIBDIR=.
elif [ -e ../z0testrc ]; then
. ../z0testrc
  Z0TLIBDIR=..
else
. ~/dev/z0testrc
  Z0TLIBDIR=~
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)
Z0LIBDIR=$(readlink -e $Z0LIBDIR)
Z0TLIBDIR=$(readlink -e $Z0TLIBDIR)

__version__=0.2.1
parseoptest -l$TESTDIR/test_product.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
sts=0
TPRODUCT="$RUNDIR/product -t"

test_run () {
# test_run(msg,package,disto,TRES)
    # set -x #debug
    local msg="$1"
    local Package="$2"
    local Disto="$3"
    local TRES="$4"
    local FH=
    local opt_e="-E$Disto"
    if [ "$Disto" == "." ]; then
        local FH=$Real_FH
        local Disto=$Real_DISTO
        local opt_e=
    elif [ "$Disto" == "Ubuntu12" -o "$Disto" == "Ubuntu14" ]; then
      local FH="Debian"
    elif [ "$Disto" == "CentOS6" -o "$Disto" == "CentOS7" ]; then
      local FH="RHEL"
    fi
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      RES=$(eval $TPRODUCT $opt_e realname $Package)
    fi
    # set +x #debug
    ci-test "$msg" "$RES" "$TRES"
    return $s
}

if [ ${opt_dry_run:-0} -eq 0 ]; then
  cat <<EOF >$TESTDIR/res/LAMP__Debian.test
LAMP (by product)()
python-pip (by apt-get)(pip --version)
LAMP_security (by product)()
openssh-server (by apt-get)()
- TCP port 22
apache2 (by apt-get)(apachectl -v)
- TCP port 80
- TCP port 443
mysql-server (by apt-get)(mysql-server --version)
postgresql (by apt-get)(psql --version)
php5 (by apt-get)(php5 -v)
python (by apt-get)(python --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__CentOS6.test
LAMP (by product)()
epel-release (by yum)(epel-release --version)
pip (by yum)(pip --version)
yum-utils (by yum)(yum-utils --version)
LAMP_security (by product)()
openssh-server (by yum)()
- TCP port 22
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
mysql-server (by yum)(mysql-server --version)
postgresql-server (by yum)(psql --version)
php (by yum)(php -v)
python (by yum)(python --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__CentOS7.test
LAMP (by product)()
epel-release (by yum)(epel-release --version)
python-pip (by yum)(pip --version)
yum-utils (by yum)(yum-utils --version)
LAMP_security (by product)()
openssh-server (by yum)()
- TCP port 22
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
mariadb (by yum)(mariadb --version)
postgresql-server (by yum)(psql --version)
php (by yum)(php -v)
python (by yum)(python --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP_security__Debian.test
LAMP_security (by product)()
--libffi-dev (by apt-get)(libffi-dev --version)
--libssl-dev (by apt-get)(libssl-dev --version)
--python-openssl (by apt-get)(python-openssl --version)
--build-essential (by apt-get)(build-essential --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP_security__CentOS7.test
LAMP_security (by product)()
--libffi-devel (by yum)(libffi-devel --version)
--pyOpenSSL (by yum)(pyOpenSSL --version)
--pyasn1 (by pip)()
--ndg-httpsclient (by pip)()
EOF
  cat <<EOF >$TESTDIR/res/LAMP_security__CentOS6.test
LAMP_security (by product)()
--openssl-devel (by yum)(openssl-devel --version)
--libffi-devel (by yum)(libffi-devel --version)
--pyOpenSSL (by yum)(pyOpenSSL --version)
--pyasn1 (by pip)()
--ndg-httpsclient (by pip)()
EOF
  cat <<EOF >$TESTDIR/res/httpd.test
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
EOF
  cat <<EOF >$TESTDIR/res/apache2.test
apache2 (by apt-get)(apachectl -v)
- TCP port 80
- TCP port 443
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__Debian.test
mysql-server (by apt-get)(mysql-server --version)
--libapache2-mod-auth-mysql (by apt-get)(libapache2-mod-auth-mysql --version)
EOF
  cat <<EOF >$TESTDIR/res/mysql__CentOS7.test
mariadb (by yum)(mariadb --version)
--mariadb-server (by yum)(mariadb-server --version)
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__CentOS7.test
mariadb-server (by yum)(mariadb-server --version)
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__CentOS6.test
mysql-server (by yum)(mysql-server --version)
EOF
  cat <<EOF >$TESTDIR/res/postgres__Debian.test
postgres (by apt-get)(postgres --version)
EOF
  cat <<EOF >$TESTDIR/res/postgres__RHEL.test
postgres (by yum)(postgres --version)
EOF
  cat <<EOF >$TESTDIR/res/postgres-server__Debian.test
postgres-server (by apt-get)(postgres-server --version)
EOF
  cat <<EOF >$TESTDIR/res/postgres-server__RHEL.test
postgres-server (by yum)(postgres-server --version)
EOF
fi
Real_FH=$(xuname "-f")
x=$(xuname "-v")
v=$(echo $x|awk -F. '{print $1}')
Real_DISTO=$(xuname "-d")$v

for Package in LAMP LAMP_security apache2 httpd mysql mysql-server postgres postgres-server; do
  for Disto in . Ubuntu14 CentOS7 Ubuntu12 CentOS6; do
     if [ "$Disto" == "." ]; then
       opt_e=
     else
       opt_e="-E$Disto"
     fi
     test_run "whatis $Package $opt_e" "$Package" "$Disto" "diff"
  done
done

if [ ${opt_dry_run:-0} -ne 0 ]; then
  echo "$ctr"
fi
exit $sts
