#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on product
# Check for remove
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=.
  RUNDIR=..
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=.
elif [ -d ../_travis ]; then
  TRAVISDIR=..
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
  Z0LIBDIR=$TDIR
elif [ -e ./z0librc ]; then
. ./z0librc
  Z0LIBDIR=.
elif [ -e ../z0librc ]; then
. ../z0librc
  Z0LIBDIR=..
elif [ -e ~/z0librc ]; then
. ~/z0librc
  Z0LIBDIR=~
else
. /etc/z0librc
  Z0LIBDIR=/etc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
  Z0TLIBDIR=$TDIR
elif [ -e ./z0testrc ]; then
. ./z0testrc
  Z0TLIBDIR=.
elif [ -e ../z0testrc ]; then
. ../z0testrc
  Z0TLIBDIR=..
else
. ~/dev/z0testrc
  Z0TLIBDIR=~
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)
Z0LIBDIR=$(readlink -e $Z0LIBDIR)
Z0TLIBDIR=$(readlink -e $Z0TLIBDIR)

__version__=0.2.1.19
parseoptest -l$TESTDIR/test_product.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
sts=0
TPRODUCT="$RUNDIR/product -T"

test_run () {
# test_run(msg,package,disto,cmd)
    # set -x #debug
    local msg="$1"
    local Package="$2"
    local Disto="$3"
    local cmd="$4"
    local FH=
    local opt_e="-E$Disto"
    local opt_ij="-I$Package,wget,gcc,git"
    if [ "$Disto" == "." ]; then
        local FH=$Real_FH
        local Disto=$Real_DISTO
        local opt_e=
    elif [ "$Disto" == "Ubuntu12" -o "$Disto" == "Ubuntu14" ]; then
      local FH="Debian"
    elif [ "$Disto" == "CentOS6" -o "$Disto" == "CentOS7" ]; then
      local FH="RHEL"
    fi
    if [ "$Package" == "httpd" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="apache2"
      fi
      local opt_ij="-I$Package,vsftpd"
    elif [ "$Package" == "apache2" ]; then
      if [ "$FH" == "RHEL" ]; then
        local Package="httpd"
      fi
      local opt_ij="-I$Package,vsftpd"
    elif [ "$Package" == "pip" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="python-pip"
        local opt_ij="-I$Package"
      elif [ "$Disto" == "CentOS7" ]; then
        local Package="python-pip"
        local opt_ij="-I$Package"
      fi
    elif [ "$Package" == "python-pip" -a "$Disto" == "CentOS6" ]; then
      local Package="pip"
      local opt_ij="-I$Package"
    elif [ "$Package" == "postgresql-server" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="postgresql"
      fi
      local opt_ij="-I$Package,postgresql-client-common,postgresql-contrib"
    elif [ "$Package" == "postgresql" ]; then
      if [ "$FH" == "RHEL" ]; then
        local Package="postgresql-server"
      fi
      local opt_ij="-I$Package,postgresql-client-common,postgresql-contrib"
    elif [ "$Package" == "postgres" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="postgresql"
      elif [ "$FH" == "RHEL" ]; then
        local Package="postgresql-server"
      fi
      local opt_ij="-I$Package,postgresql-client-common,postgresql-contrib"
    elif [ "$Package" == "openssh" ]; then
      local Package="openssh-server"
      opt_ij="-I$Package,openssh-client,openssh-clients,mod_ssl,mod_proxy_html,iptables-services,bind-utils"
    elif [ "$Package" == "openssh-server" ]; then
      opt_ij="-I$Package,openssh-client,openssh-clients,mod_ssl,mod_proxy_html,iptables-services,bind-utils"
    fi
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $TESTDIR/res/${Package}__${Disto}.07.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${Disto}.07.test
      elif [ -f $TESTDIR/res/${Package}__${FH}.07.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${FH}.07.test
      elif [ -f $TESTDIR/res/${Package}.07.test ]; then
        TESTOUT=$TESTDIR/res/${Package}.07.test
      else
        TESTOUT=
        echo "File test comparison ${Package}__${Disto} not found!"
      fi
      rm -f $TESTDIR/product.out
      eval $TPRODUCT $opt_e remove $2 $opt_ij>$TESTDIR/product.out
    fi
    # set +x #debug
    ci-test "$msg" "$TESTOUT" "$TESTDIR/product.out" "$cmd"
    return $s
}

if [ ${opt_dry_run:-0} -eq 0 ]; then
  rm -f $TESTDIR/res/*.07.test
  cat <<EOF >$TESTDIR/res/product__Debian.07.test
> rm /usr/bin/product
> rm /usr/bin/product.*
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/product__RHEL.07.test
> rm /usr/bin/product
> rm /usr/bin/product.*
EOF
  cat <<EOF >$TESTDIR/res/apache2__Debian.07.test
> service apache2 stop
# service vsftpd stop
> apt-get -y remove apache2
# apt-get -y remove vsftpd
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/httpd__CentOS7.07.test
> systemctl stop httpd
# systemctl stop vsftpd
> yum -y remove httpd
# yum -y remove vsftpd
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
EOF
  cat <<EOF >$TESTDIR/res/httpd__CentOS6.07.test
> service httpd stop
> yum -y remove httpd
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__CentOS7.07.test
> systemctl stop postgresql
> yum -y remove postgresql-server
# yum -y remove postgresql-client-common
# yum -y remove postgresql-contrib
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__CentOS6.07.test
> service postgresql stop
> yum -y remove postgresql-server
# yum -y remove postgresql-client-common
# yum -y remove postgresql-contrib
EOF
  cat <<EOF >$TESTDIR/res/postgresql__Debian.07.test
> service postgresql stop
> apt-get -y remove postgresql
# apt-get -y remove postgresql-client-common
# apt-get -y remove postgresql-contrib
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/python-pip__Debian.07.test
> apt-get -y remove python-pip
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/python-pip__RHEL.07.test
> yum -y remove python-pip
EOF
  cat <<EOF >$TESTDIR/res/pip.07.test
> yum -y remove pip
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__Debian.07.test
> service ssh stop
> apt-get -y remove openssh-server
# apt-get -y remove openssh-client
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__CentOS7.07.test
> systemctl stop sshd
> yum -y remove openssh-server
# yum -y remove openssh-clients
# yum -y remove mod_ssl
# yum -y remove mod_proxy_html
# yum -y remove iptables-services
# yum -y remove bind-utils
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__CentOS6.07.test
> service sshd stop
> yum -y remove openssh-server
# yum -y remove openssh-clients
# yum -y remove mod_ssl
# yum -y remove mod_proxy_html
# yum -y remove iptables-services
# yum -y remove bind-utils
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
EOF
fi
Real_FH=$(xuname "-f")
x=$(xuname "-v")
v=$(echo $x|awk -F. '{print $1}')
Real_DISTO=$(xuname "-d")$v

for Package in product apache2 httpd\
  pip python-pip\
  postgres postgresql postgresql-server\
  openssh openssh-server; do
  for Disto in . Ubuntu14 CentOS7 Ubuntu12 CentOS6; do
     if [ "$Disto" == "." ]; then
       opt_e=
     else
       opt_e="-E$Disto"
     fi
     test_run "remove $Package $opt_e" "$Package" "$Disto" "diff"
  done
done

if [ ${opt_dry_run:-0} -ne 0 ]; then
  echo "$ctr"
fi
exit $sts
