#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on product
# Check for whatis
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=.
  RUNDIR=..
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=.
elif [ -d ../_travis ]; then
  TRAVISDIR=..
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
  Z0LIBDIR=$TDIR
elif [ -e ./z0librc ]; then
. ./z0librc
  Z0LIBDIR=.
elif [ -e ../z0librc ]; then
. ../z0librc
  Z0LIBDIR=..
elif [ -e ~/z0librc ]; then
. ~/z0librc
  Z0LIBDIR=~
else
. /etc/z0librc
  Z0LIBDIR=/etc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
  Z0TLIBDIR=$TDIR
elif [ -e ./z0testrc ]; then
. ./z0testrc
  Z0TLIBDIR=.
elif [ -e ../z0testrc ]; then
. ../z0testrc
  Z0TLIBDIR=..
else
. ~/dev/z0testrc
  Z0TLIBDIR=~
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)
Z0LIBDIR=$(readlink -e $Z0LIBDIR)
Z0TLIBDIR=$(readlink -e $Z0TLIBDIR)

__version__=0.2.1.22
parseoptest -l$TESTDIR/test_product.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
sts=0
TPRODUCT="$RUNDIR/product -t"

test_run () {
# test_run(msg,package,disto,cmd)
    # set -x #debug
    local msg="$1"
    local Package="$2"
    local Disto="$3"
    local cmd="$4"
    local FH=
    local opt_e="-E$Disto"
    if [ "$Disto" == "." ]; then
        local FH=$Real_FH
        local Disto=$Real_DISTO
        local opt_e=
    elif [ "$Disto" == "Ubuntu12" -o "$Disto" == "Ubuntu14" ]; then
      local FH="Debian"
    elif [ "$Disto" == "CentOS6" -o "$Disto" == "CentOS7" ]; then
      local FH="RHEL"
    fi
    if [ "$Package" == "httpd" ]; then
      if [ "$Disto" == "Ubuntu12" -o "$Disto" == "Ubuntu14" ]; then
        local Package="apache2"
      fi
    elif [ "$Package" == "apache2" ]; then
      if [ "$Disto" == "CentOS6" -o "$Disto" == "CentOS7" ]; then
        local Package="httpd"
      fi
    elif [ "$Package" == "pip" -a "$Disto" != "CentOS6" ]; then
      local Package="python-pip"
    elif [ "$Package" == "python-pip" -a "$Disto" == "CentOS6" ]; then
      local Package="pip"
    elif [ "$Package" == "mysql" ]; then
      if [ "$Disto" == "CentOS7" ]; then
         local Package="mariadb"
      else
        local Package="mysql-server"
      fi
    elif [ "$Package" == "mariadb" -o "$Package" == "mariadb-server" ]; then
      if [ "$Disto" == "CentOS6" -o "$FH" == "Debian" ]; then
        local Package="mysql-server"
      fi
    elif [ "$Package" == "php" -a "$FH" == "Debian" ]; then
      local Package="php5"
    elif [ "$Package" == "php5" -a "$FH" == "RHEL" ]; then
      local Package="php"
    elif [ "$Package" == "openssh" ]; then
      local Package="openssh-server"
    fi
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $TESTDIR/res/${Package}__${Disto}.03.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${Disto}.03.test
      elif [ -f $TESTDIR/res/${Package}__${FH}.03.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${FH}.03.test
      elif [ -f $TESTDIR/res/${Package}.03.test ]; then
        TESTOUT=$TESTDIR/res/${Package}.03.test
      else
        TESTOUT=
        echo "File test comparison ${Package}__${Disto} not found!"
      fi
      rm -f $TESTDIR/product.out
      eval $TPRODUCT $opt_e whatis $2 >$TESTDIR/product.out
      # eval $TPRODUCT $opt_e whatis $2
    fi
    # set +x #debug
    ci-test "$msg" "$TESTOUT" "$TESTDIR/product.out" "$cmd"
    return $s
}

if [ ${opt_dry_run:-0} -eq 0 ]; then
  rm -f $TESTDIR/res/*.03.test
  cat <<EOF >$TESTDIR/res/product.03.test
product (by git)(product -V)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__Debian.03.test
LAMP (by product)()
python-pip (by apt-get)(pip --version)
libffi-dev (by apt-get)(libffi-dev --version)
libssl-dev (by apt-get)(libssl-dev --version)
python-openssl (by apt-get)(python-openssl --version)
build-essential (by apt-get)(build-essential --version)
openssh-server (by apt-get)()
- TCP port 22
apache2 (by apt-get)(apachectl -v)
- TCP port 80
- TCP port 443
mysql-server (by apt-get)(mysql --version)
postgresql (by apt-get)(psql --version)
php5 (by apt-get)(php5 -v)
python (by apt-get)(python --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__CentOS6.03.test
LAMP (by product)()
epel-release (by yum)(epel-release --version)
pip (by yum)(pip --version)
yum-utils (by yum)(yum-utils --version)
openssl-devel (by yum)(openssl-devel --version)
libffi-devel (by yum)(libffi-devel --version)
pyOpenSSL (by yum)(pyOpenSSL --version)
pyasn1 (by pip)()
ndg-httpsclient (by pip)()
openssh-server (by yum)()
- TCP port 22
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
mysql-server (by yum)(mysql --version)
postgresql-server (by yum)(psql --version)
php (by yum)(php -v)
python (by yum)(python --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__CentOS7.03.test
LAMP (by product)()
epel-release (by yum)(epel-release --version)
python-pip (by yum)(pip --version)
python-wheel (by yum)(python-wheel --version)
yum-utils (by yum)(yum-utils --version)
libffi-devel (by yum)(libffi-devel --version)
pyOpenSSL (by yum)(pyOpenSSL --version)
pyasn1 (by pip)()
ndg-httpsclient (by pip)()
openssh-server (by yum)()
- TCP port 22
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
mariadb (by yum)(mysql --version)
postgresql-server (by yum)(psql --version)
php (by yum)(php -v)
python (by yum)(python --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP_security__Debian.03.test
libffi-dev (by apt-get)(libffi-dev --version)
libssl-dev (by apt-get)(libssl-dev --version)
python-openssl (by apt-get)(python-openssl --version)
build-essential (by apt-get)(build-essential --version)
EOF
  cat <<EOF >$TESTDIR/res/LAMP_security__CentOS7.03.test
libffi-devel (by yum)(libffi-devel --version)
pyOpenSSL (by yum)(pyOpenSSL --version)
pyasn1 (by pip)()
ndg-httpsclient (by pip)()
EOF
  cat <<EOF >$TESTDIR/res/LAMP_security__CentOS6.03.test
openssl-devel (by yum)(openssl-devel --version)
libffi-devel (by yum)(libffi-devel --version)
pyOpenSSL (by yum)(pyOpenSSL --version)
pyasn1 (by pip)()
ndg-httpsclient (by pip)()
EOF
  cat <<EOF >$TESTDIR/res/httpd__CentOS7.03.test
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
--vsftpd (by yum)()
- TCP port 21
EOF
  cat <<EOF >$TESTDIR/res/httpd__CentOS6.03.test
httpd (by yum)(apachectl -v)
- TCP port 80
- TCP port 443
EOF
  cat <<EOF >$TESTDIR/res/apache2.03.test
apache2 (by apt-get)(apachectl -v)
- TCP port 80
- TCP port 443
--vsftpd (by apt-get)()
- TCP port 21
EOF
  cat <<EOF >$TESTDIR/res/python-pip__CentOS7.03.test
python-pip (by yum)(pip --version)
EOF
  cat <<EOF >$TESTDIR/res/pip__CentOS6.03.test
pip (by yum)(pip --version)
EOF
  cat <<EOF >$TESTDIR/res/python-pip__Debian.03.test
python-pip (by apt-get)(pip --version)
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__Debian.03.test
mysql-server (by apt-get)(mysql --version)
--libapache2-mod-auth-mysql (by apt-get)(libapache2-mod-auth-mysql --version)
EOF
  cat <<EOF >$TESTDIR/res/mariadb__CentOS7.03.test
mariadb (by yum)(mysql --version)
--mariadb-server (by yum)(mysql --version)
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__CentOS7.03.test
mariadb-server (by yum)(mysql --version)
EOF
  cat <<EOF >$TESTDIR/res/mariadb-server__CentOS7.03.test
mariadb-server (by yum)(mysql --version)
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__CentOS6.03.test
mysql-server (by yum)(mysql --version)
--libapache2-mod-auth-mysql (by yum)(libapache2-mod-auth-mysql --version)
EOF
  cat <<EOF >$TESTDIR/res/postgres__Debian.03.test
postgresql (by apt-get)(psql --version)
--postgresql-client-common (by apt-get)()
--postgresql-contrib (by apt-get)()
EOF
  cat <<EOF >$TESTDIR/res/postgres__RHEL.03.test
postgresql-server (by yum)(psql --version)
--postgresql-client-common (by yum)()
--postgresql-contrib (by yum)()
EOF
  cat <<EOF >$TESTDIR/res/postgresql__Debian.03.test
postgresql (by apt-get)(psql --version)
--postgresql-client-common (by apt-get)()
--postgresql-contrib (by apt-get)()
EOF
  cat <<EOF >$TESTDIR/res/postgresql__RHEL.03.test
postgresql-server (by yum)(psql --version)
--postgresql-client-common (by yum)()
--postgresql-contrib (by yum)()
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__Debian.03.test
postgresql (by apt-get)(psql --version)
--postgresql-client-common (by apt-get)()
--postgresql-contrib (by apt-get)()
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__RHEL.03.test
postgresql-server (by yum)(psql --version)
--postgresql-client-common (by yum)()
--postgresql-contrib (by yum)()
EOF
  cat <<EOF >$TESTDIR/res/php__RHEL.03.test
php (by yum)(php -v)
--php-mysql (by yum)(php-mysql --version)
--php-common (by yum)(php-common --version)
--php-xml (by yum)(php-xml --version)
--php-cli (by yum)(php-cli --version)
EOF
  cat <<EOF >$TESTDIR/res/php5__Debian.03.test
php5 (by apt-get)(php5 -v)
--php5-mysql (by apt-get)(php5-mysql --version)
--php5-common (by apt-get)(php5-common --version)
--php5-xml (by apt-get)(php5-xml --version)
--php5-cli (by apt-get)(php5-cli --version)
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__RHEL.03.test
openssh-server (by yum)()
- TCP port 22
--openssh-clients (by yum)(ssh -V)
--mod_ssl (by yum)(mod_ssl --version)
--mod_proxy_html (by yum)(mod_proxy_html --version)
--iptables-services (by yum)(iptables-services --version)
--bind-utils (by yum)(bind-utils --version)
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__Debian.03.test
openssh-server (by apt-get)()
- TCP port 22
--openssh-client (by apt-get)(ssh -V)
EOF
fi
Real_FH=$(xuname "-f")
x=$(xuname "-v")
v=$(echo $x|awk -F. '{print $1}')
Real_DISTO=$(xuname "-d")$v

for Package in product LAMP LAMP_security apache2 httpd pip python-pip\
 mysql mysql-server mariadb mariadb-server\
 postgres postgresql postgresql-server php php5\
 openssh openssh-server; do
  for Disto in . Ubuntu14 CentOS7 Ubuntu12 CentOS6; do
     if [ "$Disto" == "." ]; then
       opt_e=
     else
       opt_e="-E$Disto"
     fi
     test_run "whatis $Package $opt_e" "$Package" "$Disto" "diff"
  done
done

if [ ${opt_dry_run:-0} -ne 0 ]; then
  echo "$ctr"
fi
exit $sts
