#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on product
# Check for commands & info
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=.
  RUNDIR=..
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=.
elif [ -d ../_travis ]; then
  TRAVISDIR=..
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
  Z0LIBDIR=$TDIR
elif [ -e ./z0librc ]; then
. ./z0librc
  Z0LIBDIR=.
elif [ -e ../z0librc ]; then
. ../z0librc
  Z0LIBDIR=..
elif [ -e ~/z0librc ]; then
. ~/z0librc
  Z0LIBDIR=~
else
. /etc/z0librc
  Z0LIBDIR=/etc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
  Z0TLIBDIR=$TDIR
elif [ -e ./z0testrc ]; then
. ./z0testrc
  Z0TLIBDIR=.
elif [ -e ../z0testrc ]; then
. ../z0testrc
  Z0TLIBDIR=..
else
. ~/dev/z0testrc
  Z0TLIBDIR=~
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)
Z0LIBDIR=$(readlink -e $Z0LIBDIR)
Z0TLIBDIR=$(readlink -e $Z0TLIBDIR)

__version__=0.2.1.25
parseoptest -l$TESTDIR/test_product.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
sts=0
TPRODUCT="$RUNDIR/product -t"

test_run () {
# test_run(msg,package,disto,cmd)
    # set -x #debug
    local msg="$1"
    local Package="$2"
    local Disto="$3"
    local cmd="$4"
    local FH=
    local opt_e="-E$Disto"
    if [ "$Disto" == "." ]; then
        local FH=$Real_FH
        local Disto=$Real_DISTO
        local opt_e=
    elif [ "$Disto" == "Ubuntu12" -o "$Disto" == "Ubuntu14" ]; then
      local FH="Debian"
    elif [ "$Disto" == "CentOS6" -o "$Disto" == "CentOS7" ]; then
      local FH="RHEL"
    fi
    # if [ "$Package" == "php" -a "$FH" == "Debian" ]; then
    #   local Package="php5"
    # elif [ "$Package" == "php5" -a "$FH" == "RHEL" ]; then
    #   local Package="php"
    # fi
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $TESTDIR/res/${Package}__${Disto}.02.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${Disto}.02.test
      elif [ -f $TESTDIR/res/${Package}__${FH}.02.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${FH}.02.test
      elif [ -f $TESTDIR/res/${Package}.02.test ]; then
        TESTOUT=$TESTDIR/res/${Package}.02.test
      else
        TESTOUT=
        echo "File test comparison ${Package}__${Disto} not found!"
      fi
      rm -f $TESTDIR/product.out
      eval $TPRODUCT $opt_e info $2 >$TESTDIR/product.out
    fi
    # set +x #debug
    ci-test "$msg" "$TESTOUT" "$TESTDIR/product.out" "$cmd"
    return $s
}

if [ ${opt_dry_run:-0} -eq 0 ]; then
  rm -f $TESTDIR/res/*.02.test
  cat <<EOF >$TESTDIR/res/product.02.test
product (install by git)
 command=product
 get ver=product -V
EOF
  cat <<EOF >$TESTDIR/res/LAMP__Debian.02.test
LAMP=(LAMP python-pip LAMP_security openssh-server apache2 mysql-server postgresql php5 python) (install by product)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__CentOS6.02.test
LAMP=(LAMP epel-release pip yum-utils LAMP_security openssh-server httpd mysql-server postgresql-server php python) (install by product)
EOF
  cat <<EOF >$TESTDIR/res/LAMP__CentOS7.02.test
LAMP=(LAMP epel-release python-pip python-wheel yum-utils LAMP_security openssh-server httpd mariadb postgresql-server php python) (install by product)
EOF
  cat <<EOF >$TESTDIR/res/httpd__RHEL.02.test
httpd (install by yum)
 service=httpd
 command=apachectl
 get ver=apachectl -v
EOF
  cat <<EOF >$TESTDIR/res/apache2__RHEL.02.test
apache2=httpd (install by yum)
 service=httpd
 command=apachectl
 get ver=apachectl -v
EOF
  cat <<EOF >$TESTDIR/res/httpd__Debian.02.test
httpd=apache2 (install by apt-get)
 service=apache2
 command=apachectl
 get ver=apachectl -v
EOF
  cat <<EOF >$TESTDIR/res/apache2__Debian.02.test
apache2 (install by apt-get)
 service=apache2
 command=apachectl
 get ver=apachectl -v
EOF
  cat <<EOF >$TESTDIR/res/pip__CentOS7.02.test
pip=python-pip (install by yum)
 command=pip
 get ver=pip --version
EOF
  cat <<EOF >$TESTDIR/res/pip__CentOS6.02.test
pip (install by yum)
 command=pip
 get ver=pip --version
EOF
  cat <<EOF >$TESTDIR/res/python-pip__CentOS7.02.test
python-pip (install by yum)
 command=pip
 get ver=pip --version
EOF
  cat <<EOF >$TESTDIR/res/python-pip__CentOS6.02.test
python-pip=pip (install by yum)
 command=pip
 get ver=pip --version
EOF
  cat <<EOF >$TESTDIR/res/pip__Debian.02.test
pip=python-pip (install by apt-get)
 command=pip
 get ver=pip --version
EOF
  cat <<EOF >$TESTDIR/res/python-pip__Debian.02.test
python-pip (install by apt-get)
 command=pip
 get ver=pip --version
EOF
  cat <<EOF >$TESTDIR/res/mysql__Debian.02.test
mysql=mysql-server (install by apt-get)
 service=mysql
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mysql__CentOS7.02.test
mysql=mariadb (install by yum)
 service=mariadb
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mysql__CentOS6.02.test
mysql=mysql-server (install by yum)
 service=mysqld
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__Debian.02.test
mysql-server (install by apt-get)
 service=mysql
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__CentOS7.02.test
mysql-server=mariadb-server (install by yum)
 service=mariadb
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mysql-server__CentOS6.02.test
mysql-server (install by yum)
 service=mysqld
 command=mysql
 get ver=mysql --version
EOF
 cat <<EOF >$TESTDIR/res/mariadb__Debian.02.test
mariadb=mysql-server (install by apt-get)
 service=mysql
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mariadb__CentOS7.02.test
mariadb (install by yum)
 service=mariadb
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mariadb__CentOS6.02.test
mariadb=mysql-server (install by yum)
 service=mysqld
 command=mysql
 get ver=mysql --version
EOF
 cat <<EOF >$TESTDIR/res/mariadb-server__Debian.02.test
mariadb-server=mysql-server (install by apt-get)
 service=mysql
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mariadb-server__CentOS7.02.test
mariadb-server (install by yum)
 service=mariadb
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/mariadb-server__CentOS6.02.test
mariadb-server=mysql-server (install by yum)
 service=mysqld
 command=mysql
 get ver=mysql --version
EOF
  cat <<EOF >$TESTDIR/res/postgres__RHEL.02.test
postgres=postgresql-server (install by yum)
 service=postgresql
 command=psql
 get ver=psql --version
EOF
  cat <<EOF >$TESTDIR/res/postgres__Debian.02.test
postgres=postgresql (install by apt-get)
 service=postgresql
 command=psql
 get ver=psql --version
EOF
  cat <<EOF >$TESTDIR/res/postgresql__RHEL.02.test
postgresql=postgresql-server (install by yum)
 service=postgresql
 command=psql
 get ver=psql --version
EOF
  cat <<EOF >$TESTDIR/res/postgresql__Debian.02.test
postgresql (install by apt-get)
 service=postgresql
 command=psql
 get ver=psql --version
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__RHEL.02.test
postgresql-server (install by yum)
 service=postgresql
 command=psql
 get ver=psql --version
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__Debian.02.test
postgresql-server=postgresql (install by apt-get)
 service=postgresql
 command=psql
 get ver=psql --version
EOF
  cat <<EOF >$TESTDIR/res/php__Debian.02.test
php=php5 (install by apt-get)
 command=php5
 get ver=php5 -v
EOF
  cat <<EOF >$TESTDIR/res/php__RHEL.02.test
php (install by yum)
 command=php
 get ver=php -v
EOF
  cat <<EOF >$TESTDIR/res/php5__RHEL.02.test
php5=php (install by yum)
 command=php
 get ver=php -v
EOF
  cat <<EOF >$TESTDIR/res/php5__Debian.02.test
php5 (install by apt-get)
 command=php5
 get ver=php5 -v
EOF
  cat <<EOF >$TESTDIR/res/openssh__RHEL.02.test
openssh=openssh-server (install by yum)
 service=sshd
EOF
  cat <<EOF >$TESTDIR/res/openssh__Debian.02.test
openssh=openssh-server (install by apt-get)
 service=ssh
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__RHEL.02.test
openssh-server (install by yum)
 service=sshd
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__Debian.02.test
openssh-server (install by apt-get)
 service=ssh
EOF
fi
Real_FH=$(xuname "-f")
x=$(xuname "-v")
v=$(echo $x|awk -F. '{print $1}')
Real_DISTO=$(xuname "-d")$v

for Package in product LAMP apache2 httpd pip python-pip\
 mysql mysql-server mariadb mariadb-server\
 postgres postgresql postgresql-server php php5\
 openssh openssh-server; do
  for Disto in . Ubuntu14 CentOS7 Ubuntu12 CentOS6; do
     if [ "$Disto" == "." ]; then
       opt_e=
     else
       opt_e="-E$Disto"
     fi
     test_run "info $Package $opt_e" "$Package" "$Disto" "diff"
  done
done

if [ ${opt_dry_run:-0} -ne 0 ]; then
  echo "$ctr"
fi
exit $sts
