#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on travis emulator
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TRAVISLIBDIR=$(findpkg travisrc "$TDIR . .. $HOME/dev $TDIR/../../travis_emulator")
if [ -z "$TRAVISLIBDIR" ]; then
  echo "Library file travisrc not found!"
  exit 2
fi
. $TRAVISLIBDIR
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.1.77.2


Z0BUG_init
parseoptest -l$TESTDIR/test_travis_em.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi

UT_LIST="__version_V_${__version__}$RUNDIR/travis"
UT_LIST="$UT_LIST __version_1_${__version__}$RUNDIR/travisrc"
UT_LIST="$UT_LIST __version_0_0.2.7_$Z0TLIBDIR/z0testrc"
UT_LIST="$UT_LIST __version_1_0.1.44$Z0LIBDIR/z0librc"
# UT_LIST="$UT_LIST test_travisrc1 test_travisrc2 test_yaml test_regex test_dist_pkg test_cronow test_vfdiff test_vfcp"
UT_LIST="$UT_LIST test_travisrc1 test_travisrc2 test_regex test_dist_pkg test_vfdiff test_vfcp"
Z0BUG_main_file "" "$UT_LIST"
exit $sts
