#! /bin/bash
# -*- coding: utf-8 -*-
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=./
  RUNDIR=../
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=./
elif [ -d ../_travis ]; then
  TRAVISDIR=../
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -e ./z0librc ]; then
. ./z0librc
elif [ -e ../z0librc ]; then
. ../z0librc
elif [ -e ~/z0librc ]; then
. ~/z0librc
else
. /etc/z0librc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
elif [ -e ./z0testrc ]; then
. ./z0testrc
elif [ -e ../z0testrc ]; then
. ../z0testrc
else
. ~/dev/z0testrc
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)

__version__=0.1.79
parseoptest -l$TESTDIR/test_travis_em.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
sts=0

TEST_GCONF=$TESTDIR/test_dist_pkg.conf
TEST_LCONF=$TESTDIR/test_local_dist_pkg.conf
if [ -f $TEST_LCONF ]; then
  rm -f $TEST_LCONF
fi
echo "# Sample conf file for test">$TEST_GCONF
echo "distpath=/opt/odoo/tools/\${prjname}">>$TEST_GCONF
echo "openerp_distpath=/opt/odoo/8.0">>$TEST_GCONF
echo "zeroincombenze_distpath=/opt/odoo/7.0/zeroincombenze">>$TEST_GCONF
echo "server_distpath=/opt/odoo/7.0/server/openerp">>$TEST_GCONF
echo "CONFN=$TEST_LCONF">>$TEST_GCONF

echo "# Sample conf file for test">$TEST_LCONF
echo "tgt9path=odoo@shsprd14:~/dev/pypi">>$TEST_LCONF


CWD=$PWD

TRES=$($RUNDIR/dist_pkg -V)
test_result "version" "$__version__" "$TRES"

cd $RUNDIR
TRES=$($RUNDIR/dist_pkg -W PKGPATH)
cd $CWD
test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"

cd $RUNDIR
cd ..
TRES=$($RUNDIR/dist_pkg -W PKGPATH)
cd $CWD
test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"

cd $TESTDIR
TRES=$($RUNDIR/dist_pkg -W PKGPATH)
cd $CWD
test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"

TRES=$($RUNDIR/dist_pkg -W PKGPATH -p /opt/odoo/dev/pypi/travis_emulator/conf)
test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"

TRES=$($RUNDIR/dist_pkg -W PKGPATH -p /opt/odoo/dev/pypi/travis_emulator/travis_emulator/conf)
test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"

TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
test_result "param LGITPATH (travis)" "/opt/odoo/tools/travis_emulator" "$TRES"

if [ "$HOSTNAME" == "shsdev14" ]; then
  cd /opt/odoo/7.0
  TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
  cd $CWD
  test_result "param LGITPATH (odoo8)" "/opt/odoo/8.0" "$TRES"
else
  test_result "dummy" "true" "true"
fi

if [ -d "/opt/openerp/7.0/zeroincombenze/l10n_it_bbone" ]; then
  cd /opt/openerp/7.0/zeroincombenze/l10n_it_bbone
  TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
  cd $CWD
  test_result "param LGITPATH (zeroincombenze)" "/opt/odoo/7.0/zeroincombenze" "$TRES"
fi

cd $TESTDIR
TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
cd $CWD
test_result "commit travis_emulator 1" "dist_pkg -n -C -p \"/opt/odoo/tools/travis_emulator\" travis_emulator travis_emulator" "$TRES"

cd $TESTDIR
cd ..
TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
cd $CWD
test_result "commit travis_emulator 2" "dist_pkg -n -C -p \"/opt/odoo/tools/travis_emulator\" travis_emulator travis_emulator" "$TRES"

if [ "$HOSTNAME" == "shsdev14" ]; then
  cd /opt/odoo/7.0
  TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
  cd $CWD
  test_result "commit openerp" "dist_pkg -n -C -p \"/opt/odoo/8.0\" 7.0 openerp" "$TRES"
else
  test_result "dummy" "true" "true"
fi

echo "distpath=/opt/odoo">>$TEST_LCONF
cd $TESTDIR
TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
cd $CWD
test_result "param LGITPATH (odoo)" "/opt/odoo" "$TRES"

if [ -d "/opt/openerp/7.0/server/openerp/workflow" ]; then
  cd /opt/openerp/7.0/server/openerp/workflow
  TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
  cd $CWD
  test_result "param LGITPATH (workflow)" "/opt/odoo/7.0/server/openerp" "$TRES"
fi

TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
test_result "commit travis_emulator" "dist_pkg -n -C -p \"/opt/odoo\" travis_emulator travis_emulator" "$TRES"


if [ ${opt_dry_run:-0} -ne 0 ]; then
  echo "$ctr"
fi
exit $sts