#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on travis emulator
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
if [ -z "$Z0TLIBDIR" ]; then
  echo "Library file z0testrc not found!"
  exit 2
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)
__version__=0.1.41.24


test_01() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_01.out
      cat <<EOF >$TESTSRC
TEST_TRAVIS
===========


EOF
      cat <<EOF >$TESTRES
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master)](https://coveralls.io/github/zeroincombenze/tools?branch=master)
[![codecov](https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/tools/branch/master)
[![Tech Doc](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-travis_emulator.svg)](http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator)
[![Help](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-travis_emulator.svg)](http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator/help)

TEST_TRAVIS
===========


[//]: # (copyright)

----

**zeroincombenze®** is a trademark of [SHS-AV s.r.l.](http://www.shs-av.com/)
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.

Odoo is a trademark of Odoo S.A.
[//]: # (end copyright)

[![chat with us](https://www.shs-av.com/wp-content/chat_with_us.gif)](https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b)
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_02() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_01.out
      cat <<EOF >$TESTSRC
|license agpl|_

TEST_TRAVIS II
==============


EOF
      cat <<EOF >$TESTRES
|build status|_
|license agpl|_
|coverage status|_
|codecov status|_
|technical doc|_
|help zeroincombenze|_

TEST_TRAVIS II
==============


.. [//]: # (copyright)

----

**zeroincombenze®** is a trademark of \`SHS-AV s.r.l.
<http://www.shs-av.com/>\`_.
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.

Odoo is a trademark of Odoo S.A.

.. [//]: # (end copyright)

.. |build status| image:: https://travis-ci.org/zeroincombenze/tools.svg?branch=master
.. _build status: https://travis-ci.org/zeroincombenze/tools
.. |license agpl| image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.. _license agpl: http://www.gnu.org/licenses/agpl-3.0.html
.. |coverage status| image:: https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master
.. _coverage status: https://coveralls.io/github/zeroincombenze/tools?branch=master
.. |codecov status| image:: https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg
.. _codecov status: https://codecov.io/gh/zeroincombenze/tools/branch/master
.. |technical doc| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-travis_emulator.svg
.. _technical doc: http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator
.. |help zeroincombenze| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-travis_emulator.svg
.. _help zeroincombenze: http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator/help
.. image:: https://www.shs-av.com/wp-content/chat_with_us.gif
   :target: https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_03() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_01.out
      cat <<EOF >$TESTSRC
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools/)
TEST_TRAVIS III
===============

[//]: # (copyright)

----

Test style Copyright
[//]: # (end copyright)

[![chat with us](http://www.shs-av.com/wp-content/chat_with_us.png)](https://www.zeroincombenze.it/chi-siamo/contatti/)
EOF
      cat <<EOF >$TESTRES
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master)](https://coveralls.io/github/zeroincombenze/tools?branch=master)
[![codecov](https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/tools/branch/master)
[![Tech Doc](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-travis_emulator.svg)](http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator)
[![Help](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-travis_emulator.svg)](http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator/help)

TEST_TRAVIS III
===============

[//]: # (copyright)

----

**zeroincombenze®** is a trademark of [SHS-AV s.r.l.](http://www.shs-av.com/)
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.

Odoo is a trademark of Odoo S.A.
[//]: # (end copyright)

[![chat with us](https://www.shs-av.com/wp-content/chat_with_us.gif)](https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b)
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_04() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_01.out
      cat <<EOF >$TESTSRC
|build status|_
|license agpl|_

TEST_TRAVIS IV
==============

.. |build status| image:: https://travis-ci.org/zeroincombenze/tools.svg?branch=master
.. _build status: https://travis-ci.org/zeroincombenze/tools
.. |license agpl| image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.. _license agpl: http://www.gnu.org/licenses/agpl-3.0.html
.. image::  http://www.shs-av.com/wp-content/chat_with_us.png
   :alt: Join the chat at https://www.zeroincombenze.it/chi-siamo/contatti/
   :target:  https://www.zeroincombenze.it/chi-siamo/contatti/
EOF
      cat <<EOF >$TESTRES
|build status|_
|license agpl|_
|coverage status|_
|codecov status|_
|technical doc|_
|help zeroincombenze|_

TEST_TRAVIS IV
==============

.. [//]: # (copyright)

----

**zeroincombenze®** is a trademark of \`SHS-AV s.r.l.
<http://www.shs-av.com/>\`_.
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.

Odoo is a trademark of Odoo S.A.

.. [//]: # (end copyright)

.. |build status| image:: https://travis-ci.org/zeroincombenze/tools.svg?branch=master
.. _build status: https://travis-ci.org/zeroincombenze/tools
.. |license agpl| image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.. _license agpl: http://www.gnu.org/licenses/agpl-3.0.html
.. |coverage status| image:: https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master
.. _coverage status: https://coveralls.io/github/zeroincombenze/tools?branch=master
.. |codecov status| image:: https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg
.. _codecov status: https://codecov.io/gh/zeroincombenze/tools/branch/master
.. |technical doc| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-travis_emulator.svg
.. _technical doc: http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator
.. |help zeroincombenze| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-travis_emulator.svg
.. _help zeroincombenze: http://wiki.zeroincombenze.org/en/Python/opt/travis_emulator/help
.. image:: https://www.shs-av.com/wp-content/chat_with_us.gif
   :target: https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

Z0BUG_setup() {
    :
}


Z0BUG_init
parseoptest -l$TESTDIR/test_travis_em.log "$@"
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
if [ ${opt_tlib:-0} -ne 0 ]; then
  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
  if [ -z "$TRAVISLIBDIR" ]; then
    echo "Library file travisrc not found!"
    exit 2
  fi
  . $TRAVISLIBDIR
fi
UT1_LIST=""
UT_LIST=""
if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
exit $sts
