#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on travis emulator
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.1.12.1


test_diff() {
    export opt_conf=$TESTDIR/test_travis.conf
    local cmd="$RUNDIR/vfdiff -c$opt_conf -nv $1 $2"
    if [ -n "$1" ]; then
      local msg1=$1
    else
      local msg1=
    fi
    if [ -n "$2" ]; then
      local msg2=$2
    else
      local msg2=.
    fi
    if [ -n "$3" ]; then
      cmd="$cmd -r $3"
      msg1=$msg1/$3
    fi
    if [ -n "$4" ]; then
      cmd="$cmd -p $4"
      msg1=$msg1/$4
    fi
    if [ -n "$5" ]; then
      if [ "${5:0:1}" == "-" ]; then
        cmd="$cmd -y"
        if [ -n "${5:1}" ]; then
          cmd="$cmd -O ${5:1}"
        fi
      else
        cmd="$cmd -O $5"
      fi
    fi
    TRES=$(eval $cmd)
    test_result "diff $msg1 $msg2" "$6" "$TRES"
}

test_01() {
    local s t
    export opt_conf=$TESTDIR/test_travis.conf
    if [ -f $opt_conf ]; then rm -f $opt_conf; fi
    touch $opt_conf
    echo "filedel=.pyc .log .bak  ~">>$opt_conf
    echo "fileignore=.conf">>$opt_conf
    echo "filediffignore=.po .pot">>$opt_conf
    for s in v7 8.0 10.0; do
      for t in v7 7.0 9.0; do
        test_diff "$s" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/$s /opt/odoo/$t"
        test_diff "~/$s" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/$s /opt/odoo/$t"
        test_diff "/opt/odoo/$s" "$t" "l10n-italy" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/$s/l10n-italy /opt/odoo/$t/l10n-italy"
        test_diff "/opt/odoo/$s" "$t" "l10n-italy" "l10n_it_vat_registries" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/$s/l10n-italy/l10n_it_vat_registries /opt/odoo/$t/l10n-italy/l10n_it_vat_registries"
        test_diff "/opt/odoo/$s/l10n-italy" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/$s/l10n-italy /opt/odoo/$t/l10n-italy"
        test_diff "/opt/odoo/$s/l10n-italy/l10n_it_vat_registries" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/$s/l10n-italy/l10n_it_vat_registries /opt/odoo/$t/l10n-italy/l10n_it_vat_registries"
        test_diff "/opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "$t" "" "" "" "> diff -ZB /opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py /opt/odoo/$t/l10n-italy/l10n_it_vat_registries/__openerp__.py"
        test_diff "/opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "" "" "" "$t" "> diff -ZB /opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py /opt/odoo/$t/l10n-italy/l10n_it_vat_registries/__openerp__.py"
        test_diff "/opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "" "" "" "-$t" "> diff -ZBy /opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py /opt/odoo/$t/l10n-italy/l10n_it_vat_registries/__openerp__.py"
      done
    done
    for s in v7 10.0; do
      test_diff "/opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "8.0" "l10n-italy-supplemental" "" "" "> diff -ZB /opt/odoo/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py /opt/odoo/8.0/l10n-italy-supplemental/l10n_it_vat_registries/__openerp__.py"
    done
    for s in 7 8; do
      test_diff "/etc/odoo/odoo$s-server.conf" "9.0" "" "" "" "> diff -ZB /etc/odoo/odoo$s-server.conf /etc/odoo/odoo9-server.conf"
    done
    test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_vat_registries/i18n/" "8.0" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries/i18n /opt/odoo/8.0/l10n-italy/l10n_it_vat_registries/i18n"
    test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_vat_registries/i18n" "8.0" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries/i18n /opt/odoo/8.0/l10n-italy/l10n_it_vat_registries/i18n"
    local CWD=$PWD
    cd /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries
    test_diff "__openerp__.py" "" "" "" "8" "> diff -ZB /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_vat_registries/__openerp__.py"
    cd $CWD
}


Z0BUG_init
parseoptest -l$TESTDIR/test_zerobug.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi

TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
if [ -z "$TRAVISLIBDIR" ]; then
  echo "Library file travisrc not found!"
  exit 2
fi
. $TRAVISLIBDIR

UT1_LIST=""
UT_LIST=""
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
exit $?
