#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on travis emulator
#
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/zerobug $HOME/dev" "zerobug")
if [ -z "$Z0TLIBDIR" ]; then
  echo "Library file z0testrc not found!"
  exit 2
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.2.1.10


test_01() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_01.out
      cat <<EOF >$TESTSRC
TEST_TRAVIS
===========


EOF
      cat <<EOF >$TESTRES
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master)](https://coveralls.io/github/zeroincombenze/tools?branch=master)
[![codecov](https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/tools/branch/master)
[![OCA_project](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-oca-master.svg)](https://github.com/OCA/tools/tree/master)
[![Tech Doc](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/dev)
[![Help](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/man/)
[![try it](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-try-it-master.svg)](http://erpmaster.zeroincombenze.it)


[![en](http://www.shs-av.com/wp-content/en_US.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS
===========


[//]: # (copyright)

----

**Odoo** is a trademark of [Odoo S.A.](https://www.odoo.com/) (formerly OpenERP, formerly TinyERP)

**OCA**, or the [Odoo Community Association](http://odoo-community.org/), is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

**zeroincombenze®** is a trademark of [SHS-AV s.r.l.](http://www.shs-av.com/)
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.
[Zeroincombenze® distribution](http://wiki.zeroincombenze.org/en/Odoo)
is mainly designed for Italian law and markeplace.
Everytime, every Odoo DB and customized code can be deployed on local server too.

[//]: # (end copyright)

[//]: # (addons)

[//]: # (end addons)

[![chat with us](https://www.shs-av.com/wp-content/chat_with_us.gif)](https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b)
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_02() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_02.out
      cat <<EOF >$TESTSRC
|license agpl|_

TEST_TRAVIS II
==============


EOF
      cat <<EOF >$TESTRES
|build status|_
|license agpl|_
|coverage status|_
|codecov status|_
|oca project|_
|technical doc|_
|help zeroincombenze|_
|try it|_


[![en](http://www.shs-av.com/wp-content/en_US.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS II
==============


.. [//]: # (copyright)

----

**Odoo** is a trademark of  \`Odoo S.A.
<https://www.odoo.com/>\`_.
(formerly OpenERP, formerly TinyERP)

**OCA**, or the  \`Odoo Community Association
<http://odoo-community.org/>\`_.
is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

**zeroincombenze®** is a trademark of \`SHS-AV s.r.l.
<http://www.shs-av.com/>\`_.
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.
[Zeroincombenze® distribution](http://wiki.zeroincombenze.org/en/Odoo)
is mainly designed for Italian law and markeplace.
Everytime, every Odoo DB and customized code can be deployed on local server too.


.. [//]: # (end copyright)

.. [//]: # (addons)


.. [//]: # (end addons)

.. |build status| image:: https://travis-ci.org/zeroincombenze/tools.svg?branch=master
.. _build status: https://travis-ci.org/zeroincombenze/tools
.. |license agpl| image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.. _license agpl: http://www.gnu.org/licenses/agpl-3.0.html
.. |coverage status| image:: https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master
.. _coverage status: https://coveralls.io/github/zeroincombenze/tools?branch=master
.. |codecov status| image:: https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg
.. _codecov status: https://codecov.io/gh/zeroincombenze/tools/branch/master
.. |oca project| image::
.. _oca project:
.. |technical doc| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-master.svg
.. _technical doc: http://wiki.zeroincombenze.org/en/Odoo/master/dev
.. |help zeroincombenze| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-master.svg
.. _help zeroincombenze: http://wiki.zeroincombenze.org/en/Odoo/master/man/
.. |try it| image::
.. _try it:
.. image:: https://www.shs-av.com/wp-content/chat_with_us.gif
   :target: https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_03() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_03.out
      cat <<EOF >$TESTSRC
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools/)
TEST_TRAVIS III
===============

[//]: # (copyright)

----

Test style Copyright
[//]: # (end copyright)

[![chat with us](http://www.shs-av.com/wp-content/chat_with_us.png)](https://www.zeroincombenze.it/chi-siamo/contatti/)
EOF
      cat <<EOF >$TESTRES
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master)](https://coveralls.io/github/zeroincombenze/tools?branch=master)
[![codecov](https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/tools/branch/master)
[![OCA_project](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-oca-master.svg)](https://github.com/OCA/tools/tree/master)
[![Tech Doc](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/dev)
[![Help](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/man/)
[![try it](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-try-it-master.svg)](http://erpmaster.zeroincombenze.it)


[![en](http://www.shs-av.com/wp-content/en_US.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS III
===============

[//]: # (copyright)

----

**Odoo** is a trademark of [Odoo S.A.](https://www.odoo.com/) (formerly OpenERP, formerly TinyERP)

**OCA**, or the [Odoo Community Association](http://odoo-community.org/), is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

**zeroincombenze®** is a trademark of [SHS-AV s.r.l.](http://www.shs-av.com/)
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.
[Zeroincombenze® distribution](http://wiki.zeroincombenze.org/en/Odoo)
is mainly designed for Italian law and markeplace.
Everytime, every Odoo DB and customized code can be deployed on local server too.

[//]: # (end copyright)

[//]: # (addons)

[//]: # (end addons)

[![chat with us](https://www.shs-av.com/wp-content/chat_with_us.gif)](https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b)
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_04() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_04.out
      cat <<EOF >$TESTSRC
|build status|_
|license agpl|_

TEST_TRAVIS IV
==============

.. |build status| image:: https://travis-ci.org/zeroincombenze/tools.svg?branch=master
.. _build status: https://travis-ci.org/zeroincombenze/tools
.. |license agpl| image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.. _license agpl: http://www.gnu.org/licenses/agpl-3.0.html
.. image::  http://www.shs-av.com/wp-content/chat_with_us.png
   :alt: Join the chat at https://www.zeroincombenze.it/chi-siamo/contatti/
   :target:  https://www.zeroincombenze.it/chi-siamo/contatti/
EOF
      cat <<EOF >$TESTRES
|build status|_
|license agpl|_
|coverage status|_
|codecov status|_
|oca project|_
|technical doc|_
|help zeroincombenze|_
|try it|_


[![en](http://www.shs-av.com/wp-content/en_US.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS IV
==============

.. [//]: # (copyright)

----

**Odoo** is a trademark of  \`Odoo S.A.
<https://www.odoo.com/>\`_.
(formerly OpenERP, formerly TinyERP)

**OCA**, or the  \`Odoo Community Association
<http://odoo-community.org/>\`_.
is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

**zeroincombenze®** is a trademark of \`SHS-AV s.r.l.
<http://www.shs-av.com/>\`_.
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.
[Zeroincombenze® distribution](http://wiki.zeroincombenze.org/en/Odoo)
is mainly designed for Italian law and markeplace.
Everytime, every Odoo DB and customized code can be deployed on local server too.


.. [//]: # (end copyright)

.. [//]: # (addons)


.. [//]: # (end addons)

.. |build status| image:: https://travis-ci.org/zeroincombenze/tools.svg?branch=master
.. _build status: https://travis-ci.org/zeroincombenze/tools
.. |license agpl| image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.. _license agpl: http://www.gnu.org/licenses/agpl-3.0.html
.. |coverage status| image:: https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master
.. _coverage status: https://coveralls.io/github/zeroincombenze/tools?branch=master
.. |codecov status| image:: https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg
.. _codecov status: https://codecov.io/gh/zeroincombenze/tools/branch/master
.. |oca project| image::
.. _oca project:
.. |technical doc| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-master.svg
.. _technical doc: http://wiki.zeroincombenze.org/en/Odoo/master/dev
.. |help zeroincombenze| image:: http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-master.svg
.. _help zeroincombenze: http://wiki.zeroincombenze.org/en/Odoo/master/man/
.. |try it| image::
.. _try it:
.. image:: https://www.shs-av.com/wp-content/chat_with_us.gif
   :target: https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_05() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_05.out
      cat <<EOF >$TESTSRC
[![Build Status](https://travis-ci.org/OCA/tools.svg?branch=master)](https://travis-ci.org/OCA/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/OCA/tools/badge.svg?branch=master)](https://coveralls.io/github/OCA/tools?branch=master)
[![codecov](https://codecov.io/gh/OCA/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/OCA/tools/branch/master)
[![Tech Doc](http://www.odoo.com/button/button-docs-travis_emulator.svg)](http://www.odoo.com/documentation/travis_emulator)
[![Help](https://www.odoo.com/forum/button/button-help-travis_emulator.svg)](https://www.odoo.com/forum/travis_emulator/help)


[![en](http://www.shs-av.com/wp-content/en_US.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS V
=============

[//]: # (addons)
Invalid text
Should be deleted
[//]: # (end addons)


[![it](http://www.shs-av.com/wp-content/it_IT.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS V
=============
Differenze rispetto localizzazione ufficiale Odoo/OCA

Descrizione | Odoo Italia | OCA
--- | --- | ---
Coverage | [![codecov](https://codecov.io/gh/zeroincombenze/l10n-italy/branch/7.0/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/l10n-italy/branch/7.0) | [![codecov](https://codecov.io/gh/OCA/l10n-italy/branch/7.0/graph/badge.svg)](https://codecov.io/gh/OCA/l10n-italy/branch/7.0)
Test con repository OCA e Odoo | Boh! | Boh!

[//]: # (copyright)

----

Test style Copyright
[//]: # (end copyright)

[![chat with us](http://www.shs-av.com/wp-content/chat_with_us.png)](https://www.zeroincombenze.it/chi-siamo/contatti/)
EOF
      cat <<EOF >$TESTRES
[![Build Status](https://travis-ci.org/zeroincombenze/tools.svg?branch=master)](https://travis-ci.org/zeroincombenze/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/zeroincombenze/tools/badge.svg?branch=master)](https://coveralls.io/github/zeroincombenze/tools?branch=master)
[![codecov](https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/tools/branch/master)
[![OCA_project](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-oca-master.svg)](https://github.com/OCA/tools/tree/master)
[![Tech Doc](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/dev)
[![Help](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/man/)
[![try it](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-try-it-master.svg)](http://erpmaster.zeroincombenze.it)


[![en](https://github.com/zeroincombenze/grymb/blob/master/flags/en_US.png)](https://www.facebook.com/groups/openerp.italia/)

TEST_TRAVIS V
=============

[//]: # (addons)

[//]: # (end addons)


[![it](https://github.com/zeroincombenze/grymb/blob/master/flags/it_IT.png)](https://www.facebook.com/groups/openerp.italia/)

TEST_TRAVIS V
=============
Differenze rispetto localizzazione ufficiale Odoo/OCA

Descrizione | Odoo Italia | OCA
--- | --- | ---
Coverage |  [![codecov](https://codecov.io/gh/zeroincombenze/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/tools/branch/master) | [![codecov](https://codecov.io/gh/OCA/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/OCA/tools/branch/master)
Test compatibilità OCA e Odoo | :white_check_mark: | :white_check_mark:

[//]: # (copyright)

----

**Odoo** is a trademark of [Odoo S.A.](https://www.odoo.com/) (formerly OpenERP, formerly TinyERP)

**OCA**, or the [Odoo Community Association](http://odoo-community.org/), is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

**zeroincombenze®** is a trademark of [SHS-AV s.r.l.](http://www.shs-av.com/)
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.
[Zeroincombenze® distribution](http://wiki.zeroincombenze.org/en/Odoo)
is mainly designed for Italian law and markeplace.
Everytime, every Odoo DB and customized code can be deployed on local server too.

[//]: # (end copyright)

[![chat with us](https://www.shs-av.com/wp-content/chat_with_us.gif)](https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b)
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}

test_06() {
    local TESTOUT TESTRES TESTFN
    TESTFN=README
    TESTSRC=$TESTDIR/res/$TESTFN
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/$TESTFN.tmp
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTDIR/res/*_06.out
      mv $TESTDIR/res/__openerp__.py $TESTDIR
      cat <<EOF >$TESTSRC
[![Build Status](https://travis-ci.org/OCA/tools.svg?branch=master)](https://travis-ci.org/OCA/tools)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/OCA/tools/badge.svg?branch=master)](https://coveralls.io/github/OCA/tools?branch=master)
[![codecov](https://codecov.io/gh/OCA/tools/branch/master/graph/badge.svg)](https://codecov.io/gh/OCA/tools/branch/master)
[![Tech Doc](http://www.odoo.com/button/button-docs-travis_emulator.svg)](http://www.odoo.com/documentation/travis_emulator)
[![Help](https://www.odoo.com/forum/button/button-help-travis_emulator.svg)](https://www.odoo.com/forum/travis_emulator/help)


[![en](http://www.shs-av.com/wp-content/en_US.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

[![icon](static/src/img/icon.png)](https://travis-ci.org/zeroincombenze)

TEST_TRAVIS VI
==============

[//]: # (addons)
Invalid text
Should be deleted
[//]: # (end addons)


[![it](http://www.shs-av.com/wp-content/it_IT.png)](http://wiki.zeroincombenze.org/it/Odoo/7.0/man)

TEST_TRAVIS VI
==============

Differenze rispetto localizzazione ufficiale Odoo/OCA

Descrizione | Odoo Italia | OCA
--- | --- | ---
Coverage | [![codecov](https://codecov.io/gh/zeroincombenze/l10n-italy/branch/7.0/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/l10n-italy/branch/7.0) | [![codecov](https://codecov.io/gh/OCA/l10n-italy/branch/7.0/graph/badge.svg)](https://codecov.io/gh/OCA/l10n-italy/branch/7.0)
Test con repository OCA e Odoo | Boh! | Boh!

Installation
------------

* pip install zerobug

Usage
-----

For furthermore information, please visit http://wiki.zeroincombenze.org/it/Odoo

Credits
-------

### Contributors

* Antonio Maria Vigliotti <antoniomaria.vigliotti@gmail.com>

### Funders

This module has been financially supported by

* SHS-AV s.r.l. <https://www.zeroincombenze.it/>

### Maintainer

[//]: # (copyright)

----

Test style Copyright
[//]: # (end copyright)

[![chat with us](http://www.shs-av.com/wp-content/chat_with_us.png)](https://www.zeroincombenze.it/chi-siamo/contatti/)
EOF
      cat <<EOF >$TESTRES
[![Build Status](https://travis-ci.org/zeroincombenze/res.svg?branch=master)](https://travis-ci.org/zeroincombenze/res)
[![license agpl](https://img.shields.io/badge/licence-AGPL--3-blue.svg)](http://www.gnu.org/licenses/agpl-3.0.html)
[![Coverage Status](https://coveralls.io/repos/github/zeroincombenze/res/badge.svg?branch=master)](https://coveralls.io/github/zeroincombenze/res?branch=master)
[![codecov](https://codecov.io/gh/zeroincombenze/res/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/res/branch/master)
[![OCA_project](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-oca-master.svg)](https://github.com/OCA/res/tree/master)
[![Tech Doc](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-docs-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/dev)
[![Help](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-help-master.svg)](http://wiki.zeroincombenze.org/en/Odoo/master/man/)
[![try it](http://www.zeroincombenze.it/wp-content/uploads/ci-ct/prd/button-try-it-master.svg)](http://erpmaster.zeroincombenze.it)


[![en](https://github.com/zeroincombenze/grymb/blob/master/flags/en_US.png)](https://www.facebook.com/groups/openerp.italia/)

[![icon](static/src/img/icon.png)](https://travis-ci.org/zeroincombenze)

TEST_TRAVIS VI
==============

[//]: # (addons)

[//]: # (end addons)


[![it](https://github.com/zeroincombenze/grymb/blob/master/flags/it_IT.png)](https://www.facebook.com/groups/openerp.italia/)

TEST_TRAVIS VI
==============

Differenze rispetto localizzazione ufficiale Odoo/OCA

Descrizione | Odoo Italia | OCA
--- | --- | ---
Coverage |  [![codecov](https://codecov.io/gh/zeroincombenze/res/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroincombenze/res/branch/master) | [![codecov](https://codecov.io/gh/OCA/res/branch/master/graph/badge.svg)](https://codecov.io/gh/OCA/res/branch/master)
Test compatibilità OCA e Odoo | :white_check_mark: | :white_check_mark:

Installation
------------

* pip install zerobug

Configuration
-------------

Usage
-----

For furthermore information, please visit http://wiki.zeroincombenze.org/it/Odoo

Known issues / Roadmap
----------------------

Bug Tracker
-----------

Credits
-------

### Contributors

* Antonio Maria Vigliotti <antoniomaria.vigliotti@gmail.com>

### Funders

This module has been financially supported by

* SHS-AV s.r.l. <https://www.zeroincombenze.it/>

### Maintainer

[//]: # (copyright)

----

**Odoo** is a trademark of [Odoo S.A.](https://www.odoo.com/) (formerly OpenERP, formerly TinyERP)

**OCA**, or the [Odoo Community Association](http://odoo-community.org/), is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

**zeroincombenze®** is a trademark of [SHS-AV s.r.l.](http://www.shs-av.com/)
which distributes and promotes **Odoo** ready-to-use on its own cloud infrastructure.
[Zeroincombenze® distribution](http://wiki.zeroincombenze.org/en/Odoo)
is mainly designed for Italian law and markeplace.
Everytime, every Odoo DB and customized code can be deployed on local server too.

[//]: # (end copyright)

[![chat with us](https://www.shs-av.com/wp-content/chat_with_us.gif)](https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b)
EOF
      $RUNDIR/please -qt distribution . zero
    fi
    test_result "please distribution" "$TESTOUT" "$TESTRES" "diff"
}


Z0BUG_setup() {
    touch $TESTDIR/res/__openerp__.py
}

Z0BUG_teardown() {
    rm -f $TESTDIR/__openerp__.py
}


Z0BUG_init
parseoptest -l$TESTDIR/test_travis_em.log "$@" "-J"
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
if [ $opt_tjLib -ne 0 ]; then
  TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
  if [ -z "$TRAVISLIBDIR" ]; then
    echo "Library file travisrc not found!"
    exit 2
  fi
  . $TRAVISLIBDIR
fi

UT1_LIST=""
UT_LIST=""
if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
exit $sts
