#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on travis emulator
#
READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
export READLINK
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
for d in $PYPATH /etc; do
  if [[ -e $d/z0librc ]]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [[ -z "$Z0LIBDIR" ]]; then
  echo "Library file z0librc not found!"
  exit 72
fi
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
RUNDIR=$(readlink -e $TESTDIR/..)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
RED="\e[1;31m"
GREEN="\e[1;32m"
CLR="\e[0m"
Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
if [[ -z "$Z0TLIBDIR" ]]; then
  echo "Library file z0testrc not found!"
  exit 72
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"

__version__=1.0.9


Z0BUG_setup() {
    if [[ -d /home/odoo ]]; then
        LCL_ROOT=/home/odoo
    else
        LCL_ROOT=/opt/odoo
    fi
    LCLTEST_RMDIR=
    for VERSION in v7 7.0 8.0 9.0 10.0 11.0; do
      if [ ! -d ~/$VERSION ]; then
        LCLTEST_RMDIR="$LCLTEST_RMDIR $VERSION"
        mkdir -p ~/$VERSION
        mkdir -p ~/$VERSION/l10n-italy
        mkdir -p ~/$VERSION/l10n-italy/l10n_it_vat_registries
        mkdir -p ~/$VERSION/l10n-italy/l10n_it_vat_registries/i18n
        touch ~/$VERSION/l10n-italy/l10n_it_vat_registries/__openerp__.py
      fi
    done
}

Z0BUG_teardown() {
    for VERSION in v7 7.0 8.0 9.0 10.0; do
      if [[ "$LCLTEST_RMDIR" =~ $VERSION ]]; then
        rm -fR ~/$VERSION/l10n-italy/l10n_it_vat_registries/i18n
        rm -fR ~/$VERSION/l10n-italy/l10n_it_vat_registries
        rm -fR ~/$VERSION/l10n-italy
        rm -fR ~/$VERSION
      fi
    done
}

test_diff() {
    export opt_conf=$TESTDIR/test_travis.conf
    local cmd="$RUNDIR/vfdiff -c$opt_conf -nv $1 $2"
    if [ -n "$1" ]; then
      local msg1=$1
    else
      local msg1=
    fi
    if [ -n "$2" ]; then
      local msg2=$2
    else
      local msg2=.
    fi
    if [ -n "$3" ]; then
      cmd="$cmd -r $3"
      msg1=$msg1/$3
    fi
    if [ -n "$4" ]; then
      cmd="$cmd -p $4"
      msg1=$msg1/$4
    fi
    if [ -n "$5" ]; then
      if [ "${5:0:1}" == "-" ]; then
        cmd="$cmd $5"
        # if [ -n "${5:1}" ]; then
        #   cmd="$cmd -O ${5:1}"
        # fi
      else
        cmd="$cmd -O $5"
      fi
    fi
    TRES=$(eval $cmd)
    test_result "diff $msg1 $msg2" "$TRES" "$6"
}

test_01() {
    local s t
    export opt_conf=$TESTDIR/test_travis.conf
    if [ -f $opt_conf ]; then rm -f $opt_conf; fi
    touch $opt_conf
    echo "filedel=.pyc .log .bak  ~">>$opt_conf
    echo "fileignore=.conf">>$opt_conf
    echo "filediffignore=.po .pot">>$opt_conf
    for s in v7 8.0 10.0; do
      if [ -d $HOME/$s ]; then
        for t in v7 7.0 9.0; do
          if [ -d $HOME/$t ]; then
            test_diff "$s" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/$s $HOME/$t"
            # TODO: Test does not work in travis env
            if [ "${PWD:0:18}" == "$HOME/dev/pypi" ]; then
              test_diff "~/$s" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/$s $HOME/$t"
            fi
            test_diff "$HOME/$s" "$t" "l10n-italy" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/$s/l10n-italy $HOME/$t/l10n-italy"
            test_diff "$HOME/$s" "$t" "l10n-italy" "l10n_it_vat_registries" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/$s/l10n-italy/l10n_it_vat_registries $HOME/$t/l10n-italy/l10n_it_vat_registries"
            test_diff "$HOME/$s/l10n-italy" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/$s/l10n-italy $HOME/$t/l10n-italy"
            test_diff "$HOME/$s/l10n-italy/l10n_it_vat_registries" "$t" "" "" "" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/$s/l10n-italy/l10n_it_vat_registries $HOME/$t/l10n-italy/l10n_it_vat_registries"
            test_diff "$HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "$t" "" "" "" "> diff -ZBy $HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py $HOME/$t/l10n-italy/l10n_it_vat_registries/__openerp__.py"
            test_diff "$HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "" "" "" "$t" "> diff -ZBy $HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py $HOME/$t/l10n-italy/l10n_it_vat_registries/__openerp__.py"
            test_diff "$HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "" "" "" "-O$t" "> diff -ZBy $HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py $HOME/$t/l10n-italy/l10n_it_vat_registries/__openerp__.py"
          fi
        done
      fi
    done
    for s in v7 10.0; do
      if [ -d $HOME/$s ]; then
        test_diff "$HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py" "8.0" "l10n-italy-supplemental" "" "" "> diff -ZBy $HOME/$s/l10n-italy/l10n_it_vat_registries/__openerp__.py $HOME/8.0/l10n-italy-supplemental/l10n_it_vat_registries/__openerp__.py"
      fi
    done
    for s in 7 8; do
      if [ -d $HOME/$s.0 ]; then
        test_diff "/etc/odoo/odoo$s-server.conf" "9.0" "" "" "" "> diff -ZBy /etc/odoo/odoo$s-server.conf /etc/odoo/odoo9-server.conf"
      fi
    done
    test_diff "$HOME/7.0/l10n-italy/l10n_it_vat_registries/i18n/" "8.0" "" "" "-m" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr -I '^#' -I \"^ *[_\\\"']\?_\?version[_\\\"']\?_\? *[:=]\" $HOME/7.0/l10n-italy/l10n_it_vat_registries/i18n $HOME/8.0/l10n-italy/l10n_it_vat_registries/i18n"
    test_diff "$HOME/7.0/l10n-italy/l10n_it_vat_registries/i18n" "8.0" "" "" "-e" "> diff -x '*.pyc' -x '*.log' -x '*.bak' -x '*~' -x '*.conf' -x '*.po' -x '*.pot' -ZBqr $HOME/7.0/l10n-italy/l10n_it_vat_registries/i18n $HOME/8.0/l10n-italy/l10n_it_vat_registries/i18n"
    local CWD=$PWD
    cd $HOME/7.0/l10n-italy/l10n_it_vat_registries
    test_diff "__openerp__.py" "" "" "" "8" "> diff -ZBy $HOME/7.0/l10n-italy/l10n_it_vat_registries/__openerp__.py $HOME/8.0/l10n-italy/l10n_it_vat_registries/__openerp__.py"
    cd $CWD
}


Z0BUG_init
parseoptest -l$TESTDIR/test_wok_code.log "$@"
sts=$?
[[ $sts -ne 127 ]] && exit $sts



UT1_LIST=
UT_LIST=
[[ "$(type -t Z0BUG_setup)" == "function" ]] && Z0BUG_setup
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
[[ "$(type -t Z0BUG_teardown)" == "function" ]] && Z0BUG_teardown
exit $sts
