include_odoo_python_new_api:
  ctx: 'final'
  include: 'odoo_python_new_api'
include_odoo_api_multi:
  ctx: 'final'
  include: 'odoo_python_api_multi'
import_oerplib:
  match: '^ *import oerplib(?!\w)'
  prio: '9'
  do:
    - action: 's'
      args:
      - import oerplib
      - import oerplib3 as oerplib
oerplib3:
  match: '.*["'']oerplib["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - oerplib
      - oerplib3
ir_model_sudo:
  search: 'self\.env\[["'']ir\.config_parameter["'']'
  prio: '9'
  do:
    - action: 's'
      args:
        - 'self\.env\[["''](ir\.config_parameter)["'']'
        - 'self.env["ir.config_parameter"].sudo()'
