no_api_multi:
  match: '^ *@api\.multi'
  do:
    - action: 's'
      args:
      - '@api\.multi'
      - '# @api.multi'
no_api_mix:
  match: '^ *@api\.(one|returns|cr|model_cr|model_cr_context|v8|noguess)'
  do:
    - action: 's'
      args:
      - '@api\.(one|returns|cr|model_cr|model_cr_context|v8|noguess)'
      - '# @api.\1'
    - action: 'a'
      args:
      - '%(indent)s# TODO> Update code to multi or add self.ensure_one()'
