# This configuration is loaded when source file is a HISTORY/CHANGELOG file
# and product is Odoo
#
version:
#  match: '.*[0-9]+\(?:\\.[0-9]+\)+'
  match: '[0-9][0-9.]+ \([0-9]{4}-[0-9]{2}-[0-9]{2}\)'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_version