version:
  match: "^ *[\"']version[\"']*: [\"'][0-9.]+[\"']"
  prio: '9'
  do:
    - action: '$'
      args:
      - match_version
version_depends:
  match: "^ *[\"']version_depends[\"']*: .*[\"'].*[0-9.]+[\"']"
  prio: '9'
  do:
    - action: '$'
      args:
      - match_version
