# This configuration is always used to apply an action on searched files
# when product is Odoo and Odoo version is 10.0
#
manifest:
  match: '.*/__openerp__.py'
  ctx: 'final or migrate_multi'
  prio: '0'
  do:
    - action: 'mv'
      args:
      - '__openerp__.py'
      - '__manifest__.py'
