no_view_type:
  match: '^ *<field name="view_type">form</field>'
  do:
    - action: 'd'
binding_model:
  match: '.*src_model="([^"]*)"'
  do:
    - action: 's'
      args:
      - 'src_model="([^"]*)"'
      - 'binding_model="\1"'
