openerp_import:
  match: '^from openerp\.osv import'
  prio: '3'
  do:
    - action: 's'
      args:
      - 'from openerp\.osv import'
      - 'from openerp import'
    - action: 's'
      args:
      - '(osv|orm)'
      - 'models'
except_usererror:
  match: 'from openerp\.osv\.(osv|orm) import except_(osv|orm)'
  prio: '3'
  do:
    - action: 's'
      args:
      - 'from openerp\.osv\.(osv|orm) import except_(osv|orm)'
      - 'from openerp.exceptions import UserError'
raise_user_error:
  match: '^.*raise *[a-z_.]*except_(osv|orm)\('
  do:
    - action: 's'
      args:
      - 'raise *[a-z_.]*except_(osv|orm)\('
      - 'raise UserError('
    - action: 's'
      args:
      - "(\\([\"'][^\"']*[\"'], *)(.*)"
      - '(\2'
class_model:
  match: '^ *class [^(]+\([^)]*\)'
  do:
    - action: 's'
      args:
      - '(osv|orm).Model'
      - 'models.Model'
    - action: 's'
      args:
      - 'osv.osv_memory'
      - 'models.TransientModel'
def_cr_uid:
  match: '^ *def [^(]+\(self, *cr, *uid, [^)]*\)'
  do:
    - action: 's'
      args:
      - '\(self, *cr, *uid,'
      -  '(self,'
    - action: 's'
      args:
      - ', *context=[^)]+'
      - ''
from_openerp:
  match: '^from odoo'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'odoo'
      - 'openerp'
sort_from_odoo_import:
  match: '^from (odoo|openerp) import [\w, ]+'
  prio: '9'
  do:
    - action: '$'
      args:
      - sort_from_odoo_import
