#! /bin/bash
# -*- coding: utf-8 -*-
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -e ./z0librc ]; then
. ./z0librc
elif [ -e ../z0librc ]; then
. ../z0librc
elif [ -e ~/z0librc ]; then
. ~/z0librc
else
. /etc/z0librc
fi

__version__="1.4.25.3"

# set -x
publog="/var/log/restwww.log"
set_tlog_file "$publog"
opt_quiet=1
wlog "****** $THIS $__version__ ******"
# Creare file list
dblist=""
excl=""
hdp="/var/www"
bd="$hdp/backups/*.bz2"
flst="$HOME/tmp_www.lst"
dir -1 $bd>$flst
sts=$?
if [ $sts -gt 0 ]; then
  wlog "???????????????"
  wlog "No Files found!"
  exit 1
fi
cd $hdp/backups
exec 3< $flst
#
while read -u 3 -r db
do
  fqn=$db
  if [ -e $fqn ]; then
    db=`echo "$db"|awk -F"/"  '{print $5}'`
    l=$((${#db}-4))
    db=${db:0:l}/

    # if [ "$db" != "wp-zi.it/" ]; then
      uu=`echo "$db"|awk -F"/"  '{print $1}'`
      if [ "$uu" == "mw" -o "$uu" == "wp-zi" ]; then
        uu="apache"
      elif [ "${uu:0:5}" == "eu-zi" -o  "${uu:0:5}" == "wp-zi" ]; then
        uu=`echo "$uu"|awk -F"."  '{print $2}'`
        uu="zeroincombenze.$uu"
      elif [ "${uu:0:4}" == "odoo" -o "${uu:0:3}" == "zi." -o "${uu:0:3}" == "mw-" ]; then
        uu="zeroincombenze.org"
      elif [ "${uu:0:3}" == "wp-" -o  "${uu:0:3}" == "mg-" ]; then
        uu=${uu:3}
      elif [ "${uu:0:3}" == "aaa" ]
      then
        uu="apache"
      fi
      uu=$(echo "$uu"|tr -d "~")
      if [ -e $hdp/html/$db ]
      then
        CWD=$PWD
        wlog "\$ cd $hdp/html"
        cd $hdp/html
        fn=$(basename $fqn)
        wlog "Update tree $db"
        if [ -e $hdp/html/__old_$db ]
        then
          wlog "\$ rm -fR $hdp/html/__old_$db"
          rm -fR $hdp/html/__old_$db
        fi
        wlog "\$ tar -cjf $fn $db"
        tar -cjf $fn $db
        wlog "\$ chown $uu:apache $fn"
        chown -R $uu:apache $fn
        wlog "\$ rm -fR $hdp/html/$db"
        rm -fR $hdp/html/$db
        wlog "\$ mkdir -p $hdp/html/$db"
        mkdir -p $hdp/html/$db
        wlog "\$ cd $CWD"
        cd $CWD
      else
        wlog "\$ mkdir $hdp/html/$db"
        mkdir $hdp/html/$db
        wlog "New website $db found"
      fi

      wlog "\$ tar --overwrite -xjf $fqn -C $hdp/html/"
      tar --overwrite -xjf $fqn -C $hdp/html/
      # wlog "\$ rm -f $fqn"
      # rm -f $fqn

      if [ "${HOSTNAME:0:6}" == "shsdev" ]; then
      if [ "$db" == "mw-zi.org/" ]
      then
        wlog "Change local data for wiki site .."
        wlog "\$ mv $hdp/html/${db}lang-it/LocalSettings.php $hdp/html/${db}lang-it/__old_LocalSettings.php"
        mv $hdp/html/${db}lang-it/LocalSettings.php $hdp/html/${db}lang-it/__old_LocalSettings.php
        wlog "\$ cat $hdp/html/${db}lang-it/__old_LocalSettings.php|sed 's/http:\/\/wiki.zeroincombenze.org/http:\/\/wiki1.zeroincombenze.org/g .."
        cat $hdp/html/${db}lang-it/__old_LocalSettings.php|\
sed 's/http:\/\/wiki.zeroincombenze.org/http:\/\/wiki1.zeroincombenze.org/g'>$hdp/html/${db}lang-it/LocalSettings.php
        wlog "\$ mv $hdp/html/${db}lang-en/LocalSettings.php $hdp/html/${db}lang-en/__old_LocalSettings.php"
        mv $hdp/html/${db}lang-en/LocalSettings.php $hdp/html/${db}lang-en/__old_LocalSettings.php
        wlog "\$ cat $hdp/html/${db}lang-en/__old_LocalSettings.php|sed 's/http:\/\/wiki.zeroincombenze.org/http:\/\/wiki1.zeroincombenze.org/g .."
        cat $hdp/html/${db}lang-en/__old_LocalSettings.php|\
sed 's/http:\/\/wiki.zeroincombenze.org/http:\/\/wiki1.zeroincombenze.org/g'>$hdp/html/${db}lang-en/LocalSettings.php
        wlog "\$ mv $hdp/html/${db}index.html $hdp/html/${db}__old_index.html"
        mv $hdp/html/${db}index.html $hdp/html/${db}__old_index.html
        wlog "\$ cat $hdp/html/${db}__old_index.html|sed 's/http:\/\/wiki.zeroincombenze.org/http:\/\/wiki1.zeroincombenze.org/g .."
        cat $hdp/html/${db}__old_index.html|\
sed 's/http:\/\/wiki.zeroincombenze.org/http:\/\/wiki1.zeroincombenze.org/g'>$hdp/html/${db}index.html
        wlog "Recording robots.txt"
        echo "User-agent: *">$hdp/html/${db}robots.txt
        echo "Disallow: /wiki/">>$hdp/html/${db}robots.txt
      elif [ "$db" == "mw-zi.eu/" ]
      then
        wlog "Change local data for wiki site .."
        wlog "\$ mv $hdp/html/${db}mw/LocalSettings.php $hdp/html/${db}mw/__old_LocalSettings.php"
        mv $hdp/html/${db}mw/LocalSettings.php $hdp/html/${db}mw/__old_LocalSettings.php
        wlog "\$ cat $hdp/html/${db}mw/__old_LocalSettings.php|sed 's/http:\/\/www.zeroincombenze.eu/http:\/\/www1.zeroincombenze.eu/g .."
        cat $hdp/html/${db}mw/__old_LocalSettings.php|\
sed 's/http:\/\/www.zeroincombenze.eu/http:\/\/www1.zeroincombenze.eu/g'>$hdp/html/${db}mw/LocalSettings.php
        wlog "\$ cat $hdp/html/${db}__old_index.html|sed 's/http:\/\/www.zeroincombenze.eu/http:\/\/www1.zeroincombenze.eu/g .."
        wlog "\$ mv $hdp/html/${db}index.html $hdp/html/${db}__old_index.html"
        mv $hdp/html/${db}index.html $hdp/html/${db}__old_index.html
        cat $hdp/html/${db}__old_index.html|\
sed 's/http:\/\/www.zeroincombenze.eu/http:\/\/www1.zeroincombenze.eu/g'>$hdp/html/${db}index.html
        wlog "Recording robots.txt"
        echo "User-agent: *">$hdp/html/${db}robots.txt
        echo "Disallow: /wiki/">>$hdp/html/${db}robots.txt
      fi
      fi

    wlog "\$ chown -R $uu:apache $hdp/html/$db"
    chown -R $uu:apache $hdp/html/$db
    if [ "$uu" != "apache" ]; then
      wlog "\$ setfacl -R -m u:apache:rwx $hdp/html/$db"
      setfacl -R -m u:apache:rwx $hdp/html/$db
      setfacl -R -m d:u:apache:rwx $hdp/html/$db
      chown $uu:apache $fqn
    else
      for usx in it biz com eu org; do
        wlog "\$ setfacl -R -m u:zeroincombenze.$usx:rwx $hdp/html/$db"
        setfacl -R -m u:zeroincombenze.$usx:rwx $hdp/html/$db
        setfacl -R -m d:u:zeroincombenze.$usx:rwx $hdp/html/$db
      done
      chown $uu:apache $fqn
    fi
    wlog "\$ chmod -R u+rxw,g+rwx,o-rwx $hdp/html/$db"
    chmod -R u+rxw,g+rwx,o-rwx $hdp/html/$db
    if [ "$db" == "alfaschool.ru/" ]; then
      wlog "\$ chmod -R o+rwx $hdp/html/${db}wp-content/uploads/wp-google-maps/"
      chmod -R o+rwx $hdp/html/${db}wp-content/uploads/wp-google-maps/
    fi
  fi
done
exec 3<&-
cd

bd=$hdp/backups
htmd=$hdp/html
./av_php -sp $htmd
sts=$?
if [ $sts -gt 0 ]; then
  wlog "?????????????????????????????"
  wlog "Virus found in restored dirs!"
  wlog "?????????????????????????????"
  exit 1
fi
wlog "All www dirs are restored!"
exit 0
