#! /bin/bash
# -*- coding: utf-8 -*-
#
# Purge backupped postgres DB
#
# This free software is released under GNU Affero GPL3
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi

__version__="1.3.13.3"


detached_login() {
# detached_login([path] [path2] [path3])
    if [ $opt_cron -gt 0 -a "$SHELL" == "/bin/sh" ]; then
      if [ $opt_dry_run -eq 0 ]; then
        fqcmd=$(readlink -f $0)
        wlog "Run $fqcmd in cron mode"
        SHELL=/bin/bash exec "$fqcmd" "$@"
      fi
    elif [ $opt_cron -gt 0 -a -f $HOME/.bash_profile ]; then
      wlog "Simulate login ($HOME/.bash_profile)"
      . $HOME/.bash_profile
    fi
    if [[ ":$PATH:" =~ /usr/local/bin ]]; then
      :
    else
      export PATH=/usr/local/bin:$PATH
    fi
    if [ -n "$1" ]; then
      if [ -d $1 ]; then
        if [[ ":$PATH:" =~ $1 ]]; then
          :
        else
          export PATH=$PATH:$1
        fi
      fi
    fi
    if [ -n "$2" ]; then
      if [ -d $2 ]; then
        if [[ ":$PATH:" =~ $2 ]]; then
          :
        else
          export PATH=$PATH:$2
        fi
      fi
    fi
    if [ -n "$3" ]; then
      if [ -d $3 ]; then
        if [[ ":$PATH:" =~ $3 ]]; then
          :
        else
          export PATH=$PATH:$3
        fi
      fi
    fi
    wlog "PATH=$PATH"
}

OPTOPTS=(h        K        k          l       m        n           U          V           v)
OPTDEST=(opt_help opt_cron opt_keep   opt_log opt_km   opt_dry_run opt_user   opt_version opt_verbose)
OPTACTI=(1        1        "="        "="     "="      "1"         "="        "*>"        1)
OPTDEFL=(0        0        ""         ""      ""        0           "postgres" ""          0)
OPTMETA=("help"   "cron"   "# copies" "file" "# copies" "do nothing" "username" "version"   "verbose")
OPTHELP=("this help"\
 "run in cron environment"\
 "keep # recent copies of db (max 60)"\
 "log filename (def /var/log/bckdb.log)"\
 "keep # of monthly copies of db (max 12)"\
 "do nothing (dry-run)"\
 "username (def postgres)"\
 "show version"\
 "verbose mode")
OPTARGS=(dbsel)

parseoptargs $@

if [ "$opt_version" ]
then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]
then
  print_help "Purge backupped postgres DB"\
  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
if [ -z "$opt_log" ]; then
  publog="/var/log/zar/purgedb.log"
else
  publog=$opt_log
fi
FCONF=$TDIR/zar.conf
CFG_init
set_tlog_file "$publog"
if [ $opt_cron -gt 0 ]; then
  detached_login "$@"
fi
link_cfg $FCONF
wlog "Starting purge backup $__version__ by $USER"

PGDIR=$(findpkg "" "/var/lib" "postgresql  pgsql" "8.2 8.3 9.0 9.1 9.2 9.3 9.4")
DBCKDIR="$PGDIR/backups"
HOST_PRD=$(get_cfg_value 0 production_host)
HOST_DEV=$(get_cfg_value 0 development_host)
wlog "PRD=$HOST_PRD"
wlog "DEV=$HOST_DEV"
if [ -z "$dbsel" ]; then
  dbsel="$(get_cfg_value 0 dbfilter)"
fi
for sfx in A B C D; do
  if [ "$HOSTNAME" == "$HOST_PRD" ]; then
    eval DB$sfx="$(get_cfg_value 0 PRD_DB${sfx}_filter)"
    eval NC$sfx="$(get_cfg_value 0 PRD_DB${sfx}_keep_recent)"
    eval NA$sfx="$(get_cfg_value 0 PRD_DB${sfx}_keep_monthly)"
  elif [ "$HOSTNAME" == "$HOST_DEV" ]; then
    eval DB$sfx="$(get_cfg_value 0 DEV_DB${sfx}_filter)"
    eval NC$sfx="$(get_cfg_value 0 DEV_DB${sfx}_keep_recent)"
    eval NA$sfx="$(get_cfg_value 0 DEV_DB${sfx}_keep_monthly)"
  fi
  if [ -z "$DB$sfx" ]; then
    eval DB$sfx="$(get_cfg_value 0 DB${sfx}_filter)"
    eval NC$sfx="$(get_cfg_value 0 DB${sfx}_keep_recent)"
    eval NA$sfx="$(get_cfg_value 0 DB${sfx}_keep_monthly)"
  fi
done
if [ -z "$DBA" ]; then
  DBA="$dbsel"
  NCA=$(get_cfg_value 0 keep_recent)
  if [ -z "$NCA" ]; then
    NCA=30
  fi
  NAA=$(get_cfg_value 0 keep_monthly)
  if [ -z "$NAA" ]; then
    NAA=12
  fi
fi

if [[ "$opt_keep" =~ [0-9]+ ]]; then
  NCA=$opt_keep
fi
if [[ "$opt_km" =~ [0-9]+ ]]; then
  NAA=$opt_km
fi
dblist=""
if [ $opt_dry_run -gt 0 ]; then
  echo "Keep $NCA recent copies copies and $NAA monthly copies of $DBA"
  echo "Keep $NCB recent copies copies and $NAB monthly copies of $DBB"
  echo "Keep $NCC recent copies copies and $NAC monthly copies of $DBC"
  echo "Keep $NCD recent copies copies and $NAD monthly copies of $DBD"
else
  wlog "Keep $NCA recent copies copies and $NAA monthly copies of $DBA"
  wlog "Keep $NCB recent copies copies and $NAB monthly copies of $DBB"
  wlog "Keep $NCC recent copies copies and $NAC monthly copies of $DBC"
  wlog "Keep $NCD recent copies copies and $NAD monthly copies of $DBD"
fi
ctr=0
for fn in $(dir $DBCKDIR/*.sql)
do
  dbf=${fn%%-*}
  db=$(basename $dbf)
  f=0
  if [[ $db =~ $DBA ]]; then
    if [[ " $dblist " =~ [[:space:]]$db[[:space:]] ]]; then
      :
    else
      dblist="$dblist $db"
      f=1
    fi
    range=$NCA
  elif [[ $db =~ $DBB ]]; then
    if [[ " $dblist " =~ [[:space:]]$db[[:space:]] ]]; then
      :
    else
      dblist="$dblist $db"
      f=1
    fi
    range=$NCB
  elif [[ $db =~ $DBC ]]; then
    if [[ " $dblist " =~ [[:space:]]$db[[:space:]] ]]; then
      :
    else
      dblist="$dblist $db"
      f=1
    fi
    range=$NCC
  elif [[ $db =~ $DBD ]]; then
    if [[ " $dblist " =~ [[:space:]]$db[[:space:]] ]]; then
      :
    else
      dblist="$dblist $db"
      f=1
    fi
    range=$NCD
  fi
  if [ $f -gt 0 -a -n "$range" ]; then
    for i in {90..1}; do
      dtc=$(date -d "today - $i day" +%Y%m%d)
      dd=$(date -d "today - $i day" +%d)
      if [ "$dd" != "01" -a $i -gt $range ]
      then
        if [ -f "$dbf-$dtc.sql" ]; then
          if [ $opt_dry_run -gt 0 ]; then
            echo "File $dbf-$dtc.sql should be deleted!"
          else
            wlog "File $dbf-$dtc.sql deleted!"
            rm -f $dbf-$dtc.sql
            ((ctr++))
          fi
        fi
      fi
    done
  fi
done
mm=$(date -d today +%m)
mm=${mm#0}
for i in {1..12}; do
  if [ $mm -lt $i ]; then
    ((d=$mm+12-$i))
    yy=$(date -d "today - 1 year" +%Y)
  else
    ((d=$mm-$i))
    yy=$(date -d today +%Y)
  fi
  dtc=$(printf "%04d%02d%02d" $yy $i 1)
  for db in $dblist; do
    if [[ $db =~ $DBA ]]; then
      f=1
      range=$NAA
    elif [[ $db =~ $DBB ]]; then
      f=1
      range=$NAB
    elif [[ $db =~ $DBC ]]; then
      f=1
      range=$NAC
    elif [[ $db =~ $DBD ]]; then
      f=1
      range=$NAD
    fi
    if [ $f -gt 0 -a -n "$range" ]; then
      if [ $d -ge $range ]; then
        if [ -f "$DBCKDIR/${db}-$dtc.sql" ]; then
          if [ $opt_dry_run -gt 0 ]; then
            echo "File $DBCKDIR/${db}-$dtc.sql should be deleted!"
          else
            wlog "File $DBCKDIR/${db}-$dtc.sql deleted!"
            rm -f $DBCKDIR/${db}-$dtc.sql
            ((ctr++))
          fi
        fi
      fi
    fi
  done
done
wlog "All $ctr databases are purged!"
exit 0
