#! /bin/bash
# -*- coding: utf-8 -*-
# Duplicate postgres DB
#
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
# This free software is released under GNU Affero GPL3


THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x/z0librc
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)


__version__="1.3.17"


detached_login() {
# detached_login([path] [path2] [path3])
    if [ $opt_cron -gt 0 -a "$SHELL" == "/bin/sh" ]; then
      if [ $opt_dry_run -eq 0 ]; then
        fqcmd=$(readlink -f $0)
        wlog "Run $fqcmd in cron mode"
        SHELL=/bin/bash exec "$fqcmd" "$@"
      fi
    elif [ $opt_cron -gt 0 -a -f $HOME/.bash_profile ]; then
      wlog "Simulate login ($HOME/.bash_profile)"
      . $HOME/.bash_profile
    fi
    if [[ ":$PATH:" =~ /usr/local/bin ]]; then
      :
    else
      export PATH=/usr/local/bin:$PATH
    fi
    if [ -n "$1" ]; then
      if [ -d $1 ]; then
        if [[ ":$PATH:" =~ $1 ]]; then
          :
        else
          export PATH=$PATH:$1
        fi
      fi
    fi
    if [ -n "$2" ]; then
      if [ -d $2 ]; then
        if [[ ":$PATH:" =~ $2 ]]; then
          :
        else
          export PATH=$PATH:$2
        fi
      fi
    fi
    if [ -n "$3" ]; then
      if [ -d $3 ]; then
        if [[ ":$PATH:" =~ $3 ]]; then
          :
        else
          export PATH=$PATH:$3
        fi
      fi
    fi
    wlog "PATH=$PATH"
}


kill_process() {
    sql="select datname,pid,xact_start,waiting,state from pg_stat_activity where datname='$NEWDB' and pid<>pg_backend_pid();"
    flog=$HOME/dup4test_proc.log
    psql -U$opt_user -d postgres -tc "$sql" -o $flog
    while IFS=\| read db pid pdt w st; do
      if [ -n "$st" ]; then
        db=$(echo $db)
        w=$(echo $w)
        st=$(echo $st)
        pid=$(echo $pid)
        if [ "$db" == "$NEWDB" ]; then
          if [ "$w" != "f" -a "${st:0:4}" != "idle" ]; then
            echo "DB non deletable"
          else
            echo "killing process $pid"
            kill $pid
          fi
        fi
      fi
    done < $flog
    rm -f $flog
}

backup_db() {
    local db=$1
    if [ $opt_dry_run -gt 0 ]; then
      wlog "> pg_dump -U$opt_user -Fp -f $DBCKDIR/$db-00000000.sql $db"
    else
      kill_process
      wlog "\$ pg_dump -U$opt_user -Fp -f $DBCKDIR/$db-00000000.sql $db"
      pg_dump -U$opt_user -Fp -f $DBCKDIR/$db-00000000.sql $db
    fi
}

OPTOPTS=(h        K        l       m        n            U          V           v)
OPTDEST=(opt_help opt_cron opt_log opt_mail opt_dry_run  opt_user   opt_version opt_verbose)
OPTACTI=(1        1        "="     1        "1"          "="        "*>"        1)
OPTDEFL=(0        0        ""      -1        0           "postgres" ""          0)
OPTMETA=("help"   "cron"   "file" "mail"    "do nothing" "username" "version"   "verbose")
OPTHELP=("this help"\
 "run in cron environment"\
 "log filename (def /var/log/bckdb.log)"\
 "disable mail server on target DB"\
 "do nothing (dry-run)"\
 "username (def postgres)"\
 "show version"\
 "verbose mode")
OPTARGS=(olddb newdb seldate)

parseoptargs $@

if [ "$opt_version" ]
then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]
then
  print_help "Restore/duplicate postgres DB"\
  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
if [ -z "$opt_log" ]; then
  publog="/var/log/zar/restdb.log"
else
  publog=$opt_log
fi
FCONF=$TDIR/zar.conf
eval $(init_cfg)
eval $(active_cfg)
set_tlog_file "$publog"
if [ $opt_cron -gt 0 ]; then
  detached_login "$@"
fi
link_cfg $FCONF
wlog "Starting restore/duplicate $__version__ by $USER"

DBCKDIR=$(findpkg "" "/var/lib" "postgresql  pgsql" "8.2 8.3 9.0 9.1 9.2 9.3 9.4" "backups")
if [ -z "$DBCKDIR" ]; then
  wlog "No postgres backup directory found!"
  exit 1
fi
wlog "Found $DBCKDIR directory"
HOST_PRD=$(get_cfg_value 0 production_host)
HOST_DEV=$(get_cfg_value 0 development_host)
wlog "PRD=$HOST_PRD"
wlog "DEV=$HOST_DEV"
OWN=$(get_cfg_value 0 db_user)
if [ -z "$OWN" ]; then
  OWN=odoo
fi
wlog "OWN=$OWN"
if [ -z "$olddb" ]; then
  OLDDB=$(get_cfg_value 0 db_name)
else
  OLDDB=$olddb
fi
if [ -z "$newdb" ]; then
  NEWDBS=$(get_cfg_value 0 bck_db)
  if [ "$NEWDBS" == "*" ]; then
    NEWDBS=$OLDDB
  fi
elif [ "$newdb" == "*" ]; then
  NEWDBS=$OLDDB
else
  NEWDBS=$newdb
fi
if [ -z "$OLDDB" -o -z "$NEWDBS" ]; then
  print_help
  exit
fi
TEST_DB="$(get_cfg_value 0 test_db)"
if [ -z "$TEST_DB" ]; then
  TEST_DB="$(get_cfg_value 0 bck_db)"
fi
if [[ $seldate =~ [0-9]{8} ]]; then
  NDAYSB=$seldate
elif [ "$HOSTNAME" == "$HOST_PRD" ]; then
  NDAYSB="$(get_cfg_value 0 PRD_num_days_before)"
elif [ "$HOSTNAME" == "$HOST_DEV" ]; then
  NDAYSB="$(get_cfg_value 0 DEV_num_days_before)"
fi
if [ -z "$NDAYSB" ]; then
  NDAYSB="$(get_cfg_value 0 num_days_before)"
fi
if [ -z "$NDAYSB" ]; then
  NDAYSB=yesterday
fi
ODOO_RPC_HOST="$(get_cfg_value 0 odoo_rpc_host)"
if [ -z "$ODOO_RPC_HOST" ]; then ODOO_RPC_HOST=localhost; fi
ODOO_RPC_PROTOCOL="$(get_cfg_value 0 odoo_rpc_protocol)"
if [ -z "$ODOO_RPC_PROTOCOL" ]; then ODOO_RPC_PROTOCOL=xmlrpc; fi
ODOO_RPC_XMLPORT="$(get_cfg_value 0 odoo_rpc_xmlport)"
if [ -z "$ODOO_RPC_XMLPORT" ]; then ODOO_RPC_XMLPORT=8069; fi
ODOO_VERSION="$(get_cfg_value 0 odoo_version)"
if [ -z "$ODOO_VERSION" ]; then ODOO_VERSION=7.0; fi
ODOO_RPC_PWD="$(get_cfg_value 0 odoo_rpc_pwd)"
if [ -z "$ODOO_RPC_PWD" ]; then ODOO_RPC_PWD=admin; fi
ctr=0
passed=""
for NEWDB in ${NEWDBS//,/ }; do
  for ND in ${NDAYSB//,/ }; do
    if [[ " $passed " =~ [[:space:]]$NEWDB[[:space:]] ]]; then
       continue
    fi
    if [[ $ND =~ [0-9]{8} ]]; then
      dtdb=$ND
    elif [[ $ND =~ [0-9]+ ]]; then
      NDAYB=-${ND}day
      dtdb=$(date -d $NDAYB +"%Y%m%d")
    else
      dtdb=$(date -d yesterday +"%Y%m%d")
    fi
    if [[ " $passed " =~ [[:space:]]$dtdb[[:space:]] ]]; then
       continue
    fi
    if [ $opt_mail -eq -1 ]; then
      opt_mail=0
      if [ "$HOSTNAME" == "$HOST_DEV" ]; then
        opt_mail=1
      elif [[ $NEWDB =~ $TEST_DB ]]; then
        opt_mail=1
      fi
    fi
    echo "Searching $DBCKDIR/$OLDDB-$dtdb.sql"
    if [ ! -f $DBCKDIR/$OLDDB-$dtdb.sql ]; then
      echo "No sql file found!!!"
      exit 1
    fi
    if [ $opt_dry_run -eq 0 ]; then
      wlog "Restore/duplicate $OLDDB-$dtdb.sql $NEWDB"
    else
      echo "Should restore $OLDDB-$dtdb.sql $NEWDB"
    fi
    if [ "$NEWDB" == "$OLDDB" -a "$dtdb" != "00000000" ]; then
      backup_db $OLDDB
    fi
    pycmd=$HOME/$NEWDB.py
    echo "import oerplib">$pycmd
    echo "oerp = oerplib.OERP(server='$ODOO_RPC_HOST',">>$pycmd
    echo "                    protocol='$ODOO_RPC_PROTOCOL',">>$pycmd
    echo "                    port='$ODOO_RPC_XMLPORT',">>$pycmd
    echo "                    version='$ODOO_VERSION')">>$pycmd
    echo "oerp.db.drop('$ODOO_RPC_PWD',">>$pycmd
    echo "             '$NEWDB')">>$pycmd
    bashcmd=$HOME/$NEWDB.sh
    echo "# Check for $NEWDB">$bashcmd
    echo ". $Z0LIBDIR">>$bashcmd
    echo "eval \$(init_cfg)">>$bashcmd
    echo "eval \$(active_cfg)">>$bashcmd
    echo "set_tlog_file "$publog"">>$bashcmd
    echo "wlog \".. Starting mail server checker ...\"">>$bashcmd
    echo "OMS=1">>$bashcmd
    echo "FMS=1">>$bashcmd
    echo "while [ \$FMS -gt 0 -o \$OMS -gt 0 ]; do">>$bashcmd
    echo "  sleep 20">>$bashcmd
    echo "  if [ \$OMS -gt 0 ]; then">>$bashcmd
    echo "    x=\$(psql -tc \"select * from ir_mail_server where active=true;\" $NEWDB)">>$bashcmd
    echo "    if [ -n \"\$x\" ]; then">>$bashcmd
    echo "      psql -tc \"update ir_mail_server set active=false where active=true;\" $NEWDB">>$bashcmd
    echo "      ((OMS--))">>$bashcmd
    echo "      wlog \".. Found out mail server ...\"">>$bashcmd
    echo "    fi">>$bashcmd
    echo "  fi">>$bashcmd
    echo "  if [ \$FMS -gt 0 ]; then">>$bashcmd
    echo "    x=\$(psql -tc \"select * from fetchmail_server where active=true;\" $NEWDB)">>$bashcmd
    echo "    if [ -n \"\$x\" ]; then">>$bashcmd
    echo "      psql -tc \"update fetchmail_server set active=false where active=true;\" $NEWDB">>$bashcmd
    echo "      ((FMS--))">>$bashcmd
    echo "      wlog \".. Found fetch mail server ...\"">>$bashcmd
    echo "    fi">>$bashcmd
    echo "  fi">>$bashcmd
    # echo "  if [ \$FMS -eq 0 -a  \$OMS -gt 1 ]; then">>$bashcmd
    # echo "    ((FMS++))">>$bashcmd
    # echo "  fi">>$bashcmd
    echo "done">>$bashcmd
    echo "wlog \".. All mail servers are disabled!\"">>$bashcmd
    chmod +x $bashcmd
    fsql=$HOME/$NEWDB.sql
    wlog "Prepare file script $fsql ..."
    echo "\\c postgres">$fsql
    echo "\\echo Creating new DB $NEWDB">>$fsql
    echo "DROP DATABASE IF EXISTS $NEWDB;">>$fsql
    echo "CREATE DATABASE $NEWDB TEMPLATE template1;">>$fsql
    echo "\\c $NEWDB">>$fsql
    echo "\\echo Loading data into DB $NEWDB">>$fsql
    echo "\\i $DBCKDIR/$OLDDB-$dtdb.sql">>$fsql
    if [ $opt_mail -gt 0 ]; then
      wlog "Database without inbound/outbound mails"
      echo "\\echo Disabling inbound mails ...">>$fsql
      # echo "update ir_cron set interval_number=60000 where name='Fetchmail Service';">>$fsql
      echo "update fetchmail_server set active=false;">>$fsql
      echo "\\echo Disabling outbound mails ...">>$fsql
      echo "update ir_mail_server set active=false;">>$fsql
      echo "\\echo Disabling automatic actions ...">>$fsql
      echo "update base_action_rule set active=false;">>$fsql
    fi
    echo "ALTER DATABASE $NEWDB OWNER TO $OWN;">>$fsql
    if [ $opt_dry_run -eq 0 ]; then
      wlog "Starting restore $NEWDB"
      kill_process
      python $pycmd
      $bashcmd &
      psql -U$opt_user -d postgres -f $fsql -o $NEWDB.log
      rm -f $pycmd
      rm -f $bashcmd
      wlog "Restore $NEWDB terminated"
      ((ctr++))
    fi
    passed="$passed $NEWDB $dtdb"
  done
done
if [ $opt_dry_run -eq 0 ]; then
  sleep 30
fi
wlog "All $ctr databases are restored"
exit 0
