#! /bin/bash
# -*- coding: utf-8 -*-
# Backup postgres DB
#
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
# This free software is released under GNU Affero GPL3

THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)

__version__="1.3.20"


detached_login() {
# detached_login([path] [path2] [path3])
    if [ $opt_cron -gt 0 -a "$SHELL" == "/bin/sh" ]; then
      if [ $opt_dry_run -eq 0 ]; then
        fqcmd=$(readlink -f $0)
        wlog "Run $fqcmd in cron mode"
        SHELL=/bin/bash exec "$fqcmd" "$@"
      fi
    elif [ $opt_cron -gt 0 -a -f $HOME/.bash_profile ]; then
      wlog "Simulate login ($HOME/.bash_profile)"
      . $HOME/.bash_profile
    fi
    if [[ ":$PATH:" =~ /usr/local/bin ]]; then
      :
    else
      export PATH=/usr/local/bin:$PATH
    fi
    if [ -n "$1" ]; then
      if [ -d $1 ]; then
        if [[ ":$PATH:" =~ $1 ]]; then
          :
        else
          export PATH=$PATH:$1
        fi
      fi
    fi
    if [ -n "$2" ]; then
      if [ -d $2 ]; then
        if [[ ":$PATH:" =~ $2 ]]; then
          :
        else
          export PATH=$PATH:$2
        fi
      fi
    fi
    if [ -n "$3" ]; then
      if [ -d $3 ]; then
        if [[ ":$PATH:" =~ $3 ]]; then
          :
        else
          export PATH=$PATH:$3
        fi
      fi
    fi
    wlog "PATH=$PATH"
}

create_db_list() {
# create_db_list(dbsel pgsql_dir bck_dir bck_db)
    local PGDIR=$2
    if [ -z $3 ]; then
      local DBCKDIR="$PGDIR/backups"
    else
      local DBCKDIR=$3
    fi
    local flst="$HOME/db_pgsql.lst"
    local re=$1
    if [ -z "$re" ]; then
      re=".*"
    fi
    local redb=$4
    if [ -z "$redb" ]; then
      redb="test"
    fi
    if [ $opt_dry_run -gt 0 ]; then
      echo "Select DB matches $re in $DBCKDIR"
    else
      wlog "Select DB matches $re in $DBCKDIR"
    fi
    psql -U$opt_user -lt -o $flst
    sort $flst -f -o $flst
    local dblist=
    for db in $(awk -F"|" '{ print $1 }' $flst); do
      db=$(echo $db|sed -e 's/^ *//' -e 's/ *$//')
      if [[ $db =~ $redb ]]; then
        wlog "DB $db is backup copy"
      else
        if [[ $db =~ $re ]]; then
          if [ "$HOSTNAME" == "$HOST_PRD" -o \( "${db:0:4}" != "prov" -a "${db:0:4}" != "test" \) ]; then
            dblist=$(echo "$dblist $db")
          fi
        fi
      fi
    done
    rm -f $flst
    echo "$dblist"
}

inherit_options() {
    OPTS=
    if [ $opt_cron -gt 0 ]; then
      OPTS=K$OPTS
    fi
    if [ $opt_dry_run -gt 0 ]; then
      OPTS=n$OPTS
    fi
    if [ $opt_verbose -gt 0 ]; then
      OPTS=v$OPTS
    fi
    if [ -n "$opt_user" ]; then
      OPTS="${OPTS}U$opt_user"
    fi
    if [ -n "$OPTS" ]; then
      OPTS=-$OPTS
    fi
}

OPTOPTS=(h        K        l       n            o        U          V           v)
OPTDEST=(opt_help opt_cron opt_log opt_dry_run  opt_name opt_user   opt_version opt_verbose)
OPTACTI=(1        1        "="     1            "="      "="        "*>"        1)
OPTDEFL=(0        0        ""      0            ""       "postgres" ""          0)
OPTMETA=("help"   "cron"   "file"  "do nothing" "fname"  "username" "version"   "verbose")
OPTHELP=("this help"\
 "run in cron environment"\
 "log filename (def /var/log/bckdb.log)"\
 "do nothing (dry-run)"\
 "output filename (def dbname-date)"\
 "username (def postgres)"\
 "show version"\
 "verbose mode")
OPTARGS=(dbsel)

parseoptargs $@

if [ "$opt_version" ]
then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]
then
  print_help "Backup postgres DB"\
  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
if [ -z "$opt_log" ]; then
  publog="/var/log/zar/bckdb.log"
else
  publog=$opt_log
fi
FCONF=$TDIR/zar.conf
CFG_init
set_tlog_file "$publog"
if [ $opt_cron -gt 0 ]; then
  detached_login "$@"
fi
link_cfg $FCONF
wlog "Starting backup $__version__ by $USER"

PGDIR=$(findpkg "" "/var/lib" "postgresql  pgsql" "8.2 8.3 9.0 9.1 9.2 9.3 9.4")
if [ -z "$PGDIR" ]; then
  wlog "No postgres directory found!"
  exit 1
fi
wlog "Found $PGDIR directory"
DBCKDIR="$PGDIR/backups"
if [ ! -d $DBCKDIR ]; then
  mkdir -p $DBCKDIR
fi
wlog "Backup directory is $DBCKDIR"
HOST_PRD=$(get_cfg_value 0 production_host)
HOST_DEV=$(get_cfg_value 0 development_host)
wlog "PRD=$HOST_PRD"
wlog "DEV=$HOST_DEV"
if [ -z "$dbsel" ]; then
  dbsel="$(get_cfg_value 0 dbfilter)"
fi
REST2="$(get_cfg_value 0 enable_restore)"
TEST_DB="$(get_cfg_value 0 test_db)"
NEWDBS=$(get_cfg_value 0 bck_db)
REDB="($TEST_DB|${NEWDBS//,/|})"
if [ -z $REDB ]; then
  REDB="test"
fi
dblist=$(create_db_list "$dbsel" "$PGDIR" "$DBCKDIR" "$REDB")
ctr=0
if [ -n "$dblist" ]
then
  inherit_options
  if [ -z "$opt_name" ]; then
    wlog "\$ ./zar_purge $OPTS $dbsel"
    ./zar_purge $OPTS "'$dbsel'"
  fi
  dtc=$(date +%Y%m%d)
  for db in $dblist
  do
    wlog "backup $db"
    if [ -z "$opt_name" ]; then
      sqlfname=$DBCKDIR/$db-$dtc.sql
    else
      sqlfname=$opt_name
      if [ -f $sqlfname ]; then
        echo "File $sqlfname already exists!"
        exit 1
      fi
    fi
    if [ "$HOSTNAME" != "$HOST_DEV" ]; then
      if [ $opt_dry_run -gt 0 ]; then
        wlog "> pg_dump -U$opt_user -Fp -f $sqlfname $db"
      else
        wlog "\$ pg_dump -U$opt_user -Fp -f $sqlfname $db"
        pg_dump -U$opt_user -Fp -f $sqlfname $db
        if [ -z "$opt_name" -a "$HOSTNAME" == "$HOST_PRD" -a -n "$HOST_DEV" ]; then
          wlog "\$ scp $sqlfname $HOST_DEV:$sqlfname"
          scp $sqlfname $HOST_DEV:$sqlfname
        fi
      fi
      ((ctr++))
    else
      wlog "Waiting for backup from production host"
      if [ $opt_dry_run -eq 0 ]; then
        wctr=25
        while [ ! -f $sqlfname -a $wctr -gt 0 ]; do
          sleep 180
          ((wctr--))
        done
        wlog "Received $sqlfname"
      fi
    fi
  done
  wlog "All $ctr databases are backupped!"
  if [ -z "$opt_name" ]; then
    if [ -z "$REST2" ]; then
      if [ "$HOSTNAME" == "$HOST_PRD" -a -z "$HOST_DEV" ]; then
        wlog "\$ ./zar_rest $OPTS"
        ./zar_rest $OPTS
      elif [ "$HOSTNAME" == "$HOST_DEV" ]; then
        wlog "\$ ./zar_rest $OPTS"
        ./zar_rest $OPTS
      fi
    else
      if [ "$REST2" == "1" ]; then
        wlog "\$ ./zar_rest $OPTS"
        ./zar_rest $OPTS
      fi
    fi
  fi
fi
exit 0
