#! /bin/bash
# -*- coding: utf-8 -*-
#
# check nightly Zeroincombenze software for continuous integration
# Tool for internal use
#
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com

if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -e ./z0librc ]; then
. ./z0librc
elif [ -e ../z0librc ]; then
. ../z0librc
elif [ -e ~/z0librc ]; then
. ~/z0librc
elif [ -f /etc/z0librc ]; then
. /etc/z0librc
else
  echo "Library file z0librc not found!"
  exit 1
fi

__version__=0.1.6
OPTOPTS=(h        n            V           v)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose)
OPTACTI=(1        "1>"         "*>"        1)
OPTDEFL=(0        0            ""          0)
OPTMETA=("help"   "do nothing" "version"   "verbose")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode")
OPTARGS=(src tgt)

parseoptargs "$@"

if [ "$opt_version" ]; then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]; then
  print_help "Check for test_nightly execution"\
  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi

if [ ! -d ~/dev/pypi/travis_emulator/travis_emulator/tests ]; then
  echo "Invalid environment!"
  exit 1
fi

sts=0
if [ -f ~/test_nightly.log ]; then
  dt_last_exec=$(tail -n1 ~/test_nightly.log|awk '{print $1}'|tr -d "-")
else
  dt_last_exec="20160101"
fi
dt_limit=$(date +%Y%m%d -d yesterday)
if [ $dt_last_exec -lt $dt_limit ]; then
  cd ~/dev/pypi/travis_emulator/travis_emulator/tests
  echo "> ./all_tests"
  if [ $opt_dry_run -eq 0 ]; then
    ./all_tests &>/dev/null
  fi
  sts=$?
  if [ $sts -eq 0 ]; then
    echo "> ~/dev/pypi/travis_emulator/travis_emulator/test_nightly -K"
    if [ $opt_dry_run -eq 0 ]; then
      ~/dev/pypi/travis_emulator/travis_emulator/test_nightly -K
    fi
  fi
fi
exit $sts
