#! /bin/bash
# -*- coding: utf-8 -*-
##############################################################################
#
#    Copyright (C) SHS-AV s.r.l. (<http://ww.zeroincombenze.it>)
#    All Rights Reserved
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either versiofn 3 of the
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYTHONPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib ${PYTHONPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi

__version__=0.2.6

if [ "$OPTARGS_TEST_1_2" ]; then
  test_1_2=$OPTARGS_TEST_1_2
else
  test_1_2=1
fi
if [ $test_1_2 -eq 1 ]; then
OPTOPTS=(h        n            V           v           q           p        t)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose opt_verbose opt_path opt_test)
OPTACTI=(1        "1>"         "*>"        1           0           "=>"     0)
OPTDEFL=(1        0            ""          0           0           ~/       0)
OPTMETA=("help"   "do nothing" "version"   "verbose"   "silent"    "path"   "n/a")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode"\
 "silent mode"\
 "destination path"\
 "test mode")
OPTARGS=(src tgt)
else
OPTOPTS=(h        n            V           v           q           p)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose opt_verbose opt_path)
OPTACTI=(1        "1>"         "*>"        1           0           "=>")
OPTDEFL=(1        0            ""          0           0           ~/)
OPTMETA=("help"   "do nothing" "version"   "verbose"   "silent"    "path")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode"\
 "silent mode"\
 "destination path")
OPTARGS=(src tgt)
fi
parseoptargs "$@"
echo "help    = <$opt_help>"
echo "dry_run = <$opt_dry_run>"
echo "version = <$opt_version>"
echo "verbose = <$opt_verbose>"
echo "path    = <$opt_path>"
echo ""
echo "#1      = <$src>"
echo "#2      = <$tgt>"

if [ "$opt_version" ]; then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]; then
  print_help "Sample for optargs"\
  "(C) 2015-2018 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
