#! /bin/bash
# -*- coding: utf-8 -*-
##############################################################################
#
#    Copyright (C) SHS-AV s.r.l. (<http://ww.zeroincombenze.it>)
#    All Rights Reserved
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either versiofn 3 of the
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
export READLINK
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
for d in $PYPATH /etc; do
  if [[ -e $d/z0librc ]]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [[ -z "$Z0LIBDIR" ]]; then
  echo "Library file z0librc not found!"
  exit 72
fi
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"

__version__=1.0.2

if [ "$OPTARGS_TEST_1_2" ]; then
  test_1_2=$OPTARGS_TEST_1_2
else
  test_1_2=1
fi
if [ $test_1_2 -eq 1 ]; then
OPTOPTS=(h        n            V           v           q           p        t)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose opt_verbose opt_path opt_test)
OPTACTI=(1        "1>"         "*>"        1           0           "=>"     0)
OPTDEFL=(1        0            ""          0           0           ~/       0)
OPTMETA=("help"   "do nothing" "version"   "verbose"   "silent"    "path"   "n/a")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode"\
 "silent mode"\
 "destination path"\
 "test mode")
OPTARGS=(src tgt)
else
OPTOPTS=(h        n            V           v           q           p)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose opt_verbose opt_path)
OPTACTI=(1        "1>"         "*>"        1           0           "=>")
OPTDEFL=(1        0            ""          0           0           ~/)
OPTMETA=("help"   "do nothing" "version"   "verbose"   "silent"    "path")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode"\
 "silent mode"\
 "destination path")
OPTARGS=(src tgt)
fi
parseoptargs "$@"
echo "help    = <$opt_help>"
echo "dry_run = <$opt_dry_run>"
echo "version = <$opt_version>"
echo "verbose = <$opt_verbose>"
echo "path    = <$opt_path>"
echo ""
echo "#1      = <$src>"
echo "#2      = <$tgt>"

if [[ "$opt_version" ]]; then
  echo "$__version__"
  exit 0
fi
if [[ $opt_help -gt 0 ]]; then
  print_help "Sample for optargs"\
  "© 2015-2021 by zeroincombenze®\nhttps://zeroincombenze-tools.readthedocs.io/\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
