#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on lisa
# Check for remove
#
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib ${PYPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $HOME/tools/zerobug $HOME/dev ${PYPATH//:/ } . .." "zerobug")
if [ -z "$Z0TLIBDIR" ]; then
  echo "Library file z0testrc not found!"
  exit 2
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.3.0.14

test_run () {
# test_run(msg,package,disto,cmd)
    # set -x #debug
    TPRODUCT="$RUNDIR/lisa -T"
    local msg="$1"
    local Package="$2"
    local Disto="$3"
    local cmd="$4"
    local FH=
    local opt_e="-E$Disto"
    local opt_ij="-I$Package,wget,gcc,git"
    if [ "$Disto" == "." ]; then
        local FH=$Real_FH
        local Disto=$Real_DISTO
        local opt_e=
    elif [ "$Disto" == "Ubuntu12" -o "$Disto" == "Ubuntu14" ]; then
      local FH="Debian"
    elif [ "$Disto" == "CentOS6" -o "$Disto" == "CentOS7" ]; then
      local FH="RHEL"
    fi
    if [ "$Package" == "httpd" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="apache2"
      fi
      local opt_ij="-I$Package,vsftpd"
    elif [ "$Package" == "apache2" ]; then
      if [ "$FH" == "RHEL" ]; then
        local Package="httpd"
      fi
      local opt_ij="-I$Package,vsftpd"
    elif [ "$Package" == "pip" -o "$Package" == "python-pip" ]; then
        local opt_ij="-I$Package,python-pip,python-whell,wheel"
    elif [ "$Package" == "postgresql-server" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="postgresql"
      fi
      local opt_ij="-I$Package,postgresql-client-common,postgresql-contrib"
    elif [ "$Package" == "postgresql" ]; then
      if [ "$FH" == "RHEL" ]; then
        local Package="postgresql-server"
      fi
      local opt_ij="-I$Package,postgresql-client-common,postgresql-contrib"
    elif [ "$Package" == "postgres" ]; then
      if [ "$FH" == "Debian" ]; then
        local Package="postgresql"
      elif [ "$FH" == "RHEL" ]; then
        local Package="postgresql-server"
      fi
      local opt_ij="-I$Package,postgresql-client-common,postgresql-contrib"
    elif [ "$Package" == "openssh" ]; then
      local Package="openssh-server"
      opt_ij="-I$Package,openssh-client,openssh-clients,mod_ssl,mod_proxy_html,iptables-services,bind-utils"
    elif [ "$Package" == "openssh-server" ]; then
      opt_ij="-I$Package,openssh-client,openssh-clients,mod_ssl,mod_proxy_html,iptables-services,bind-utils"
    fi
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $TESTDIR/res/${Package}__${Disto}.07.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${Disto}.07.test
      elif [ -f $TESTDIR/res/${Package}__${FH}.07.test ]; then
        TESTOUT=$TESTDIR/res/${Package}__${FH}.07.test
      elif [ -f $TESTDIR/res/${Package}.07.test ]; then
        TESTOUT=$TESTDIR/res/${Package}.07.test
      else
        TESTOUT=
        echo "File test comparison ${Package}__${Disto} not found!"
      fi
      rm -f $TESTDIR/lisa.out
      eval $TPRODUCT $opt_e remove $2 $opt_ij>$TESTDIR/lisa.out
    fi
    # set +x #debug
    ci-test "$msg" "$TESTOUT" "$TESTDIR/lisa.out" "$cmd"
    return $s
}

test_01() {
if [ ${opt_dry_run:-0} -eq 0 ]; then
  rm -f $TESTDIR/res/*.07.test
  cat <<EOF >$TESTDIR/res/lisa__Debian.07.test
> rm /usr/bin/lisa
> rm /usr/bin/lisa.*
> rm /usr/bin/lisa_*
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/lisa__RHEL.07.test
> rm /usr/bin/lisa
> rm /usr/bin/lisa.*
> rm /usr/bin/lisa_*
EOF
  cat <<EOF >$TESTDIR/res/apache2__Debian.07.test
> service apache2 stop
# service vsftpd stop
> apt-get -y remove apache2
# apt-get -y remove vsftpd
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/httpd__CentOS7.07.test
> systemctl stop httpd
# systemctl stop vsftpd
> yum -y remove httpd
# yum -y remove vsftpd
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
EOF
  cat <<EOF >$TESTDIR/res/httpd__CentOS6.07.test
> service httpd stop
> yum -y remove httpd
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__CentOS7.07.test
> systemctl stop postgresql
> yum -y remove postgresql-server
# yum -y remove postgresql-client-common
# yum -y remove postgresql-contrib
EOF
  cat <<EOF >$TESTDIR/res/postgresql-server__CentOS6.07.test
> service postgresql stop
> yum -y remove postgresql-server
# yum -y remove postgresql-client-common
# yum -y remove postgresql-contrib
EOF
  cat <<EOF >$TESTDIR/res/postgresql__Debian.07.test
> service postgresql stop
> apt-get -y remove postgresql
# apt-get -y remove postgresql-client-common
# apt-get -y remove postgresql-contrib
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/pip__CentOS6.07.test
> yum -y remove python-pip
EOF
  cat <<EOF >$TESTDIR/res/pip__CentOS7.07.test
> yum -y remove python-pip
EOF
  cat <<EOF >$TESTDIR/res/pip__Debian.07.test
> apt-get -y remove python-pip
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/python-pip__Debian.07.test
> apt-get -y remove python-pip
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/python-pip__CentOS6.07.test
> yum -y remove python-pip
EOF
  cat <<EOF >$TESTDIR/res/python-pip__CentOS7.07.test
> yum -y remove python-pip
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__Debian.07.test
> service ssh stop
> apt-get -y remove openssh-server
# apt-get -y remove openssh-client
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
> apt-get autoremove
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__CentOS7.07.test
> systemctl stop sshd
> yum -y remove openssh-server
# yum -y remove openssh-clients
# yum -y remove mod_ssl
# yum -y remove mod_proxy_html
# yum -y remove iptables-services
# yum -y remove bind-utils
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
EOF
  cat <<EOF >$TESTDIR/res/openssh-server__CentOS6.07.test
> service sshd stop
> yum -y remove openssh-server
# yum -y remove openssh-clients
# yum -y remove mod_ssl
# yum -y remove mod_proxy_html
# yum -y remove iptables-services
# yum -y remove bind-utils
# iptables -D INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
EOF
fi
Real_FH=$(xuname "-f")
x=$(xuname "-v")
v=$(echo $x|awk -F. '{print $1}')
Real_DISTO=$(xuname "-d")$v

for Package in lisa apache2 httpd\
  pip python-pip\
  postgres postgresql postgresql-server\
  openssh openssh-server; do
  for Disto in . Ubuntu14 CentOS7 Ubuntu12 CentOS6; do
     if [ "$Disto" == "." ]; then
       opt_e=
     else
       opt_e="-E$Disto"
     fi
     test_run "remove $Package $opt_e" "$Package" "$Disto" "diff"
  done
done
}

Z0BUG_setup() {
    [ -f /tmp/lisa.tar.gz ] && rm -f /tmp/lisa.tar.gz
    [ -d /tmp/lisa ] && rm -fR /tmp/lisa
    [ -f "/tmp/wkhtml*"  ] && rm -f /tmp/wkhtml*
    if [ -f "/tmp/lisa*"  ]; then
      echo "Test not executable!"
      echo "Please, remove lisa file/directory from /tmp"
      exit 1
    fi
    if [ -f "/tmp/wkhtml*"  ]; then
      echo "Test not executable!"
      echo "Please, remove wkhtmltopdf file from /tmp"
      exit 1
    fi
    export PYTHONWARNINGS="ignore"
}


Z0BUG_init
parseoptest -l$TESTDIR/test_lisa.log "$@" "-O"
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
if [ ${opt_oeLib:-0} -ne 0 ]; then
  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/dev ${PYPATH//:/ } . .." "clodoo")
  if [ -z "$ODOOLIBDIR" ]; then
    echo "Library file odoorc not found!"
    exit 2
  fi
  . $ODOOLIBDIR
fi


UT_LIST=""
if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
exit $sts
