#! /bin/bash
# -*- coding: utf-8 -*-
#
# test nightly Zeroincombenze sofware for continuous integration
# Tool for internal use
#
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com

if [ $EUID -eq 0 -a -d /opt/odoo/tools/z0lib ]; then
  cd /opt/odoo/tools/z0lib
fi
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
FCONF=$TDIR/.$THIS.conf
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -e ./z0librc ]; then
. ./z0librc
elif [ -e ../z0librc ]; then
. ../z0librc
elif [ -e ~/z0librc ]; then
. ~/z0librc
elif [ -f /etc/z0librc ]; then
. /etc/z0librc
else
  echo "Library file z0librc not found!"
  exit 1
fi

__version__=0.1.62.4
# main
OPTOPTS=(h        A         C        K        n           O        t        V           v           8     9)
OPTDEST=(opt_help opt_nall  opt_ncld opt_cron opt_dry_run opt_odoo opt_test opt_version opt_verbose opt_8 opt_9)
OPTACTI=(1        "*>"      "*>"     1        1           "*>"     1        "*>"        1           1     1)
OPTDEFL=(0        ""        ""       0        0           ""       0        ""          0           0     0)
OPTMETA=("help"   "not_all" "nocld"  "cron"   "noop"      "odoo"   "test"   "version"   "verbose"   "x"   "x")
OPTHELP=("this help"\
 "do not execute all Odoo test"\
 "do not execute clodoo statements"\
 "run in cron environment"\
 "do nothing (dry-run)"\
 "run odoo burst tests"\
 "show configuration and do nothing (dry-run)"\
 "show version"\
 "verbose mode"\
 "undocumented"\
 "do not upgrade this script")
 OPTARGS=(tgt)

parseoptargs "$@"
if [ "$opt_version" ]; then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]; then
  print_help "Test nightly"\
  "(C) 2015-2016 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi


upgrade_myself () {
# THIS is developed on /opt/odoo/dev/pypi/travis_emulator/travis_emulator (DEV_DIR)
# If regression test ends successfully, is copied to /opt/odoo/tools/travis_emulator (PRD_DIR)
# Because THIS runs on ~/dev (RUN_DIR), is copied from /opt/odoo/tools/travis_emulator
# after a short regression test
    local PRD_DIR=/opt/odoo/tools/travis_emulator
    local RUN_DIR=$(readlink -f ~/dev)
    local sts=0
    if [ "$USER" == "odoo" -a -f $DEV_DIR/$THIS -a "$TDIR" != "$DEV_DIR" ]; then
      elog "Check for newest version to run"
      diff -q $DEV_DIR/$THIS $TDIR/$THIS
      local sts=$?
      if [ $opt_dry_run -eq 0 -a $sts -gt 0 ]; then
        elog "Found newest version of $THIS $__version__"
        test_pkg_pypi $PKGSLX
        local sts=$?
        if [ $sts -eq 0 ]; then
          $DEV_DIR/$THIS -n
          local sts=$?
        fi
        if [ $sts -eq 0 ]; then
          $DEV_DIR/$THIS -9
          local sts=$?
        fi
        if [ $sts -eq 0 ]; then
          elog "Upgrade myself ($DEV_DIR/$THIS -8 "$TDIR")!"
          exec $DEV_DIR/$THIS -8 "$TDIR"
          exit 1 # never should execute it!
        fi
        elog "!? Newest version run failed! Run current version"
      fi
    elif [ "$USER" != "odoo" -a -f $PRD_DIR/$THIS ]; then
      elog "Check for newest version to run"
      if [ -f $RUN_DIR/$THIS ]; then
        diff -q $PRD_DIR/$THIS $RUN_DIR/$THIS
        local sts=$?
      else
        local sts=1
      fi
      if [ $opt_dry_run -eq 0 -a $sts -gt 0 ]; then
        $PRD_DIR/$THIS -9
        local sts=$?
        if [ $sts -eq 0 ]; then
          elog "Upgrade myself ($PRD_DIR/$THIS -8 "$RUN_DIR")!"
          exec $PRD_DIR/$THIS -8 "$RUN_DIR"
          exit 1 # never should execute it!
        fi
      fi
    fi
    return $sts
}


test_pkg_pypi () {
# test_pkg_pypi (name)
# return: sts
    if [ ! -d ~/dev/svg ]; then
      mkdir ~/dev/svg
    fi
    wlog "------------------------------------"
    wlog "Required test for $1 package ..."
    if [ ! -d ~/dev/pypi/$1 ]; then
      wlog "!? Package $1 not found!"
      exit 1
    fi
    if [ ! -d ~/dev/pypi/$1/$1 ]; then
      wlog "!? Invalid package $1!"
      exit 1
    fi
    if [ ! -d ~/dev/pypi/$1/$1/tests ]; then
      wlog "!? Unit test for package $1 not found"
      generate_svg "$1" "FAIL"
      exit 0
    fi
    sts=0
    if [ -f ~/dev/pypi/$1/$1/tests/all_tests ]; then
      wlog "> make test  # $1"
      cd ~/dev/pypi/$1/$1/tests
      if [ $opt_dry_run -eq 0 ]; then
        ./all_tests &>/dev/null
        sts=$?
      fi
    elif [ -f ~/dev/pypi/$1/$1/tests/test_$1.py ]; then
      wlog "> make test  # $1"
      cd ~/dev/pypi/$1/$1/tests
      if [ $opt_dry_run -eq 0 ]; then
        PYTHONPATH=~/dev/pypi/$1 python ~/dev/pypi/$1/$1/tests/test_$1.py &>/dev/null
        sts=$?
      fi
    else
      wlog "!? No unit test found!"
      sts=127
    fi
    if [ $sts -eq 0 ]; then
      cd ~/dev/pypi/$1/$1
      wlog "> make wep  # $1"
      (($opt_dry_run))||make wep
      wlog "Package $1: test successfully terminated"
      if [ -x ./$1 ]; then
        local ver=$(./$1 -V)
      else
        local ver=
      fi
      generate_svg "$1" "OK" "$ver"
    else
      wlog "!? Package $1: test failed ($sts)! See package log in ~/dev/pypi/$1/$1/tests!!!"
      generate_svg "$1" "FAIL"
    fi
    return $sts
}


pkg_pypi_commit () {
# pkg_pypi_commit (name)
# return: sts
    wlog "Committing $1 package  ..."
    if [ ! -d ~/dev/pypi/$1 ]; then
      wlog "!? Package $1 not found!"
      exit 1
    fi
    if [ ! -d ~/dev/pypi/$1/$1 ]; then
      wlog "!? Invalid package $1!"
      exit 1
    fi
    if [ ! -d ~/dev/pypi/$1/$1/tests ]; then
      wlog "!? Unit test for package $1 not found"
      exit 0
    fi
    sts=0
    cd ~/dev/pypi/$1/$1
    wlog "> make replace  # $1"
    if [ $opt_dry_run -eq 0 ]; then
      if [ $opt_verbose -gt 0 ]; then
        make replace &>>~/$THIS.log
      else
        make replace &>/dev/null
      fi
      if [ "$HOSTNAME" == "$DEV_HOST" -a $sts -eq 0 ]; then
        wlog "> make commit # $1"
        if [ $opt_verbose -gt 0 ]; then
          make commit &>>~/$THIS.log
        else
          make commit &>/dev/null
        fi
      fi
    fi
    return $sts
}


oe_upd_burst () {
    if [ $EUID -eq 0 ]; then
      if [ "$HOSTNAME" == "$PRD_HOST" ]; then
        svc_name="openerp"
        clodir="/opt/openerp/7.0/clodoo"
      else
        svc_name="odoo-server"
        clodir="/opt/odoo/clodoo"
      fi
      wlog "service $svc_name restart"
      service $svc_name restart
      cd $clodir
      PATH=$PATH:$clodir
    fi
    if [ -f $1.conf ]; then
      sleep 30
      sts=0
      wlog "clodoo.py -d demo -c $1.conf"
      clodoo.py -d "demo" -c $1.conf
      sts=$?
      if [ $sts -eq 0 ]; then
        sleep 30
        wlog "clodoo.py -d zeroincombenze -c $1.conf"
        clodoo.py -d "zeroincombenze" -c $1.conf
        sts=$?
      fi
      if [ $sts -eq 0 ]; then
        for i in {0..11}; do
          l=${#i}
          ((l--))
          n="0$i"
          n=${n:l}
          db="zi0001$n[0-9]{2}"
          wlog "> clodoo.py -d $db -c $1.conf"
          clodoo.py -d "$db" -c $1.conf
          sts=$?
          if [ $sts -gt 0 ]; then
            break
          fi
          sleep 50
          if [ $EUID -eq 0 ]; then
            service $svc_name restart
            sleep 10
          else
            sleep 40
          fi
        done
      fi
      if [ $sts -eq 0 ]; then
        mv $1.conf $.conf.bak
      fi
    else
      wlog "Nothing to do"
    fi
    if [ -f /var/log/$THIS.log ]; then
      chmod +rw /var/log/$THIS.log
    fi
    return $sts
}


check4env () {
    if [ ! -d ~/dev/pypi ]; then
      wlog "!? Invalid environment: missing ~/dev/pypi directory!"
      exit 1
    fi
    if [ ! -d ~/dev/_travis ]; then
      wlog "!? Invalid environment: missing ~/dev/_travis directory!"
      exit 1
    fi
    if [ ! -d /opt/odoo/tools ]; then
      mkdir -p /opt/odoo/tools
    fi
    if [ ! -d /opt/odoo/tools/travis_emulator ]; then
      mkdir -p /opt/odoo/tools/travis_emulator
    fi
    if [ ! -d /opt/odoo/7.0 ]; then
      mkdir -p /opt/odoo/7.0
    fi
    if [ ! -d /opt/odoo/8.0 ]; then
      mkdir -p /opt/odoo/8.0
    fi
    if [ ! -d /opt/odoo/7.0/zeroincombenze ]; then
      mkdir -p /opt/odoo/7.0/zeroincombenze
      touch -d $yod-01-01 /opt/odoo/7.0/zeroincombenze/__openerp__.py
    fi
    if [ ! -d /opt/odoo/7.0/zeroincombenze/l10n_it_bbone ]; then
      mkdir -p /opt/odoo/7.0/zeroincombenze/l10n_it_bbone
      touch -d $yod-01-01 /opt/odoo/7.0/zeroincombenze/l10n_it_bbone/__openerp__.py
    fi
    if [ ! -d /opt/odoo/7.0/zeroincombenze/l10n_it_bbone/conf ]; then
      mkdir -p /opt/odoo/7.0/zeroincombenze/l10n_it_bbone/conf
    fi
    if [ ! -d /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal ]; then
      mkdir -p /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal
      touch -d $yod-01-01 /opt/odoo/7.0/zeroincombenze/__openerp__.py
    fi
    if [ ! -d /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data ]; then
      mkdir -p /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data
    fi
    if [ ! -d /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf ]; then
      mkdir -p /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf
    fi
    if [ ! -d /opt/odoo/7.0/openerp/workflow ]; then
      mkdir -p /opt/odoo/7.0/openerp/workflow
    fi
}


cpfiles () {
# cpfiles(srcpath, tgtpath, files, owner)
    if [ -z "$3" ]; then
      local l="*"
    else
      local l="$3"
    fi
    local CWD=$PWD
    local sts=0
    if [ -d $1 ]; then
      cd $1
      for f in $l; do
        if [ -f $1/$f ]; then
          wlog "> cp $1/$f $2/$f"
          (($opt_dry_run))||cp $1/$f $2/$f
          if [ $4 ]; then
            wlog "> chown $4 $2/$f"
            (($opt_dry_run))||chown $4 $2/$f
          fi
        else
          wlog "! File $1/$f not found!!"
          local sts=1
        fi
      done
    else
      wlog "! Directory $1 not found!!"
      local sts=1
    fi
    cd $CWD
    return $sts
}


scpfiles () {
# scpfiles(srcpath, tgtpath, files)
    if [ -z "$3" ]; then
      local l="*"
    else
      local l="$3"
    fi
    local CWD=$PWD
    local sts=0
    if [ -d $1 ]; then
      cd $1
      for f in $l; do
        if [ -f $1/$f ]; then
          wlog "> scp $1/$f $2/$f"
          (($opt_dry_run))||scp $1/$f $2/$f
        else
          wlog "! File $1/$f not found!!"
          local sts=1
        fi
      done
    else
      wlog "! Directory $1 not found!!"
      local sts=1
    fi
    cd $CWD
    return $sts
}


mvfiles () {
# mvfiles(srcpath, tgtpath, files, owner)
    if [ -z "$3" ]; then
      local l="*"
    else
      local l="$3"
    fi
    local CWD=$PWD
    local sts=0
    if [ -d $1 ]; then
      cd $1
      for f in $l; do
        if [ -f $1/$f ]; then
          wlog "> mv $1/$f $2/$f"
          (($opt_dry_run))||mv $1/$f $2/$f
          if [ $4 ]; then
            wlog "> chown $4 $2/$f"
            (($opt_dry_run))||chown $4 $2/$f
          fi
        else
          wlog "! File $1/$f not found!!"
          local sts=1
        fi
      done
    else
      wlog "! Directory $1 not found!!"
      local sts=1
    fi
    cd $CWD
    return $sts
}


generate_svg () {
# generate_svg(id, result, ver?)
    wlog "generate_svg $1[ $2 ] -V$3"
    local sw_id="$1"
    local sw_date=$(date +%d-%m-%Y)
    if [ "$HOSTNAME" == "$PRD_HOST" ]; then
      local color_dev_prd="#004dff"
      tgt="prd"
    elif [ "$HOSTNAME" == "$DEV_HOST" ]; then
      local color_dev_prd="#162832"
      tgt="dev"
    else
      local color_dev_prd="#3b3b3b"
      tgt=""
    fi
    if [ "$2" == "OK" ]; then
      local color_result="#33a600"
    else
      local color_result="#900404"
    fi
    if [ -n "$tgt" ]; then
      cp $SVG_TMPL_DIR/$SVG_TMPL_BTNM ./$sw_id.svg
      for t in sw_id sw_date color_dev_prd color_result;do
        # echo "$t=${!t}"
        sed -i "s:\${$t}:${!t}:g" ./$sw_id.svg
      done
      local d=$(readlink -f ~/dev/svg)
      mvfiles "." "$d" "$sw_id.svg"
    fi
}


$(init_cfg)
$(active_cfg)
a_add "0" "DEV_HOST" "shsdev16"
a_add "0" "PRD_HOST" "shsprd14"
a_add "0" "ME_BOS" "test_nightly .test_nightly.conf.sample"
a_add "0" "MYPKG" "travis_emulator"
link_cfg $FCONF
for p in DEV_HOST MYPKG PRD_HOST SVG_TMPL_DIR SVG_TMPL_BTNM; do
  declare $p=$(get_cfg_value "" "$p")
  if [ -z "${!p}" ]; then
    elog "!? Invalid configuration parameter $p!!"
    exit 1
  fi
done
DEV_DIR=/opt/odoo/dev/pypi/$MYPKG/$MYPKG
for p in ME_BOS PKGSLX; do
  declare $p="$(get_cfg_value "" "$p")"
  declare $p="${!p//,/ }"
done
if [ $opt_8 -gt 0 ]; then
  if [ "$TDIR" != "$tgt" ]; then
    cpfiles "$TDIR" "$tgt" "$ME_BOS"
    sts=$?
  else
    sts=0
  fi
  if [ $sts -eq 0 ]; then
    wlog "Test $__version__ successfully terminated"
  else
    wlog "!?!?!?!? Test $__version__ failed!!!! !?!?!?!?"
  fi
  exit $sts
fi
if [ $opt_test -gt 0 ]; then
  for p in DEV_HOST PRD_HOST SVG_TMPL_DIR SVG_TMPL_BTNM; do
    echo "$p=${!p}"
  done
  echo "Upgrade myself does .."
  for f in $ME_BOS; do
     echo "> cp $TDIR/$f {tgt}/$f"
  done
  echo "Test list .."
  for f in $PKGSLX; do
     echo "> make test # $f"
  done
  exit 0
fi

dom=$(date +%d)
dow=$(date +%w)
yod=$(date +%Y)
dt=$(date +%Y-%m-%d)
if [[ -t 0 || -p /dev/stdin ]]; then
  set_tlog_file "~/$THIS.log" "" "echo"
elif [ $dom -eq 12 ]; then
  set_tlog_file "~/$THIS.log" "new"
else
  set_tlog_file "~/$THIS.log"
fi
sts=0
if [ $opt_cron -gt 0 ]; then
  wlog "Run cron mode"
  if [ $(echo $PATH|grep -v "/dev/" 2>/dev/null) ]; then
    export PATH=$PATH:~/dev
  fi
  if [ $opt_dry_run -eq 0 ]; then
    fqcmd=$(readlink -f $0)
    /bin/bash -lc $fqcmd
    sts=$?
  fi
  exit $sts
fi
(($opt_9))||upgrade_myself
# here if upgrade fails or is not needed

ODOO_LTF=~/testlog/result.log

wlog "********************************************************"
wlog "Test nightly $__version__ starting by $USER"
wlog "********************************************************"
if [ $EUID -eq 0 ]; then
  wlog "> Upgrade z0librc"
  _install_z0librc
  if [ "$HOSTNAME" == "$DEV_HOST" -o "$HOSTNAME" == "$PRD_HOST" ]; then
    valid=0
    if [ "$HOSTNAME" == "$DEV_HOST" -a $dow -eq 3 ]; then
      valid=1
    elif [ "$HOSTNAME" == "$PRD_HOST" -a $dow -eq 4 ]; then
      valid=1
    fi
    if [ $valid -gt 0 -a $opt_dry_run -eq 0 ]; then
      wlog "> yum -y update"
      yum -y update
      vmware-config-tools.pl --default
    fi
    sts=0
    d=$(readlink -f /opt/odoo/dev/svg)
    if [ "$HOSTNAME" == "$PRD_HOST" ]; then
      tgt="prd"
    elif [ "$HOSTNAME" == "$DEV_HOST" ]; then
      tgt="dev"
    else
      tgt=""
    fi
    mvfiles "$d" "/var/www/html/wp-zi/wp-content/uploads/ci-ct/$tgt" "*.svg" "apache:apache"
    s=$?
    [ $sts -eq 0 ]&&sts=$s
    if [ "$HOSTNAME" == "$DEV_HOST" ]; then
       scpfiles "/var/www/html/wp-zi/wp-content/uploads/ci-ct/$tgt" "$PRD_HOST:/var/www/html/wp-zi/wp-content/uploads/ci-ct/$tgt" "*.svg"
      s=$?
      [ $sts -eq 0 ]&&sts=$s
    fi
    if [ "$HOSTNAME" == "$PRD_HOST" ]; then
      cpfiles "/opt/odoo/dev" "/opt/openerp/dev" "beauty clodoo.py cronow dist_pkg Makefile prjdiff test_nightly topep8 travis travisrc" "odoo:ERPs"
      s=$?
      [ $sts -eq 0 ]&&sts=$s
    fi
    cpfiles "/opt/odoo/tools/zar" "/root" "bckconf bckconf.py restconf restconf.py bckwww restwww bckdb bckdb.py restdb restdb.py updzar" "root:root"
    s=$?
    [ $sts -eq 0 ]&&sts=$s
    cpfiles "/opt/odoo/tools/wok_code" "/root" "av_php" "root:root"
    s=$?
    [ $sts -eq 0 ]&&sts=$s
    # cpfiles "/opt/openerp/dev" "/root" "oe_upd_burst" "root:root"
    if [ $opt_dry_run -eq 0 ]; then
      python /opt/odoo/dev/z0testercode.py
      s=$?
      [ $sts -eq 0 ]&&sts=$s
    fi
    if [ $sts -eq 0 ]; then
      opt_odoo="oe_upgrade"
      XX=$(ps -ef|grep "clodoo\.py.*$opt_odoo.conf"|tail -n1)
      if [ -z "$XX" ]; then
        wlog "Begin all DB Odoo burst upgrade (-c $opt_odoo.conf)"
        if [ $opt_dry_run -eq 0 ]; then
          oe_upd_burst "$opt_odoo"
          sts=$?
        fi
        wlog "All DB Odoo burst upgrade ended"
      else
        wlog "*** Odoo burst upgrade is already running ***"
       sts=1
     fi
    fi
  fi
fi
if [ "$USER" == "odoo" ]; then
  (($opt_dry_run))||check4env
  cd ~/dev/pypi
  for pkgname in *; do
    if [ $sts -eq 0 ]; then
      valid=0
      if [ -d "$pkgname" ]; then
        for p in $PKGSLX; do
          if [ "$pkgname" == "$p" ]; then
            valid=1
            break
          fi
        done
        if [ $valid -gt 0 ]; then
          test_pkg_pypi $pkgname
          sts=$?
          if [ $sts -eq 0 ]; then
            pkg_pypi_commit $pkgname
          fi
        else
          wlog "------------------------------------"
          wlog "Module $pkgname uncertificated ($sts)!"
        fi
      fi
    fi
    cd ~/dev/pypi
  done
  # if [ "$HOSTNAME" == "$DEV_HOST" -a $sts -eq 0 ]; then
    # wlog "cd ~/tools"
    # cd ~/tools
    # wlog "> git commit -a -m '[RUN] nightly commit'"
    # git commit -a -m "[RUN] nightly commit" &>>~/$THIS.log
    # wlog "> git push"
    # git push &>>~/$THIS.log
  # fi
  if [ -d /opt/odoo/tools/clodoo ]; then
    cpfiles "/opt/odoo/tools/clodoo" "/opt/odoo/dev" "clodoo.py"
    s=$?
    [ $sts -eq 0 ]&&sts=$s
  fi
  if [ -d /opt/odoo/tools/z0tester ]; then
    cpfiles "/opt/odoo/tools/z0tester" "/opt/odoo/dev" "z0testercode.py"
    s=$?
    [ $sts -eq 0 ]&&sts=$s
  fi
fi
if [ "$USER" == "openerp" ]; then
  if [ $sts -eq 0 ]; then
    cd ~/7.0/clodoo
    (($opt_dry_run))||./makecommit
    opt_odoo="nightly"
    if [ -z "$opt_ncld" -a -f $opt_odoo.conf -a $opt_dry_run -eq 0 ]; then
      echo "Analyzing if process running $opt_odoo.conf"
      XX=$(ps -ef|grep "clodoo\.py.*$[- ]c *opt_odoo\.conf"|tail -n1)
      if [ -z "$XX" ]; then
        wlog "Starting clodoo operations (-c $opt_odoo.conf)"
        oe_upd_burst "$opt_odoo"
        sts=$?
        wlog "All DB Odoo burst upgrade ended"
      else
        wlog "*** Odoo burst upgrade is already running ***"
        sts=1
      fi
    fi
    if [ $sts -eq 0 -a -z "$opt_nall" ]; then
      wlog "Odoo all tests"
      if [ $opt_dry_run -eq 0 ]; then
        /opt/odoo/dev/pypi/clodoo/clodoo/odoo_test -Aaqy test
        if [ -n "$(grep \"$dt\" $ODOO_LTF|grep FAIL)" ]; then
          sts=1
          grep "$dt" $ODOO_LTF|grep FAIL
        fi
      fi
    fi
  fi
fi
if [ $opt_9 -gt 0 ]; then
  sts=0
fi
if [ $sts -eq 0 ]; then
  wlog "Test $__version__ successfully terminated"
else
  wlog "!?!?!?!? Test $__version__ failed!!!! !?!?!?!?"
fi
exit $sts
