#! /bin/bash
# Update source python file to pep8 standard
# Tool for internal use
#
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com

THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi

__version__="0.1.12"


FCONF=$TDIR/.$THIS.conf

# main
OPTOPTS=(h        d        n            o       q           u       V           v)
OPTDEST=(opt_help opt_diff opt_dry_run  opt_out opt_verbose opt_uop opt_version opt_verbose)
OPTACTI=(1        1        1            "="     0           1       "*>"        "+")
OPTDEFL=(1        0        0            ""      -1          0       ""          -1)
OPTMETA=("help"   "diff"   "do nothing" "file"  "silent"   "uop"   "version"    "verbose")
OPTHELP=("this help"\
 "show diff"\
 "do nothing (dry-run)"\
 "output filename, leave source unchanged (def source becomes .bak)"\
 "silent mode"\
 "check for unary operator W503"\
 "show version"\
 "verbose mode")
OPTARGS=(pathname basename)

parseoptargs "$@"
if [ "$opt_version" ]; then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]; then
  print_help "PEP8 source python file\nfull path name maybe supplied as a single parameter\nor with two separated values (dir + basename)"\
  "(C) 2015-2017 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
if [ -d "$pathname" ]; then
  path=$(readlink -f $pathname)
  if [ -z "$basename" ]; then
    selfl="*.py"
  else
    selfl="$basename"
  fi
else
  path=$(dirname $pathname)
  path=$(readlink -f $path)
  selfl=$(basename $pathname)
fi
sts=1
HOMEDIR=$PWD
for fl in $(find $path -type f -name "$selfl"); do
  sts=0
  p=$(dirname $fl)
  f=$(basename $fl)
  if [ $opt_verbose -gt 0 ]; then
    echo "Reading $f in $p"
  fi
  cd $p
  autopep8 $f|sed 's/ $/\n/'>$f.new
  if [ $opt_uop -gt 0 ]; then
    python $TDIR/autopep8_W503.py $f.new
  fi
  d=$(diff -q $f $f.new)
  if [ -z "$d" ]; then
    rm -f $f.new
  else
    if [ $opt_dry_run -eq 0 ]; then
      if [ -n "$opt_out" ]; then
        mv $f.new $opt_out
        if [ $opt_diff -gt 0 ]; then
          diff $f $opt_out
        fi
      else
        cp -p $f $f.bak
        mv $f.new $f
        if [ $opt_diff -gt 0 ]; then
          diff $f.bak $f
        fi
      fi
      if [ $opt_verbose -gt 0 ]; then
        echo "File $f in $p converted"
      fi
    else
      if [ $opt_diff -gt 0 ]; then
        diff $f $f.new
      fi
      rm -f $f.new
      if [ $opt_verbose -gt 0 ]; then
        echo "File $f in $p should be converted"
      fi
    fi
  fi
done
cd $HOMEDIR
if [ $opt_verbose -gt 0 -a $sts -gt 0 ]; then
  echo "No file found!"
fi
exit $sts
