#! /bin/bash
# -*- coding: utf-8 -*-
# Version file diff
# Make diff of file among Odoo versions
#
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
# This free software is released under GNU Affero GPL3

if [ -f z0librc ]; then
. ./z0librc
elif [ -f ~/z0librc ]; then
. ~/z0librc
elif [ -f /etc/z0librc ]; then
. /etc/z0librc
else
  echo "Libreria z0librc non trovata!"
  exit 1
fi

__version__="0.1.3"

get_cur_ver () {
  local i=
  local v=
  for i in {2..4}; do
    local t=$(echo "$PWD"|awk -F/ '{ print $'$i'}')
    if [ -z "$t" ]; then
      break
    elif [ "$t" == "7.0" -o "$t" == "8.0" -o "$t" == "9.0" ]; then
      local v=$t
      break
    elif [ "$t" == "v7" ]; then
      local v=7.0
      break
    fi
  done
  echo "$v"
}

get_path_ver () {
  local p=
  local i=
  for i in {2..9}; do
    local t=$(echo "$PWD"|awk -F/ '{ print $'$i'}')
    if [ -z "$t" ]; then
      break
    elif [ "$t" == "7.0" -o "$t" == "8.0" -o "$t" == "9.0" -o "$t" == "v7" ]; then
      p="$p/$1"
    elif [ "$t" == "zeroincombenze" ]; then
      if [ "$1" == "7.0" -o "$1" == "8.0" -o "$1" == "9.0" ]; then
        p="$p/l10n-italy-supplemental"
      else
        p="$p/$t"
      fi
    elif [ "$t" == "l10n-italy-supplemental" ]; then
      if [ "$1" == "v7" ]; then
        p="$p/zeroincombenze"
      else
        p="$p/$t"
      fi
    else
      p="$p/$t"
    fi
  done
  echo "$p"
}

OPTOPTS=(h        n            O         V           v)
OPTDEST=(opt_help opt_dry_run  odoo_ver  opt_version opt_verbose)
OPTACTI=(1        "1"          "="       "*>"        1)
OPTDEFL=(0        0            ""        ""          0)
OPTMETA=("help"   "do nothing" "version" "version"   "verbose")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "select a Odoo version (may be 7, 8 or 9)"\
 "show version"\
 "verbose mode")
OPTARGS=(filename)

parseoptargs "$@"
if [ "$opt_version" ]; then
  echo "$__version__"
  exit 0
fi
if [ -z "$odoo_ver" -a -z "$filename" ]; then
  opt_help=1
fi
if [ $opt_help -gt 0 ]; then
  print_help "Diff file among Odoo versions"\
  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Odoo/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi
# set -x
if [ "$odoo_ver" == "7" -o "$odoo_ver" == "8" -o "$odoo_ver" == "9" ]; then
  odoo_ver="$odoo_ver.0"
fi
cv=$(get_cur_ver)
if [ -z "$filename" ]; then
  filenames=./
  filenamet=
else
  filenames=$filename
  filenamet=$filename
fi
a=$(find $filenames -type d|grep "\./")
if [ -n "$a" ]; then
  opts="-x*.pyc -x*.po* -x*.bak -x*~ -qr"
else
  opts=
fi
if [ -n "$odoo_ver" ]; then
  tgt=$(get_path_ver "$odoo_ver")
  if [ $opt_verbose -gt 0 ]; then
    echo "diff $opts $filenames $tgt/$filenamet"
  fi
  diff $opts $filenames $tgt/$filenamet
else
  tgt1=
  tgt2=
  for v in 7.0 8.0 9.0; do
    if [ "$v" != "$cv" ]; then
      if [ -z "$tgt1" ]; then
        tgt1=$(get_path_ver "$v")
      else
        tgt2=$(get_path_ver "$v")
      fi
    fi
  done
  if [ $opt_verbose -gt 0 ]; then
    echo "diff3 $filename $tgt1/$filename $tgt2/$filename"
  fi
  diff3 $filename $tgt1/$filename $tgt2/$filename
fi
