#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests for zar module
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=./
  RUNDIR=../
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=./
elif [ -d ../_travis ]; then
  TRAVISDIR=../
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -e ./z0librc ]; then
. ./z0librc
elif [ -e ../z0librc ]; then
. ../z0librc
elif [ -e ~/z0librc ]; then
. ~/z0librc
else
. /etc/z0librc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
elif [ -e ./z0testrc ]; then
. ./z0testrc
elif [ -e ../z0testrc ]; then
. ../z0testrc
else
. ~/dev/z0testrc
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)
TESTLOGNAME=test_zar.log

__version__=0.1.1

declare -a ctrs
export WNoCtr=1
parseoptest -l$TESTDIR/$TESTLOGNAME $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
opt4childs=$(inherit_opts)
UT_LIST=""
saved_ctr=$ctr
saved_max_test=$max_test
saved_opt_verbose=$opt_verbose
saved_opt_dry_run=$opt_dry_run
saved_LNEW=$LNEW
saved_LECHO=$LECHO

ix=0
sts=0
WLOGCMD=echo
FLOG=
# pass 1: count for # of tests
max_test=0
exec_tests_4_count "$UT_LIST"
if [ ${saved_max_test:-0} -gt 0 ]; then
  max_test=$saved_max_test
elif [ ${opt_noctr:-0} -gt 0 ]; then
  max_test=
fi
# pass 2: execute tests
ctr=$saved_ctr
opt_verbose=$saved_opt_verbose
opt_dry_run=$saved_opt_dry_run
LNEW=$saved_LNEW
LECHO=$saved_LECHO
# if [ "$LECHO" == "echo" ]; then
#   WLOGCMD="wecho-1"
# else
#   WLOGCMD="wecho-0"
# fi
WLOGCMD=
FLOG=
set_tlog_file "$TESTDIR/$TESTLOGNAME" "" "$LECHO"
if [ ${opt_noctr:-0} -eq 0 -a ${ctr:-0} -gt 0 -a ${saved_max_test:-0} -eq 0 ]; then
   let max_test="$max_test"+"$ctr"
fi
if [ ${opt_dry_run:-0} -eq 0 ]; then
  ix=0
  sts=0
  ctr=$saved_ctr
  exec_all_tests "$UT_LIST"
  if [ $sts -eq 0 ]; then
    echo "Test successfully terminated"
  else
    echo "Test failed!"
  fi
else
  echo "$max_test"
fi
exit $sts
