#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on zar
#
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/zerobug $HOME/dev" "zerobug")
if [ -z "$Z0TLIBDIR" ]; then
  echo "Library file z0testrc not found!"
  exit 2
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=1.3.33.5


test_01() {
    local RES TRES
    if [ -f $OUTF ]; then
      RES=$OUTF
    else
      RES=
    fi
    test_result "zar_bck -T (found log)" "$OUTF" "$RES"
    return $?
}

test_02() {
    local RES TRES
    if [ -f $OUTF ]; then
      grep "DB test is backup copy" $OUTF  &>/dev/null
      RES=$?
    else
      RES=1
    fi
    test_result "zar_bck -T (backup copy ignored)" "0" "$RES"
    return $?
}

test_03() {
    local RES TRES
    if [ -f $OUTF ]; then
      grep "DB invalid is not classified" $OUTF  &>/dev/null
      RES=$?
    else
      RES=1
    fi
    test_result "zar_bck -T (db not classified)" "0" "$RES"
    return $?
}

test_04() {
    local db RES TRES
    for db in zi01234567 zi01234589; do
      if [ -f $OUTF ]; then
        grep "pg_dump .*/$db.*\.sql .*$db" $OUTF  &>/dev/null
        RES=$?
      else
        RES=1
      fi
      test_result "zar_bck -T (log) # $db" "0" "$RES"
    done
    return $?
}

test_05() {
    local dtc RES TRES
    dtc=$(date +%Y%m%d)
    for db in zi01234567 zi01234589; do
      [ -f $TESTDIR/res/backups/${db}-$dtc.sql ] && RES=0 || RES=1
      test_result "zar_bck -T (found ${db}-$dtc.sql)" "0" "$RES"
    done
    return $?
}

Z0BUG_setup() {
    Z0BUG_build_os_tree "backups"
    rm -f $TESTDIR/bckdb.log
    rm -f $TESTDIR/res/backups/*.sql
    local CONFN=$TESTDIR/zar.conf
    cat <<EOF >$CONFN
DBA_filter=zi0123
DBA_keep_recent=7
DBA_keep_monthly=3
production_host=$HOSTNAME
development_host=${HOSTNAME//s/z}-DEV
bck_db=yesterday
PRD_num_days_before=0
EOF
    local cmd="$RUNDIR/zar_bck -T"
    OUTF=$TESTDIR/bckdb.log
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      OUT=$(eval $cmd)
    else
      OUT=
      rm -f $OUTF
    fi
}


Z0BUG_teardown() {
    [ ${opt_dry_run:-0} -eq 0 ] && Z0BUG_remove_os_tree "backups"
}


Z0BUG_build_os_tree() {
    local p path os_tree root
    os_tree="${1//,/ }"
    root=$TESTDIR/res
    [ ! -d "$root" ] && mkdir -p $root
    for p in $os_tree; do
      [[ ${p:0} =~ [./] ]] && path=$p || path=$root/$p
      [ ! -d $path ] && mkdir -p $path
    done
}

Z0BUG_remove_os_tree() {
    local p path os_tree root
    os_tree="${1//,/ }"
    root=$TESTDIR/res
    [ ! -d "$root" ] && return
    for p in $os_tree; do
      [[ ${p:0} =~ [./] ]] && path=$p || path=$root/$p
      [ ! -d $path ] && continue
      rm -fR $path
    done
}

Z0BUG_init
parseoptest -l$TESTDIR/test_zar.log "$@" "-Z"
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
if [ $opt_zLib -ne 0 ]; then
  ZARLIB=$(findpkg zarrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/zar $HOME/dev")
  if [ -z "$ZARLIB" ]; then
    echo "Library file zarrc not found!"
    exit 2
  fi
  . $ZARLIB
fi

UT1_LIST=""
UT_LIST=""
if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
exit $sts
