#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on zar
#
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/zerobug $HOME/dev" "zerobug")
if [ -z "$Z0TLIBDIR" ]; then
  echo "Library file z0testrc not found!"
  exit 2
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=1.3.31.3


test_01() {
    local RES TRES
    if [ -f $OUTF ]; then
      RES=$OUTF
    else
      RES=
    fi
    test_result "rest test log" "$OUTF" "$RES"
    return $?
}

test_02() {
    local RES TRES
    if [ -f $OUTF ]; then
      grep "DB to Restore: zi01234567" $OUTF  &>/dev/null
      RES=$?
    else
      RES=1
    fi
    test_result "rest list" "0" "$RES"
    return $?
}

test_03() {
    local RES TRES
    if [ -f $OUTF ]; then
      local dtc=$(date +%Y%m%d)
      grep -q "File .*/zi01234567-$dtc.sql .* zi01234567" <<< $OUT &>/dev/null
      RES=$?
    else
      RES=1
    fi
    test_result "restore into" "0" "$RES"
    return $?
}

Z0BUG_setup() {
    rm -f $TESTDIR/restdb.log
    rm -f $TESTDIR/backups/*.sql
    local tod=$(date +%Y%m%d)
    touch $TESTDIR/backups/zi01234567-$tod.sql
    touch $TESTDIR/backups/zi01234567.err
    local CONFN=$TESTDIR/zar.conf
    cat <<EOF >$CONFN
DBA_filter=zi01234567
DBA_keep_recent=7
DBA_keep_monthly=3
development_host=$HOSTNAME
production_host=${HOSTNAME//s/z}-DEV
bck_db=yesterday
PRD_num_days_before=0
EOF
    local cmd="$RUNDIR/zar_rest -T zi01234567"
    OUTF=$TESTDIR/restdb.log
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      OUT=$(eval $cmd)
    else
      OUT=
      rm -f $OUTF
    fi
}


Z0BUG_teardown() {
    :
}


Z0BUG_init
parseoptest -l$TESTDIR/test_zar.log "$@" "-Z"
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
if [ $opt_zLib -ne 0 ]; then
  ZARLIB=$(findpkg zarrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/zar $HOME/dev")
  if [ -z "$ZARLIB" ]; then
    echo "Library file zarrc not found!"
    exit 2
  fi
  . $ZARLIB
fi



UT1_LIST=""
UT_LIST=""
if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
exit $sts
