#! /bin/bash
# -*- coding: utf-8 -*-
#
# Simulate or install packges to run travis emulator
#
# This free software is released under GNU Affero GPL3
# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
# (C) 2015 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -f $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -f ./z0librc ]; then
. ./z0librc
elif [ -f ~/z0librc ]; then
. ~/z0librc
else
. /etc/z0librc
fi
TCONF=$TDIR/.$THIS.conf

__version__=0.1.1


run_traced () {
    # set -x  #debug
    if [ $opt_verbose -gt 0 ]; then
      echo "$@"
    fi
    if [ $opt_dry_run -eq 0 ]; then
      $@
    fi
    # et +x  #debug
}


OPTOPTS=(h        n            V           v)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose)
OPTACTI=(1        "1>"         "*>"        1)
OPTDEFL=(1        0            ""          0)
OPTMETA=("help"   "do nothing" "version"   "verbose")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode")
OPTARGS=(PKGPATH PRJNAME)
parseoptargs $@

if [ "$opt_version" ]; then
  echo "$__version__"
  exit 0
fi
if [ $opt_help -gt 0 ]; then
  print_help "Install packages to run travis emulator"\
  "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit 0
fi

if [ ! -d $PKGPATH ]; then
  echo "Invalid path $PKGPATH"
  exit 1
elif [ "$PRJNAME" != "Odoo" ]; then
  if [ ! -d $PKGPATH/$pkgname ]; then
    echo "Invalid path $PKGPATH/$pkgname"
    exit 1
  fi
fi
if [ "$PRJNAME" == "Odoo" ]; then
  run_traced dropdb  openerp_template 2>/dev/null||true
fi
exit 0