#! /bin/bash
# -*- coding: utf-8 -*-

if [ -f ./z0librc ]; then
. ./z0librc
  FINAL=./optargs
  TESTDIR=./tests
  OK=$(_install_z0librc "-n")
elif [ -f ../z0librc ]; then
. ../z0librc
  FINAL=../optargs
  TESTDIR=.
  CWD=$PWD
  cd ..
  OK=$(_install_z0librc "-n")
  cd $CWD
fi
if [ "$OK" != "cp ./z0librc /etc/z0librc" ]; then
  echo "Invalid library to test!!!"
  exit 1
fi


export ctr=0
$TESTDIR/test_wlog
sts=$?
# Test log file successfully ended; set log file to next tests
set_tlog_file "$TESTDIR/test_z0librc.log" "" "echo"
if [ $sts -eq 0 ]; then
  $TESTDIR/test_findpkg
  sts=$?
fi
if [ $sts -eq 0 ]; then
  $TESTDIR/test_parseoptargs
  sts=$?
fi
if [ $sts -eq 0 ]; then
  $TESTDIR/test_dict
  sts=$?
fi
if [ $sts -eq 0 ]; then
  $TESTDIR/test_cfg
  sts=$?
fi
if [ $sts -eq 0 ]; then
  echo "Test successfully terminated"
else
  echo "Test failed!"
fi
exit $sts
