#!/bin/bash
# -*- coding: utf-8 -*-
# Regression tests on z0lib
#
READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
export READLINK
THIS=$(basename "$0")
TDIR=$($READLINK -f $(dirname $0))
[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
PYPATH=$(echo -e "import os,sys\np=[x for x in (os.environ['PATH']+':$TDIR:..:$HOME_DEV').split(':') if x not in sys.path];p.extend(sys.path);print(' '.join(p))"|python)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
for d in $PYPATH /etc; do
  if [[ -e $d/z0librc ]]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
    break
  fi
done
if [[ -z "$Z0LIBDIR" ]]; then
  echo "Library file z0librc not found!"
  exit 72
fi
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
RUNDIR=$($READLINK -e $TESTDIR/..)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
if [[ -z "$Z0TLIBDIR" ]]; then
  echo "Library file z0testrc not found!"
  exit 72
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"

__version__=1.0.1.2


test_01() {
    eval $(init_cfg)
    eval $(active_cfg)
    FCONF="$TESTDIR/test.conf"
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $FCONF ]; then rm -f $FCONF; fi
      if [ -f $FCONF.sample ]; then rm -f $FCONF.sample; fi
      link_cfg $FCONF
      set_cfg_def "param1" "Value1"
      set_cfg_def "param2" "Value2"
      set_cfg_def "param3" "Value3"
      set_cfg_def "param4" "Value4"
    fi
    for i in 1 2 3 4; do
      TRES=$(get_cfg_value "" "param$i")
      test_result "find param$i" "Value$i" "$TRES"
    done

    if [ ${opt_dry_run:-0} -eq 0 ]; then
      echo "param1= VALUE1 ">$FCONF
      echo "param3=VALUE3">>$FCONF
      link_cfg $FCONF
    fi
    for i in 1 2 3 4; do
      TRES=$(get_cfg_value "" "param$i")
      if [ $i -eq 1 ]; then
        test_result "find param$i" "VALUE$i" "$TRES"
      elif [ $i -eq 3 ]; then
        test_result "find param$i" "VALUE$i" "$TRES"
      else
        test_result "find param$i" "Value$i" "$TRES"
      fi
    done
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      echo "param4=\" VALUE4 \"">>$FCONF
      link_cfg $FCONF
    fi
    TRES=$(get_cfg_value "" "param4")
    test_result "find param4" " VALUE4 " "$TRES"

    eval $(init_cfg)
    eval $(active_cfg)
    FCONF="$TESTDIR/test.conf"
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $FCONF ]; then rm -f $FCONF; fi
      echo "#param1=NOVALUE ">$FCONF.sample
      echo "param1= value1 ">>$FCONF.sample
      echo "param2=\"value2\"">>$FCONF.sample
      echo "param3=value3">>$FCONF.sample
      echo "param4= \"value4\" ">>$FCONF.sample
      link_cfg $FCONF
    fi
    for i in 1 2 3 4; do
      TRES=$(get_cfg_value "" "param$i")
      test_result "find param$i" "value$i" "$TRES"
    done
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      echo "param1= VALUE1 ">$FCONF
      echo "param3=VALUE3">>$FCONF
      link_cfg $FCONF
    fi
    for i in 1 2 3 4; do
      TRES=$(get_cfg_value "" "param$i")
      if [ $i -eq 1 ]; then
        test_result "find param$i" "VALUE$i" "$TRES"
      elif [ $i -eq 3 ]; then
        test_result "find param$i" "VALUE$i" "$TRES"
      else
        test_result "find param$i" "value$i" "$TRES"
      fi
    done

    eval $(init_cfg)
    eval $(active_cfg)
    FCONF="$TESTDIR/test.conf"
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $FCONF ]; then rm -f $FCONF; fi
      set_cfg_def "param1" "defval1"
      set_cfg_def "param2" "defval2"
      set_cfg_def "param3" "defval3"
      set_cfg_def "param4" "defval4"
      echo "#param1=NOVALUE ">$FCONF.sample
      echo "param2=\"value2\"">>$FCONF.sample
      echo "param3=value3">>$FCONF.sample
      echo "param3= VALUE3 ">$FCONF
      echo "param4=None ">>$FCONF
      echo "param9=Long long \\">>$FCONF
      echo "       value \\">>$FCONF
      echo "       parameter">>$FCONF
      link_cfg $FCONF $FCONF.sample
    fi
    TRES=$(get_cfg_value "" "param1")
    test_result "find param1" "defval1" "$TRES"
    TRES=$(get_cfg_value "" "param2")
    test_result "find param2" "value2" "$TRES"
    TRES=$(get_cfg_value "" "param3")
    test_result "find param3" "VALUE3" "$TRES"
    TRES=$(get_cfg_value "" "param4")
    test_result "find param4" "" "$TRES"
    TRES=$(get_cfg_value "" "param9")
    test_result "find param9" "Long long value parameter" "$TRES"

    eval $(init_cfg)
    eval $(active_cfg)
    FCONF="$TESTDIR/test.conf"
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $FCONF ]; then rm -f $FCONF; fi
      echo "#">$FCONF.sample
      echo "param1=Invalid">$FCONF
      local FH=$(xuname "-f")
      echo "[_${FH}_]">>$FCONF
      echo "param1=Right">>$FCONF
      if [ "$FH" == "RHEL" ]; then
        echo "[_Debian_]">>$FCONF
      else
        echo "[_RHEL_]">>$FCONF
      fi
      echo "param1=Wrong">>$FCONF
      link_cfg $FCONF
    fi
    TRES=$(get_cfg_value "" "param1")
    test_result "find param1 OS" "Right" "$TRES"
}


Z0BUG_init
parseoptest -l$TESTDIR/test_UNKNOWN.log "$@"
sts=$?
[[ $sts -ne 127 ]] && exit $sts



UT1_LIST=
UT_LIST=
[[ "$(type -t Z0BUG_setup)" == "function" ]] && Z0BUG_setup
# Follow code must be executed at main level due bash limitations
eval $(init_cfg)
eval $(active_cfg)
# /End Included Block/
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
[[ "$(type -t Z0BUG_teardown)" == "function" ]] && Z0BUG_teardown
exit $sts
