#!/bin/bash
# -*- coding: utf-8 -*-
# Regression tests on z0lib
#
READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
export READLINK
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
for d in $PYPATH /etc; do
  if [[ -e $d/z0librc ]]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [[ -z "$Z0LIBDIR" ]]; then
  echo "Library file z0librc not found!"
  exit 72
fi
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
RUNDIR=$(readlink -e $TESTDIR/..)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
RED="\e[1;31m"
GREEN="\e[1;32m"
CLR="\e[0m"
Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
if [[ -z "$Z0TLIBDIR" ]]; then
  echo "Library file z0testrc not found!"
  exit 72
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"

__version__=1.0.2


PASSED=0

store_cfg_param_value() {
#store_cfg_param_value(tid key value [-f|-d] [-D|1] [section] )
    if [ ${5:-0} -gt 0 -o "$5" == "-D" ] ; then
      PASSED=2
    else
      PASSED=1
    fi
    CFG_set "$1" "$2" "$3" "$4" "$6"
}

test_01() {
    for tid in 0 1 2 3; do
      CFG_init $tid
      FCONF="$TESTDIR/test.conf"
      if [ ${opt_dry_run:-0} -eq 0 ]; then
        link_cfg $FCONF "" $tid
      fi
      TRES=$(get_cfg_value $tid "param1")
      test_result "find param1 OS ($tid)" "Right" "$TRES"
      test_result "param managed" "1" "$PASSED"
      PASSED=0
      TRES=$(get_cfg_value $tid "param2")
      test_result "find param2 OS ($tid)" "NoDebug" "$TRES"
    done
}

test_02() {
    for tid in 0; do
      CFG_init $tid
      FCONF="$TESTDIR/test.conf"
      if [ ${opt_dry_run:-0} -eq 0 ]; then
        link_cfg $FCONF "" $tid "" "1"
      fi
      TRES=$(get_cfg_value $tid "param1")
      test_result "find param1 OS ($tid)" "Right" "$TRES"
      TRES=$(get_cfg_value $tid "param2")
      test_result "find param2 OS ($tid)" "Debug" "$TRES"
      test_result "param managed" "2" "$PASSED"
      PASSED=0
    done
    for tid in 0; do
      CFG_init $tid
      FCONF="$TESTDIR/test.conf"
      if [ ${opt_dry_run:-0} -eq 0 ]; then
        link_cfg $FCONF "" $tid "" "-D"
      fi
      TRES=$(get_cfg_value $tid "param1")
      test_result "find param1 OS ($tid)" "Right" "$TRES"
      TRES=$(get_cfg_value $tid "param2")
      test_result "find param2 OS ($tid)" "Debug" "$TRES"
      test_result "param managed" "2" "$PASSED"
      PASSED=0
    done
}

Z0BUG_setup() {
    FCONF="$TESTDIR/test.conf"
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      if [ -f $FCONF ]; then rm -f $FCONF; fi
      echo "#">$FCONF.sample
      echo "param1=Invalid">>$FCONF
      local FH=$(xuname "-f")
      local x=$(xuname "-v")
      local v=$(echo $x|awk -F. '{print $1}')
      local DISTO=$(xuname "-d")$v
      echo "">>$FCONF
      echo "[_${DISTO}_]">>$FCONF
      echo "param1=Right">>$FCONF
      echo "param2=NoDebug">>$FCONF
      echo "[_${DISTO}_DEV_]">>$FCONF
      echo "param2=Debug">>$FCONF
      echo "">>$FCONF
      if [ "$DISTO" == "CentOS7" ]; then
        echo "[_Ubuntu14_]">>$FCONF
      else
        echo "[_CentOS7_]">>$FCONF
      fi
      echo "param1=Wrong">>$FCONF
      echo "param2=WrongDebug">>$FCONF
    fi
}


Z0BUG_init
parseoptest -l$TESTDIR/test_z0lib.log "$@"
sts=$?
[[ $sts -ne 127 ]] && exit $sts




UT1_LIST=
UT_LIST=
[[ "$(type -t Z0BUG_setup)" == "function" ]] && Z0BUG_setup
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
[[ "$(type -t Z0BUG_teardown)" == "function" ]] && Z0BUG_teardown
exit $sts
