#! /bin/bash
# -*- coding: utf-8 -*-
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
if [ -d $TDIR/tests ]; then
  TESTDIR=$TDIR/tests
  RUNDIR=$TDIR
elif [ -d $TDIR/../tests ]; then
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
elif [ -d ./tests ]; then
  TESTDIR=./tests
  RUNDIR=./
elif [ -d ../tests ]; then
  TESTDIR=./
  RUNDIR=../
else
  TESTDIR=$TDIR
  RUNDIR=$TDIR/..
fi
if [ -d $TDIR/_travis ]; then
  TRAVISDIR=$TDIR
elif [ -d $TDIR/../_travis ]; then
  TRAVISDIR=$TDIR/..
elif [ -d ./_travis ]; then
  TRAVISDIR=./
elif [ -d ../_travis ]; then
  TRAVISDIR=../
else
  TRAVISDIR=~/dev/_travis
fi
if [ -e $TDIR/z0librc ]; then
. $TDIR/z0librc
elif [ -e ./z0librc ]; then
. ./z0librc
elif [ -e ../z0librc ]; then
. ../z0librc
elif [ -e ~/z0librc ]; then
. ~/z0librc
else
. /etc/z0librc
fi
if [ -e $TDIR/z0testrc ]; then
. $TDIR/z0testrc
elif [ -e ./z0testrc ]; then
. ./z0testrc
elif [ -e ../z0testrc ]; then
. ../z0testrc
else
. ~/dev/z0testrc
fi
TESTDIR=$(readlink -e $TESTDIR)
RUNDIR=$(readlink -e $RUNDIR)
TRAVISDIR=$(readlink -e $TRAVISDIR)

__version__=0.1.23
parseoptest -l$TESTDIR/test_z0librc.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
sts=0
# This test could fail because opt_dry_run is parsed by test
# So opt_dry_run is saved and restored
saved_opt_dry_run=$opt_dry_run

FOUT=$TESTDIR/z0librc.out
FTEST=$TESTDIR/z0librc.test

OPTOPTS=(h        n            V           v)
OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose)
OPTACTI=(1        "1>"         "*>"        1)
OPTDEFL=(1        0            ""          0)
OPTMETA=("help"   "do nothing" "version"   "verbose")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "verbose mode")
OPTARGS=()

parseoptargs "-V"
tested_opt_dry_run=$opt_dry_run
opt_dry_run=$saved_opt_dry_run
ci-test "cmd -h" "$opt_help" "0"
ci-test "cmd -V" "$opt_version" "-V"
ci-test "cmd -n" "$tested_opt_dry_run" "0"
ci-test "cmd -v" "$opt_verbose" "0"
echo "Usage: test_parseoptargs [-hnVv]">$FTEST
echo "Unit test">>$FTEST
echo " -h             this help">>$FTEST
echo " -n             do nothing (dry-run)">>$FTEST
echo " -V             show version">>$FTEST
echo " -v             verbose mode">>$FTEST
print_help "Unit test"\
  "">$FOUT
ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"

OPTOPTS=(h        n            V           p)
OPTDEST=(opt_help opt_dry_run  opt_version opt_path)
OPTACTI=(1        "1>"         "*>"        "=>")
OPTDEFL=(1        0            ""          "~/")
OPTMETA=("help"   "do nothing" "version"   "path")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "show version"\
 "path")
OPTARGS=(tgt)

parseoptargs "mytarget"
tested_opt_dry_run=$opt_dry_run
opt_dry_run=$saved_opt_dry_run
ci-test "cmd -h mytarget" "$opt_help" "0"
ci-test "cmd -V mytarget" "$opt_version" ""
ci-test "cmd -n mytarget" "$tested_opt_dry_run" "0"
ci-test "cmd -v mytarget" "$opt_path" "~/"
echo "Usage: test_parseoptargs [-hnV][-p path] tgt">$FTEST
echo "Unit test">>$FTEST
echo " -h             this help">>$FTEST
echo " -n             do nothing (dry-run)">>$FTEST
echo " -V             show version">>$FTEST
echo " -p path        path">>$FTEST
print_help "Unit test"\
  "">$FOUT
ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"

parseoptargs "-p" "./mypath" "yourtarget"
tested_opt_dry_run=$opt_dry_run
opt_dry_run=$saved_opt_dry_run
ci-test "cmd -h ./mypath yourtarget" "$opt_help" "0"
ci-test "cmd -V ./mypath yourtarget" "$opt_version" ""
ci-test "cmd -n ./mypath yourtarget" "$tested_opt_dry_run" "0"
ci-test "cmd -v ./mypath yourtarget" "$opt_path" "./mypath"
ci-test "cmd -v ./mypath yourtarget" "$tgt" "yourtarget"
echo "Usage: test_parseoptargs [-hnV][-p path] tgt">$FTEST
echo "Unit test">>$FTEST
echo " -h             this help">>$FTEST
echo " -n             do nothing (dry-run)">>$FTEST
echo " -V             show version">>$FTEST
echo " -p path        path">>$FTEST
print_help "Unit test"\
  "">$FOUT
ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"


OPTOPTS=(h        n            O       p        V)
OPTDEST=(opt_help opt_dry_run  opt_own opt_path opt_version)
OPTACTI=(1        "1>"         "="     "=>"     "*>")
OPTDEFL=(1        0            "$USER" "~/"     "")
OPTMETA=("help"   "do nothing" "own"   "path"   "version")
OPTHELP=("this help"\
 "do nothing (dry-run)"\
 "owner username"\
 "path"\
 "show version")
OPTARGS=(tgt)

parseoptargs "mytarget"
tested_opt_dry_run=$opt_dry_run
opt_dry_run=$saved_opt_dry_run
ci-test "cmd -h mytarget" "$opt_help" "0"
ci-test "cmd -V mytarget" "$opt_version" ""
ci-test "cmd -n mytarget" "$tested_opt_dry_run" "0"
ci-test "cmd -v mytarget" "$opt_path" "~/"
ci-test "cmd -v mytarget" "$opt_own" "$USER"
ci-test "cmd -v mytarget" "$tgt" "mytarget"
echo "Usage: test_parseoptargs [-hn][-O own][-p path][-V] tgt">$FTEST
echo "Unit test">>$FTEST
echo " -h             this help">>$FTEST
echo " -n             do nothing (dry-run)">>$FTEST
echo " -O own owner username">>$FTEST
echo " -p path        path">>$FTEST
echo " -V             show version">>$FTEST
print_help "Unit test"\
  "">$FOUT
ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"

if [ -f $FOUT ]; then rm -f $FOUT; fi
if [ -f $FTEST ]; then rm -f $FTEST; fi

if [ ${opt_dry_run:-0} -ne 0 ]; then
  echo "$ctr"
fi
exit $sts
