# This configuration is always loaded for all .py files
# Some rules may be processed just in pass1 (before file update)
#
0_import_future:
  match: 'from __future__ import '
  ctx: 'pass1'
  prio: '1'
  do:
    - action: '+'
      args:
      - python_future
0_import_past:
  match: 'from past.builtins import '
  ctx: 'pass1'
  prio: '1'
  do:
    - action: '+'
      args:
      - python_future
no_parse_file:
  match: '.*/(testenv.py|conf.py|_check4deps_.py)'
  ctx: 'pass1 and first_line'
  prio: '1'
  do:
    - action: '+'
      args:
        - 'file_action'
        - 'no'
0_match_ignore_line:
  match: '^#!'
  ctx: 'first_line'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_ignore_line
0_update_coding_utf8:
  match: '^# -\*- *encoding[:=] utf-8 -\*-'
  prio: '1'
  do:
    - action: 's'
      args:
        - '^# -\*- encoding[:=] utf-8 -\*-'
        - '^# -*- coding: utf-8 -*-'
1_match_end_utf8:
  match: '$'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_end_utf8
2_match_utf8:
  match: '^# -\*- coding[:=] utf-8 -\*-'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_utf8
4_match_lint:
  match: '^# (flake8|pylint):'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_lint
5_match_end_utf8:
  match: '!(coding|flake8|pylint|python|/bin/env)^#'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_end_utf8
6_match_end_utf8:
  match: '^[^#]'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_end_utf8
match_class:
  match: '^ *class *([^(]+)\('
  prio: '9'
  do:
    - action: '+'
      args:
      - classname
