# This configuration is always loaded for manifest files
# In Odoo project, manifest is __manifest__.py, in pypi projects manifest is setup.py
#
include_globals_python:
  include: 'globals_python'
include_globals_py2:
  ctx: 'py23==2'
  include: 'globals_py2'
include_globals_py3:
  ctx: 'py23==3'
  include: 'globals_py3'
