# This configuration is always used to apply an action on searched files
#
ply_file_action:
  match: '.*/.*\.(jpg|jpeg|gif|png|yml|yaml)$'
  prio: '0'
  do:
    - action: '+'
      args:
      - 'file_action'
      - 'ply'
testenv_file:
  search: '/(testenv.py|conf.py|_check4deps_.py)'
  ctx: 'pass1 and first_line'
  prio: '1'
  do:
    - action: '+'
      args:
        - 'file_action'
        - 'no'
ignore_file:
  match: '.*/.*\.(pyc|pyo|bak|tmp)$'
  prio: '0'
  do:
    - action: '+'
      args:
      - 'file_action'
      - 'no'