# This configuration is loaded when source file is a HISTORY/CHANGELOG file
# and product is Odoo
#
version:
  match: '.*[0-9]+\(?:\\.[0-9]+\)+'
  prio: '9'
  do:
    - action: '$'
      args:
      - match_version