# This configuration is loaded when source file is a manifest file
# and product is Odoo
#
version:
  match: "^ *[\"']version[\"']*: [\"'][0-9]+(?:\\.[0-9]+)+[\"']"
  prio: '9'
  do:
    - action: '$'
      args:
      - match_version
version_depends:
  match: "^ *[\"']version_depends[\"']*: .*[0-9]+(?:\\.[0-9]+)+[\"']"
  prio: '9'
  do:
    - action: '$'
      args:
      - match_version
