#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on clodoo
#
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
if [ -z "$ODOOLIBDIR" ]; then
  echo "Library file odoorc not found!"
  exit 2
fi
. $ODOOLIBDIR
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/zerobug $HOME/dev" "zerobug")
if [ -z "$Z0TLIBDIR" ]; then
  echo "Library file z0testrc not found!"
  exit 2
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.3.6.32


Z0BUG_setup() {
    # Just for regression tests
    coveragerc_file="$RUNDIR/.coveragerc"
    coveragerc_bak="$RUNDIR/coveragerc.bak"
    if [ ! -f "$coveragerc_bak" ]; then
      if [ -f "$coveragerc_file" ]; then
         mv -f $coveragerc_file $coveragerc_bak
      fi
    fi
    if [ -f "$coveragerc_file" ]; then
      rm -f $coveragerc_file
    fi
    if [ "${PWD:0:19}" == "/opt/odoo/dev/pypi/" ]; then
      cp -p /opt/odoo/tools/z0lib/z0librc ./
    fi
}

Z0BUG_teardown() {
    if [ -f "$coveragerc_file" ]; then
      rm -f $coveragerc_file
    fi
    if [ -f "$coveragerc_bak" ]; then
      mv -f $coveragerc_bak $coveragerc_file
    fi
}


Z0BUG_init
parseoptest -l$TESTDIR/test_clodoo.log "$@" "-O"
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi
if [ ${opt_oeLib:-0} -ne 0 ]; then
  TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
  if [ -z "$TRAVISLIBDIR" ]; then
    echo "Library file travisrc not found!"
    exit 2
  fi
  . $TRAVISLIBDIR
fi

UT1_LIST=
UT_LIST="__version_V_0.1.17.3$RUNDIR/odoo_skin.sh"
# UT_LIST="$UT_LIST __version_V_0.3.6.32$RUNDIR/transodoo.py"
UT_LIST="$UT_LIST clodoo_test_01.py clodoo_test_02.py clodoo_test_odoo_skin.sh clodoo_test_odoorc.sh"
if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
export PYTHONPATH=/opt/odoo/dev/pypi/zerobug:/opt/odoo/dev/pypi/clodoo
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
exit $sts
