#! /bin/bash
# -*- coding: utf-8 -*-
#
# Download github repository into local odoo installation
#
# This free software is released under GNU Affero GPL3
# author: Antonio M. Vigliotti <antoniomaria.vigliotti@gmail.com>
# (C) 2015-2020 by SHS-AV s.r.l. - http://www.shs-av.com <info@shs-av.com>
#
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
for d in $TDIR $TDIR/.. $TDIR/../.. $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
  if [ -e $d/z0librc ]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  elif [ -d $d/z0lib ] && [ -e $d/z0lib/z0librc ]; then
    . $d/z0lib/z0librc
    Z0LIBDIR=$d/z0lib
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/dev ${PYPATH//:/ } . .." "clodoo")
if [ -z "$ODOOLIBDIR" ]; then
  echo "Library file odoorc not found!"
  exit 2
fi
. $ODOOLIBDIR
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)

__version__=0.3.9.18

rmdir_if_exists() {
#rmdir_if_exists (RPTNAME odoo_vid new_vid)
#export DSTPATH
      local RPTNAME=$1
      local odoo_vid=$2
      local odoo_fver=$(build_odoo_param FULLVER "$odoo_vid")
      local odoo_Rver=$(build_odoo_param GIT_BRANCH "$odoo_vid")
      local new_vid=$3
      local b fn
      if [ -n "$opt_odir" ]; then
        local DSTPATH=$opt_odir
      else
        local DSTPATH=$(build_odoo_param HOME $odoo_vid "$RPTNAME" "$def_opt_org")
      fi
      local sts
      if [ -d $DSTPATH ]; then
        echo "Repository $DSTPATH of $odoo_fver Odoo already exists"
        if [ $opt_yes -gt 0 -o $opt_dry_run -gt 0 ]; then
          a=y
        else
          read -p "confirm action (y/n)?" a
        fi
        if [ "$a" != "y" ]; then
          exit 1
        fi
        local CWD=$PWD
        git status -s &>/dev/null
        sts=$?
        if [ $sts -eq 0 -a "$new_vid" == "$odoo_vid" ]; then
          if [ "$DSTPATH" != "$PWD" ]; then
            run_traced "cd $DSTPATH"
          fi
          run_traced "git push origin --delete $odoo_Rver" "$pkg_user"
          if [ "$CWD" != "$PWD" ]; then
            run_traced "cd $CWD"
          fi
        fi
        if [ "$RPTNAME" == "OCB" ]; then
          OCB_SUBDIRS_RE=$(build_odoo_param OCB_SUBDIRS_RE)
          run_traced "mkdir $HOME/__to_remove"
          run_traced "mkdir $HOME/__to_remove/OCB"
          for fn in $DSTPATH/*; do
            if [ -f "$fn" ]; then
              run_traced "mv $fn $HOME/__to_remove/OCB"
            else
              b=$(basename $fn)
              if [[ $b =~ $OCB_SUBDIRS_RE ]]; then
                run_traced "mv $fn $HOME/__to_remove/OCB"
              else
                run_traced "mv $fn $HOME/__to_remove/"
              fi
            fi
          done
        fi
        run_traced "rm -fR $DSTPATH"
      fi
}

set_remote_info() {
#set_remote_info (RPTNAME odoo_vid pkg_URL odoo_org)
    local RPTNAME=$1
    local odoo_vid=$2
    local odoo_fver=$(build_odoo_param FULLVER "$odoo_vid")
    local pkg_URL=$3
    local doo_org=$4
    local UPSTREAM=$(build_odoo_param UPSTREAM $odoo_vid $RPTNAME $odoo_org)
    local rval
    if [ "$(build_odoo_param VCS $odoo_vid)" == "git" ]; then
      rval=$(build_odoo_param RUPSTREAM $odoo_vid)
      if [[ ! "$rval" == "$UPSTREAM" ]]; then
        [[ -n "$rval" ]] && run_traced "git remote remove upstream" "$pkg_user"
        [[ -n "$UPSTREAM" ]] && run_traced "git remote add upstream $UPSTREAM" "$pkg_user"
      fi
      rval=$(build_odoo_param RORIGIN $odoo_vid)
      if [[ ! "$rval" == "$pkg_URL" ]]; then
        [[ -n "$rval" ]] && run_traced "git remote remove origin" "$pkg_user"
        [[ -n "$pkg_URL" ]] && run_traced "git remote add origin $pkg_URL" "$pkg_user"
      fi
    else
      echo "No git repositoy $RPTNAME!"
    fi
}

wep_other_branches() {
#wep_other_branches(odoo_fver)
    local sts v x lne PARSE
    git status -s &>/dev/null
    sts=$?
    if [ $sts -eq 0 ]; then
      x=$(build_odoo_param RORIGIN $1)
      if [ "${x:0:15}" == "git@github.com:" ]; then
        git remote show origin 2>/dev/null> $TMPFILE
        PARSE=0
        while read -r lne r || [ -n "$lne" ]; do
          if [[ "$lne" =~ Remote[[:space:]]branches ]]; then
            PARSE=1
          elif [[ "$lne" =~  Local ]]; then
            PARSE=0
          elif [ $PARSE -gt 0 ]; then
            lne="$(echo $lne)"
            IFS=" " read v x <<< "$lne"
            if [[ ! $v =~ (6.1|7.0|8.0|9.0|10.0|11.0|12.0) ]] ; then
              run_traced "git push origin --delete $v" "$pkg_user"
            fi
          fi
        done < $TMPFILE
      fi
      for v in $(git branch|grep -Eo [0-9.]+); do
        if [[ -n "$v" && -n "$1" &&  ! "$v" == "$1" ]] ; then
          run_traced "git branch -D $v" "$pkg_user"
        fi
      done
    fi
}

auto_add_files() {
#auto_add_files(odoo_fver)
     git status 2>/dev/null> $TMPFILE
     PARSE=0
     while IFS= read -r lne || [ -n "$lne" ]; do
     if [[ "$lne" =~ "# Untracked files:" ]]; then
       PARSE=1
     elif [ $PARSE -ne 0 ]; then
       if [[ $lne =~ (LICENSE|README\.md|README\.rst|.*\.bak) ]]; then
         lne=$(echo ${lne:1})
         run_traced "git add $lne" "$pkg_user"
       fi
     fi
     done < $TMPFILE
}

commit_files() {
#commmit_files(odoo_fver) {
    local odoo_fver=$1
    local x=$(build_odoo_param RORIGIN $1)
    if [ "${x:0:15}" == "git@github.com:" ]; then
      run_traced "git checkout -b $odoo_fver origin/$odoo_fver" "$pkg_user"
      run_traced "git format-patch --stdout origin/$odoo_fver -- $PWD | git am -3" "$pkg_user"
      run_traced "git push origin $odoo_fver" "$pkg_user"
    fi
}

update_odoo_conf() {
# update_odoo_conf(odoo_vid confn)
    local odoo_vid=$1
    if [ -z "$2" ]; then
      local confn=$(build_odoo_param CONFN $odoo_vid)
    else
      local confn=$1
    fi
    if [ ! -f $confn ]; then
      echo "File $confn not found!"
      exit 1
    fi
    local tgt=$confn.tmp
    [ -f $tgt ] && rm -f $tgt
    touch $tgt
    local DDIR=$(build_odoo_param DDIR $odoo_vid)
    local FLOG=$(build_odoo_param FLOG $odoo_vid)
    local FPID=$(build_odoo_param FPID $odoo_vid)
    local RPCPORT=$(build_odoo_param RPCPORT $odoo_vid)
    local odoo_ver=$(build_odoo_param MAJVER $odoo_vid)
    while IFS=\| read -r line || [ -n "$line" ]; do
      if [[ $line =~ ^data_dir[[:space:]]*=[[:space:]]*.*Odoo ]]; then
        line=$(echo "data_dir = $DDIR")
      elif [[ $line =~ ^logfile[[:space:]]*=[[:space:]]*.*  ]]; then
        line=$(echo "logfile = $FLOG")
      elif [[ $line =~ ^pidfile[[:space:]]*=[[:space:]]*.* ]]; then
        line=$(echo "pidfile = $FPID")
      elif [[ $line =~ ^[#[:space:]]*xmlrpc_port[[:space:]]*=[[:space:]]*[0-9]+ ]]; then
        if [ $odoo_ver -gt 10 ]; then
          line=$(echo "# xmlrpc_port = $RPCPORT")
        else
          line=$(echo "xmlrpc_port = $RPCPORT")
        fi
      elif [[ $line =~ ^[#[:space:]]*http_port[[:space:]]*=[[:space:]]*[0-9]+ ]]; then
        if [ $odoo_ver -gt 10 ]; then
          line=$(echo "http_port = $RPCPORT")
        else
          line=$(echo "# http_port = $RPCPORT")
        fi
      fi
      echo "$line">>$tgt
    done < "$confn"
    if $(diff -q $confn $tgt &>/dev/null); then
      rm -f $tgt
    else
      [ -f $confn.bak ] && rm -f $confn.bak
      mv $confn $confn.bak
      mv $tgt $confn
    fi
}

update_confn() {
  # update_confn(confn dstpath)
  if [ -z "$1" ]; then
    local confn=$(build_odoo_param CONFN $odoo_vid)
  else
    local confn=$1
  fi
  local DSTPATH=$2
  if [ $opt_noconf -eq 0 ]; then
    [[ ! $(grep "^addons_path *= .*$DSTPATH" $confn) ]] && run_traced "sed -i -e \"s|^addons_path *=.*|&,$DSTPATH|\" $confn"
  fi
}

OPTOPTS=(h        b          c        C          D        j        L        m          n            O         o         q           r          U       u          V           v           y       1)
OPTDEST=(opt_help opt_branch opt_conf opt_noconf opt_ucfg opt_only opt_link opt_multi  opt_dry_run  opt_org   opt_odir  opt_verbose opt_updrmt opt_upd opt_user   opt_version opt_verbose opt_yes opt_one)
OPTACTI=(1        "="        "="      1          1        1        1        1          1            "="       "="       0           1          1       "="        "*>"        "+"         1       1)
OPTDEFL=(0        ""         ""       0          0        0        0        0          0            ""        ""        -1          0          0       ""         ""          -1          0       0)
OPTMETA=("help"   "branch"   "file"   ""         ""       ""       ""       ""         "do nothing" "git-org" "path"    "verbose"   ""         ""      "username" "version"   "verbose"   ""      "")
OPTHELP=("this help"\
 "default odoo branch"\
 "configuration file (def .travis.conf)"\
 "do not touch configuration file (conflict with -D)"\
 "update default values in /etc configuration file before creating script (conflict with -C)"\
 "install only repository owned by git organization"\
 "create symbolic link rather copy files (if new_odoo_ver supplied)"\
 "multi-version odoo environment"\
 "do nothing (dry-run)"\
 "git organization, one of oca oia[-git|-http] zero[-git|-http] (def zero)"\
 "odoo directory"\
 "silent mode"\
 "do just update remote info (if no new_odoo_ver supplied)"\
 "do not install, do upgrade"
 "execute as username (def=odoo)"
 "show version"\
 "verbose mode"\
 "assume yes"\
 "if clone depth=1")
OPTARGS=(git_repo odoo_vid new_odoo_vid)

parseoptargs "$@"
if [ "$opt_version" ]; then
  echo "$__version__"
  exit $STS_SUCCESS
fi
if [ -z "$git_repo" ]; then
  opt_help=1
elif [ -z "$odoo_vid" -a -z "$opt_branch" ]; then
  opt_help=1
fi
if [ $opt_noconf -ne 0 -a $opt_ucfg -ne 0 ]; then
  opt_help=1
fi
if [ $opt_help -gt 0 ]; then
  print_help "Add or duplicate odoo repository into local filesystem"\
  "(C) 2015-2020 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
  exit $STS_SUCCESS
fi
if [ $opt_verbose -eq -1 ]; then
  opt_verbose=1
fi
if [ -n "$opt_branch" ]; then
  if [ -z "$odoo_vid" ]; then
    odoo_vid=$opt_branch
  elif [ -z "$new_odoo_vid" ]; then
    new_odoo_vid=$opt_branch
  elif [ -n "$new_odoo_vid" ]; then
    echo "Invalid parameters"
    echo "You cannot declare new branch with -b option switch and with 3th parameter"
    exit 1
  fi
fi
discover_multi
TMPFILE=$HOME/tmp_$$.out
odoo_fver=$(build_odoo_param FULLVER "$odoo_vid")
odoo_ver=$(build_odoo_param MAJVER $odoo_fver)
odoo_rver=$(build_odoo_param GIT_BRANCH "$odoo_vid")
pkg_URL=$git_repo
RPTNAME=$(basename $git_repo)
[ -z "$opt_org" ] && opt_org=$(build_odoo_param GIT_ORGID $odoo_vid)
if [[ $odoo_vid =~ (14\.0|13\.0|12\.0|11\.0|10\.0|9\.0|8\.0|7\.0|6\.1) && "$opt_org" == "zero" ]]; then
  def_opt_org=
else
  def_opt_org=$opt_org
fi
if [ -n "$opt_user" -a "$opt_user" != "$USER" -a $EUID -eq 0 ]; then
  pkg_user="$opt_user"
elif [ -z "$opt_user" -a "$USER" != "travis" -a $EUID -eq 0 ]; then
  pkg_user="odoo"
else
  pkg_user=
fi
if [ "${RPTNAME: -4}" == ".git" ]; then
  RPTNAME=${RPTNAME:0: -4}
fi
if [ "${RPTNAME: -1}" == "/" ]; then
  RPTNAME=${RPTNAME:0: -1}
fi
if [ "${pkg_URL: -1}" == "/" ]; then
  pkg_URL=${pkg_URL:0: -1}
fi
odoo_root=$(build_odoo_param ROOT $odoo_vid "OCB" $def_opt_org)
if [ -z "$new_odoo_vid" ]; then
  new_odoo_fver=$odoo_fver
  if [ "$pkg_URL" == "$RPTNAME" ]; then
    pkg_URL=$(build_odoo_param GIT_URL $odoo_fver $RPTNAME $opt_org)
  fi
  ORGNM=$(build_odoo_param GIT_ORGNM $odoo_vid $RPTNAME $opt_org)
  if [ $opt_only -ne 0 ]; then
    x=$(build_odoo_param GIT_ORGNM $odoo_vid OCB $opt_org)
  else
    x=$ORGNM
  fi
  if [ -n "$opt_odir" ]; then
    DSTPATH=$opt_odir
    [ "$RPTNAME" == "OCB" ] && odoo_root=$DSTPATH || odoo_root=$(dirname $DSTPATH)
  else
    DSTPATH=$(build_odoo_param HOME $odoo_vid "$RPTNAME" "$def_opt_org")
  fi
  [ "$x" != "$ORGNM" ] && exit 0
  if [ $opt_upd -gt 0 ]; then
    if [ "$DSTPATH" != "$PWD" ]; then
      run_traced "cd $DSTPATH"
    fi
    run_traced "git stash" "$pkg_user"
    if [ "$RPTNAME" == "OCB" ]; then
      run_traced "git pull origin $odoo_rver --no-recurse-submodules" "$pkg_user"
    else
      run_traced "git pull origin $odoo_rver" "$pkg_user"
    fi
    update_confn "" $DSTPATH
    exit 0
  elif [ $opt_updrmt -eq 0 ]; then
    rmdir_if_exists $RPTNAME $odoo_vid ""
    git_opts="-b $odoo_rver"
    if [ $opt_one -gt 0 ]; then
      x="--depth 1 --single-branch"
    else
      x=$(build_odoo_param GIT_OPTS $odoo_vid $RPTNAME $opt_org)
    fi
    if [ -n "$x" ]; then
      git_opts="$git_opts $x"
    fi
    if [ -n "$opt_odir" ]; then
      pardir=$(dirname $opt_odir)
    else
      pardir=$(dirname $DSTPATH)
    fi
    if [ "$PWD" != "$pardir" ]; then
      run_traced "cd $pardir"
    fi
    pkgdir=$(basename $DSTPATH)
    run_traced "git clone $pkg_URL $pkgdir/ $git_opts" "$pkg_user"
    if [ $? -ne 0 ]; then
      echo "Error cloning $pkgdir"
      exit 1
    fi
  fi
  if [ ! -d $DSTPATH ]; then
    echo "Directory $DSTPATH not found!"
    exit 1
  fi
  if [ "$DSTPATH" != "$PWD" ]; then
    run_traced "cd $DSTPATH"
  fi
  if [ "$RPTNAME" == "OCB" ]; then
    run_traced "mv $HOME/__to_remove $DSTPATH"
    discover_multi
    cfgfn=$(build_odoo_param CONFN "$odoo_vid" '' $def_opt_org)
    if [ ! -f "$cfgfn" ]; then
      odoo_bin=$(build_odoo_param BIN "$odoo_vid" "search")
      [ -z "$odoo_bin" ] && odoo_bin=$(build_odoo_param BIN "$odoo_vid")
      [ -f ~/.odoorc ] && run_traced "rm -f  ~/.odoorc" "$pkg_user"
      [ -f ~/.openerp_serverrc ] && run_traced "rm -f  ~/.openerp_serverrc" "$pkg_user"
      user=$(build_odoo_param USER "$odoo_vid")
      flog=$(build_odoo_param FLOG "$odoo_vid")
      fpid=$(build_odoo_param FPID "$odoo_vid")
      rport=$(build_odoo_param RPCPORT "$odoo_vid")
      if [ $odoo_ver -ge 7 ]; then
        pdir=$(build_odoo_param DDIR "$odoo_vid")
        if [ ! -d $pdir ]; then
          run_traced "mkdir -p $pdir" "$pkg_user"
          # run_traced "chown odoo:odoo $pdir"
        fi
        [ $odoo_ver -gt 7 ] && pdir="-D $pdir" || pdir=
      fi
      run_traced "$odoo_bin -r $user --logfile=$flog --pidfile=$fpid --xmlrpc-port=$rport $pdir -s --stop-after-init" "$pkg_user"
      OHOME=$(build_odoo_param PARENTDIR "$odoo_vid")
      if [ -f $OHOME/.openerp_serverrc ]; then
        run_traced "mv $OHOME/.openerp_serverrc $cfgfn" "$pkg_user"
      elif [ -f $OHOME/.odoorc ]; then
        run_traced "mv $OHOME/.odoorc $cfgfn" "$pkg_user"
      fi
      run_traced "chown odoo:odoo $cfgfn"
      [ $opt_ucfg -ne 0 ] && update_odoo_conf $odoo_vid $opt_cfg
    fi
  fi
else
  if [ "$odoo_vid" == "$new_odoo_vid" ]; then
    echo "Same source and target version"
    exit 1
  fi
  SRCPATH=$(build_odoo_param HOME $odoo_vid "$git_repo" "$def_opt_org")
  if [ -n "$opt_odir" ]; then
    DSTPATH=$opt_odir
  else
    DSTPATH=$(build_odoo_param HOME $new_odoo_vid "$git_repo" "$def_opt_org")
  fi
  if [ "$SRCPATH" == "$DSTPATH" ]; then
    echo "Same source and target version"
    exit 1
  fi
  new_odoo_fver=$(build_odoo_param FULLVER "$new_odoo_vid")
  if [ "$pkg_URL" == "$RPTNAME" ]; then
    pkg_URL=$(build_odoo_param GIT_URL $new_odoo_fver $RPTNAME $opt_org)
  fi
  DSTROOT=$(readlink -e $DSTPATH/..)
  if [ -z "$DSTROOT" ]; then
    echo "Cannot evaluate target root!"
    exit 1
  fi
  ORGNM=$(build_odoo_param GIT_ORGNM $new_odoo_vid $RPTNAME $opt_org)
  if [ $opt_only -ne 0 ]; then
    x=$(build_odoo_param GIT_ORGNM $new_odoo_vid OCB $opt_org)
  else
    x=$ORGNM
  fi
  [ "$x" != "$ORGNM" ] && exit 0
  if [ -d "$DSTPATH" ]; then
    run_traced "rm -fR $DSTPATH"
  fi
  if [ $opt_link -eq 0 ]; then
    run_traced "cp -r $SRCPATH/ $DSTROOT"
  else
    run_traced "ln -s $SRCPATH/ $DSTROOT"
  fi
  if [ "$DSTPATH" != "$PWD" ]; then
    run_traced "cd $DSTPATH"
  fi
  odoo_root=$(build_odoo_param ROOT $new_odoo_vid "OCB" $def_opt_org)
fi
if [ -z "$new_odoo_vid" ]; then
  new_odoo_vid=$odoo_vid
fi
set_remote_info "$RPTNAME" "$new_odoo_vid" "$pkg_URL" "$opt_org"
if [ $opt_updrmt -eq 0 ]; then
  auto_add_files "$new_odoo_fver"
  commit_files "$new_odoo_fver"
  wep_other_branches "$new_odoo_fver"
fi
is_submodule=$(build_odoo_param VCS $new_odoo_vid)
[ -n "$is_submodule" ] && git_orgnm=$(build_odoo_param RORIGIN $new_odoo_vid) || git_orgnm=
[ -n "$git_orgnm" ] && git_orgnm=$(dirname $git_orgnm)
if [ "$odoo_root" != "$PWD" ]; then
  run_traced "cd $odoo_root"
fi
if [ "$RPTNAME" != "OCB" -a -n "$is_submodule" ]; then
  root_orgnm=$(build_odoo_param RORIGIN $new_odoo_vid)
  [ -n "$root_orgnm" ] && root_orgnm=$(dirname $root_orgnm)
  if [ -n "$root_orgnm" -a "$root_orgnm" == "$git_orgnm" ]; then
    x=$(git submodule status 2>/dev/null|grep $RPTNAME)
    if [ -z "$x" ]; then
      run_traced "git submodule add -f $pkg_URL $RPTNAME/" "$pkg_user"
    fi
  else
    echo "Warning: origin '$git_orgnm' of '$RPTNAME' does not match origin '$root_orgnm'!"
  fi
fi
if [ -z "$(grep "$RPTNAME/" .gitignore 2>/dev/null)" ]; then
   run_traced "echo "$RPTNAME/">>.gitignore"
fi
confn=$(build_odoo_param CONFN "$new_odoo_vid" '' $def_opt_org)
if [ "$RPTNAME" == "OCB" ]; then
  DSTPATH="$DSTPATH/addons"
fi
update_confn $confn $DSTPATH
rm -f $TMPFILE
exit 0
