#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on zerobug
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in "$TDIR" "." ".." "~" "/etc"; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
  fi
done
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.2.3.0


Z0BUG_init
parseoptest -l$TESTDIR/test_zerobug.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi

# Just for regression tests
coveragerc_file="$RUNDIR/.coveragerc"
coveragerc_bak="$RUNDIR/coveragerc.bak"
if [ ! -f "$coveragerc_bak" ]; then
  if [ -f "$coveragerc_file" ]; then
     mv -f $coveragerc_file $coveragerc_bak
  fi
fi
if [ -f "$coveragerc_file" ]; then
  rm -f $coveragerc_file
fi
Z0BUG_main_file "" ""
if [ -f "$coveragerc_file" ]; then
  rm -f $coveragerc_file
fi
if [ -f "$coveragerc_bak" ]; then
  mv -f $coveragerc_bak $coveragerc_file
fi
exit $sts
