#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on zerobug
#
THIS=$(basename $0)
TDIR=$(readlink -f $(dirname $0))
for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
  if [ -e $x/z0librc ]; then
    . $x/z0librc
    Z0LIBDIR=$x
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [ -z "$Z0LIBDIR" ]; then
  echo "Library file z0librc not found!"
  exit 2
fi
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
RUNDIR=$(readlink -e $TESTDIR/..)
Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)

__version__=0.2.6


Z0BUG_init
parseoptest -l$TESTDIR/test_zerobug.log $@
sts=$?
if [ $sts -ne 127 ]; then
  exit $sts
fi

UT1_LIST=""
UT_LIST="__version_0_${__version__}$Z0TLIBDIR/z0testrc"
UT_LIST="$UT_LIST __version_1_0.1.43$Z0LIBDIR/z0librc"
UT_LIST="$UT_LIST __version_V_0.2.0$TESTDIR/dummy_01.py"
UT_LIST="$UT_LIST __version_v_0.2.1$TESTDIR/dummy_01.py"
UT_LIST="$UT_LIST __version_P_0.2.2$TESTDIR/dummy_01.py"
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
exit $?
