#! /bin/bash
# -*- coding: utf-8 -*-
# Regression tests on travis emulator
#
READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
export READLINK
THIS=$(basename "$0")
TDIR=$(readlink -f $(dirname $0))
[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
for d in $PYPATH /etc; do
  if [[ -e $d/z0librc ]]; then
    . $d/z0librc
    Z0LIBDIR=$d
    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
    break
  fi
done
if [[ -z "$Z0LIBDIR" ]]; then
  echo "Library file z0librc not found!"
  exit 72
fi
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
TESTDIR=$(findpkg "" "$TDIR . .." "tests")
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
RUNDIR=$(readlink -e $TESTDIR/..)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
RED="\e[1;31m"
GREEN="\e[1;32m"
CLR="\e[0m"
Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
if [[ -z "$Z0TLIBDIR" ]]; then
  echo "Library file z0testrc not found!"
  exit 72
fi
. $Z0TLIBDIR
Z0TLIBDIR=$(dirname $Z0TLIBDIR)
[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"

__version__=1.0.2.7


test_01() {
    # Test RST files
    local TESTOUT TESTRES TESTFN
    TESTFN=test_gen_readme_01
    TESTSRC=$TESTDIR/res/$TESTFN.rst
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/README.rst
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTOUT
      # Files in module directory (tested branch is 11.0)
      cat <<EOF >$TESTDIR/res/__manifest__.py
{
    'name': 'mtest',
}
EOF
      # Files in egg-info of module directory (tested branch is 11.0)
      cat <<EOF >$TESTDIR/res/descrizione.rst
Lorem ipsum
-----------

Lorem ipsum **dolor** sit amet
.. \$if branch in '12.0'
odoo 12.0
.. \$elif branch in '10.0'
odoo 10.0
.. \$elif branch in '8.0'
odoo 8.0
.. \$else
consectetur *adipiscing* elit
.. \$fi

* Feature A
* Feature B

::

    >>> doc
|
.. image:: logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

+-----------+---------+
| Feature A | |check| |
+-----------+---------+
| Feature B |         |
+-----------+---------+
EOF
      cat <<EOF >$TESTDIR/res/authors.txt
.. \$if branch in '12.0'
* wrong author
.. \$elif branch in '11.0'
* SHS-AV s.r.l. <https://www.shs-av.com>
.. \$elif branch in '10.0'
* wrong author
.. \$elif branch in '7.0'
* SHS-AV s.r.l. <https://www.zeroincombenze.it>
.. \$else
* unknown authors
.. \$fi
EOF
      cat <<EOF >$TESTDIR/res/contributors.txt
.. \$if branch in '12.0'
* wrong contributor <wrong@example.com>
.. \$elif branch in '11.0'
* antonio <antoniov@libero.it>
.. \$elif branch in '10.0'
* alberta <alberta@libero.it>
.. \$elif branch in '9.0'
* daniela <daniela@libero.it>
.. \$elif branch in '7.0'
* antonio <antoniov@shs-av.com>
.. \$else
* unknown contributor <unknow@example.com>
.. \$fi
EOF
      # Files in template directory
      cat <<EOF >$TESTSRC
===============
|icon| {{name}}
===============

Test file

Overview
========

{{descrizione}}

{{authors}}
{{contributors}}
{{acknowledges}}
.. \$include footer.rst
EOF
      cat <<EOF >$TESTDIR/res/footer.rst

----------------------

.. |en| image:: {{grymb_image_en}}
   :target: {{grymb_url_en}}
.. |it| image:: {{grymb_image_it}}
   :target: {{grymb_url_it}}
EOF
      cat <<EOF >$TESTDIR/res/header_authors.txt

Authors
-------

EOF
      cat <<EOF >$TESTDIR/res/header_contributors.txt

Contributors
------------

EOF
      cat <<EOF >$TESTDIR/res/header_acknowledges.txt

Acknoledges to
--------------

EOF
      # Files for test match
      cat <<EOF >$TESTRES
============
|icon| mtest
============

Test file

Overview
========

Lorem ipsum
-----------

Lorem ipsum **dolor** sit amet
consectetur *adipiscing* elit

* Feature A
* Feature B

::

    >>> doc
|
.. image:: https://raw.githubusercontent.com/zeroincombenze/rtest/11.0/mtest/static/description/logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

+-----------+---------+
| Feature A | |check| |
+-----------+---------+
| Feature B |         |
+-----------+---------+



Authors
-------

* \`SHS-AV s.r.l. <https://www.shs-av.com>\`__

Contributors
------------

* antonio <antoniov@libero.it>


Acknoledges to
--------------

* daniela <daniela@libero.it>
* alberta <alberta@libero.it>


----------------------

.. |en| image:: https://raw.githubusercontent.com/zeroincombenze/grymb/master/flags/en_US.png
   :target: https://www.facebook.com/Zeroincombenze-Software-gestionale-online-249494305219415/
.. |it| image:: https://raw.githubusercontent.com/zeroincombenze/grymb/master/flags/it_IT.png
   :target: https://www.facebook.com/Zeroincombenze-Software-gestionale-online-249494305219415/


EOF
      pushd $TESTDIR/res &>/dev/null
      $RUNDIR/gen_readme.py -q -b11.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w
      popd &>/dev/null
    fi
    test_result "gen_readme.py -q -b11.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w" "$TESTOUT" "$TESTRES" "diff"
}

test_02() {
    # Test HTML files
    local TESTOUT TESTRES TESTFN
    TESTFN=test_gen_readme_02
    TESTSRC=$TESTDIR/res/$TESTFN.html
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/index.html
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTOUT
      # Files in template directory
      rm -f $TESTDIR/res/header_authors.txt
      cat <<EOF >$TESTSRC
<section class="oe_container">

Test file

<h1>Overview</h1>

{{descrizione}}

{{authors}}
</section>
EOF
      # Files for test match (tested branch is 11.0)
      cat <<EOF >$TESTRES

<section class="oe_container">

Test file

<h1>Overview</h1>

<h2>mtest / Lorem ipsum</h2>
<p align="justify">
Lorem ipsum <b>dolor</b> sit amet
consectetur <i>adipiscing</i> elit
</p><p align="justify">
<ul>
<li>Feature A</li>
<li>Feature B</li>
</ul>
</p><p align="justify">

<code>
    &gt;&gt;&gt; doc
</code>
<br/>
</p>
<img src="logo.png"/>
<p align="justify">
<table style="width:100%; padding:2px; border-spacing:2px; text-align:left;"><tr>
<td>Feature A</td><td><img src="https://raw.githubusercontent.com/zeroincombenze/grymb/master/awesome/check.png"/></td>
</tr><tr>
<td>Feature B</td><td/>
</tr></table>
</p>

<ul>
<li><a href="https://www.shs-av.com/">SHS-AV s.r.l.</a></li>
</ul>
</section>
EOF
      pushd $TESTDIR/res &>/dev/null
      $RUNDIR/gen_readme.py -qTH -b11.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w
      popd &>/dev/null
    fi
    test_result "gen_readme.py -qTH -b11.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w" "$TESTOUT" "$TESTRES" "diff"
}


test_03() {
    # Test manifest
    local TESTOUT TESTRES TESTFN
    TESTFN=test_gen_readme_03
    TESTSRC=$TESTDIR/res/readme_manifest.rst
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/__openerp__.py
    TESTRDNME=$TESTDIR/res/README.rst
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTOUT
      [[ -f $TESTRDNME ]] && rm -f $TESTRDNME
      # Files in module directory
      cat <<EOF >$TESTDIR/res/__openerp__.py
# (C) SHS-Av s.r.l.
{
    'name': 'test',
    'depends': ['base', 'account'],
}
EOF
      # Files in template directory
      cat <<EOF >$TESTSRC

Overview
========

|it| {{descrizione}}

{{authors}}
{{contributors}}
.. \$include footer.rst
EOF
      # Files for test match
      cat <<EOF >$TESTRES
# (C) SHS-Av s.r.l.
{
    'name': 'test',
    'version': '7.0.0.1.0',
    'development_status': 'Alpha',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'account',
    ],
    'description': r'''
Overview
========

|it| Lorem ipsum
----------------

Lorem ipsum **dolor** sit amet
consectetur *adipiscing* elit

* Feature A
* Feature B

::

    >>> doc
|
.. image:: /mtest/static/src/img/logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

+-----------+---------+
| Feature A | |check| |
+-----------+---------+
| Feature B |         |
+-----------+---------+


* \`SHS-AV s.r.l. <https://www.zeroincombenze.it>\`__

Contributors
------------

* antonio <antoniov@shs-av.com>


----------------------

.. |en| image:: https://raw.githubusercontent.com/zeroincombenze/grymb/master/flags/en_US.png
   :target: https://www.facebook.com/Zeroincombenze-Software-gestionale-online-249494305219415/
.. |it| image:: https://raw.githubusercontent.com/zeroincombenze/grymb/master/flags/it_IT.png
   :target: https://www.facebook.com/Zeroincombenze-Software-gestionale-online-249494305219415/


''',
}
EOF
      pushd $TESTDIR/res &>/dev/null
      $RUNDIR/gen_readme.py -qR -b7.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w
      popd &>/dev/null
    fi
    test_result "gen_readme.py -qR -b7.0  -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w" "$TESTOUT" "$TESTRES" "diff"
}


test_04() {
    # Test CSV files
    local TESTOUT TESTRES TESTFN
    TESTFN=test_gen_readme_04
    TESTSRC=$TESTDIR/res/$TESTFN.rst
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/README.rst
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTOUT
      # Files in module directory (tested branch is 11.0)
      cat <<EOF >$TESTDIR/res/__manifest__.py
{
    'name': 'mtest',
}
EOF
      # Files in egg-info of module directory (tested branch is 11.0)
      cat <<EOF >$TESTDIR/res/descrizione.rst
Lorem ipsum
-----------

Lorem ipsum **dolor** sit amet
.. \$if branch in '12.0'
odoo 12.0
.. \$elif branch in '10.0'
odoo 10.0
.. \$elif branch in '8.0'
odoo 8.0
.. \$else
consectetur *adipiscing* elit
.. \$fi

* Feature A
* Feature B

::

    >>> doc
|
.. image:: logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

.. \$include features.csv
EOF
      cat <<EOF >$TESTDIR/res/features.csv
Feature A,|check|
Feature B,
EOF
      cat <<EOF >$TESTDIR/res/authors.txt
.. \$if branch in '12.0'
* wrong author
.. \$elif branch in '11.0'
* SHS-AV s.r.l. <https://www.shs-av.com>
.. \$elif branch in '10.0'
* wrong author
.. \$elif branch in '7.0'
* SHS-AV s.r.l. <https://www.zeroincombenze.it>
.. \$else
* unknown authors
.. \$fi
EOF
      cat <<EOF >$TESTDIR/res/contributors.txt
.. \$if branch in '12.0'
* wrong contributor <wrong@example.com>
.. \$elif branch in '11.0'
* antonio <antoniov@libero.it>
.. \$elif branch in '10.0'
* alberta <alberta@libero.it>
.. \$elif branch in '9.0'
* daniela <daniela@libero.it>
.. \$elif branch in '7.0'
* antonio <antoniov@shs-av.com>
.. \$else
* unknown contributor <unknow@example.com>
.. \$fi
EOF
      # Files in template directory
      cat <<EOF >$TESTSRC
===============
|icon| {{name}}
===============

Test file

Overview
========

{{descrizione}}

{{authors}}
{{contributors}}
{{acknowledges}}
.. \$include footer.rst
EOF
      cat <<EOF >$TESTDIR/res/footer.rst

----------------------

.. |en| image:: {{grymb_image_en}}
   :target: {{grymb_url_en}}
.. |it| image:: {{grymb_image_it}}
   :target: {{grymb_url_it}}
EOF
      cat <<EOF >$TESTDIR/res/header_authors.txt

Authors
-------

EOF
      cat <<EOF >$TESTDIR/res/header_contributors.txt

Contributors
------------

EOF
      cat <<EOF >$TESTDIR/res/header_acknowledges.txt

Acknoledges to
--------------

EOF
      # Files for test match
      cat <<EOF >$TESTRES
============
|icon| mtest
============

Test file

Overview
========

Lorem ipsum
-----------

Lorem ipsum **dolor** sit amet
consectetur *adipiscing* elit

* Feature A
* Feature B

::

    >>> doc
|
.. image:: https://raw.githubusercontent.com/zeroincombenze/rtest/11.0/mtest/static/description/logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

+-----------+---------+
| Feature A | |check| |
+-----------+---------+
| Feature B |         |
+-----------+---------+





Authors
-------

* \`SHS-AV s.r.l. <https://www.shs-av.com>\`__

Contributors
------------

* antonio <antoniov@libero.it>


Acknoledges to
--------------

* daniela <daniela@libero.it>
* alberta <alberta@libero.it>


----------------------

.. |en| image:: https://raw.githubusercontent.com/zeroincombenze/grymb/master/flags/en_US.png
   :target: https://www.facebook.com/Zeroincombenze-Software-gestionale-online-249494305219415/
.. |it| image:: https://raw.githubusercontent.com/zeroincombenze/grymb/master/flags/it_IT.png
   :target: https://www.facebook.com/Zeroincombenze-Software-gestionale-online-249494305219415/


EOF
      pushd $TESTDIR/res &>/dev/null
      $RUNDIR/gen_readme.py -q -b11.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w
      popd &>/dev/null
    fi
    test_result "gen_readme.py -q -b11.0 -lmodule -mmtest -rrtest -Gzero -t$TESTSRC -p$TESTDIR/res -Podoo -w" "$TESTOUT" "$TESTRES" "diff"
}


test_05() {
    # Test __manifest__.py    local TESTOUT TESTRES TESTFN
    TESTFN=test_gen_readme_05
    TESTSRC=$TESTDIR/res/$TESTFN.py
    TESTRES=$TESTDIR/res/$TESTFN.test
    TESTOUT=$TESTDIR/res/__manifest__.py
    if [ ${opt_dry_run:-0} -eq 0 ]; then
      rm -f $TESTOUT
      touch $TESTDIR/res/__init__.py
      cat <<EOF >$TESTDIR/res/__manifest__.py
{
    'name': 'mtest',
    'version': '12.0.1.0',
}
EOF
      # Files for test match
      cat <<EOF >$TESTRES
{
    'name': 'mtest',
    'version': '12.0.1.0',
    'author': 'powERP enterprise network',
    'website': 'https://www.powerp.it',
    'development_status': 'Alpha',
    'license': 'OPL-1',
}
EOF
      pushd $TESTDIR/res &>/dev/null
      $RUNDIR/gen_readme.py -q -b12.0 -Gpowerp -WR -w
      popd &>/dev/null
    fi
    test_result "gen_readme.py -q -b12.0 -Gpowerp -WR -w" "$TESTOUT" "$TESTRES" "diff"
}

Z0BUG_init
parseoptest -l$TESTDIR/test_wok_code.log "$@"
sts=$?
[[ $sts -ne 127 ]] && exit $sts



UT1_LIST=""
UT_LIST=""
[[ "$(type -t Z0BUG_setup)" == "function" ]] && Z0BUG_setup
Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
sts=$?
[[ "$(type -t Z0BUG_teardown)" == "function" ]] && Z0BUG_teardown
exit $sts
